### ISSUE TITLE
Revisit contact info in Help section

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1015]
So that filers and others can get in touch with the people who can help them, ensure that the right contact information is accessible from the right points in the Help section.

---

This issue is to follow up on a discussion today around the need to include contact information for the Info Division somewhere from the Help section.

cc @llienfec @PaulClark2 @emileighoutlaw

**Comment by AmyKort** [comment]
@llienfec Do you want to take the first crack at this?

**Comment by llienfec** [comment]
@AmyKort Yep, sounds interesting.  Happy to help out.

**Comment by PaulClark2** [comment]
A few thoughts (subject to revision by folks that know Info. Div and RAD better than I do).

Questions about filing and reporting (Get help with filing and reporting)

General questions about filing and reporting - Information Division
(general public, registered and unregistered entities)

Questions about campaign finance law (not rising to the level of an AO) - Information Division
(all)

Can I do an thing? - Information Division
(general public, registered and unregistered entities)

How do I report a thing? RAD
(registered entities)

Technical help? EFO and RAD
(registered entities)

**Comment by llienfec** [comment]
Really good thoughts @PaulClark2   Amy also had a list of who may to to which office for what.

It seems like we all agree that Info, RAD and EFO should be the main contacts on the content pages.  Can we keep the contacts simpler by having standard contacts at the bottom?  That way we don't need to predict why people are calling us.  Something along the bottom of the content pages, like:

For general help, contact Info.
For reporting help, contact RAD.
For efiling help, contact EFO.

I remember (or feel like I remember, but who knows) a mock up where the contacts were buttons lower on the page.  Would that be a possibility?

**Comment by PaulClark2** [comment]
Simple and standardized is good. It also allows use to reuse the contact "buttons" or text elsewhere.

**Comment by llienfec** [comment]
@noahmanger Do you think this approach for contacts would work for pre-flip?

**Comment by nickykrause** [comment]
@emileighoutlaw and I chatted about this quite a bit this morning, and here is a summary of our thoughts. (cc: @llienfec @PaulClark2 @jenniferthibault) 

There is a lot take take in here, I realize -- **we can chat about it in the design pairing on Friday if that's easier** 💬 

---

**The user need we're trying to meet** 
Users sometimes have questions for the FEC. They need to be able to contact the FEC with their questions and feel confident that they will reach the person who can help them best.

**Things we know** 
We know that users' questions vary across many topics. Some of the questions that users have will be best addressed by RAD, and some by InfoDiv, and some by EFO. 
 
We know that users will sometimes rush to call the FEC without first trying to answer their questions via the website. 
- We suspect this may be due to some confusion with using the old website and are hopeful that the new website will assist users in finding their answers before they call. 

**Our goals** 
- Present website content in such a way that users will be more able and more likely to answer their questions on their own
- Help users can find contact information, when they do need it
- Help users reach the correct group at the FEC as efficiently as possible

**Where we are now**
At the moment, we have a general contact link in the footer of the page:

![image](https://cloud.githubusercontent.com/assets/1450173/25675401/f500de14-3003-11e7-865e-29509c0ece72.png)

 
We also have a `Submit a question to RAD` link in the main navigation fly-out for the `Help for candidates & committees` (H4CC) section:
![image](https://cloud.githubusercontent.com/assets/1450173/25675386/e529da68-3003-11e7-8592-2f5a48b52d84.png)

Finally, at the bottom of the H4CC landing page, we have a card calling out the RAD form:
![image](https://cloud.githubusercontent.com/assets/1450173/25675448/18999578-3004-11e7-8728-e0fac4f79c20.png)

**Concerns with the current state**
The RAD contact info is over-emphasized. It may make it seem like all questions should go to RAD, when that is not true. Users might end up at the wrong place, since certain questions are better addressed by InfoDiv or EFO.

**Possible solutions we considered**

💡  1. Highlight the InfoDiv & EFO contact information the same way as RAD
---
➕ This would address the problem of RAD being over-emphasized, and it would make contact info easy to find when it is needed, but it may create other problems... 
➖ For example, we would be listing a lot of contact information with high prominence, such that users may think their best bet is to call, rather than trying to find the answer in the website content first. This wouldn't really give us a chance to see if the new website structure is really working as a means of reducing calls.
➖  Depending on how this solution is implemented, we might end up violating our content principle of trying to have "one home" for content elements, and we could have maintenance issues. (i.e., if we place InfoDiv contact on some pages, and RAD info on others, etc.)

💡  2. Remove the call-outs to RAD, put the RAD link on the contact page
---
➕  This would address the problem of RAD being over-emphasized and would be consistent with our principle of having "one home" for things. 
➖  However, it may not sufficiently address the goal of making contact info "easy to find." Users who can't find what they're looking for in Help for candidates & committees would need to find the contact link in the footer. 
    - We could test this. People might very well be able to find it. We don't really know.

:1st_place_medal: 💡  3. Remove the call-outs to RAD, put the RAD link on the contact page, AND offer a call-out to the contact page in certain highly-relevant locations.
---
➕  This would address the problem of RAD being over-emphasized and would be consistent with our principle of having "one home" for things. 
➕ It may also help us to anticipate users' questions and drive them to the contact page without giving too much prominence to the notion of contacting the FEC.

**Our hypothesis**
Our hypothesis is that option 3 will work best. :1st_place_medal: 

---

## **Design** 
After looking over some of the patterns for call-outs to helpful content, a few options come to mind:

1: A footer card that offers a general "contact the FEC" message, as opposed to a RAD message:
![image](https://cloud.githubusercontent.com/assets/1450173/25675978/0659de7a-3006-11e7-8e29-69ad52951409.png)

2: A callout in the right or left sidebar that encourages users to contact the FEC (and links to the contact page):

We're currently thinking of going with option 2 because it pulls the contact callout higher up, rather than pushing it down near the footer, where there is already a contact link close by. One possible placement for such a callout might be beneath the side nav (with a different icon, though):
![image](https://cloud.githubusercontent.com/assets/1450173/25676248/012340bc-3007-11e7-86e1-a3ea164e2ecf.png)

It would also be nice to include callouts deeper down in the content, rather than just on the landing page. If we do that, we may not be able to place it beneath the side-nav, since those pages don't have side-nav right now (see: https://github.com/18F/fec-cms/issues/1036).

This idea, as mentioned above, would mean removing `Submit a question to RAD` from the main navigation, and it would mean adding a link to the contact page, perhaps like this (thanks Emileigh for the screenshot):
![image](https://cloud.githubusercontent.com/assets/1450173/25676113/7db2478c-3006-11e7-8054-a2f9f7cce6a7.png)

---

**Comment by PaulClark2** [comment]
User need/ our goals Option 3 includes removing "Submit a question to RAD" from the main navigation fly-out, correct? If that's true, I agree user need/our goals Option 3 with design Option 2.

**Comment by AmyKort** [comment]
I agree with @PaulClark2 . Looks good to me and seems like a pretty elegant solution to reaching our diverse user base. 

Let's give @llienfec a chance to weigh in as well before we commit to this. She might have different/better information to shed light on this issue.

Thanks!

**Comment by llienfec** [comment]
Hey all! I agree. Let's try option 3, design 2. I'd be really interested in testing this, especially because the question form would be more buried than we had planned. Want to make sure users can easily reach out to us.

**Comment by jenniferthibault** [comment]
Nice work @emileighoutlaw & @nickykrause !

Looking at the designs, there's only one small hiccup with the placement on the landing page, but we talked about this in design pairing today, and have a solution! This comment is for polishing these designs up and summarizing to-do's for implementation.

**Problem:** Putting any links or content under sticky navs is problematic for short screens because they could get pushed below the page fold and wouldn't be accessible.
<img width="154" alt="screen shot 2017-05-03 at 6 37 08 pm" src="https://cloud.githubusercontent.com/assets/11636908/25761176/fc24b166-31a7-11e7-9a80-237f15c22ff4.png">

**Solution:** The fix for this would be to keep the card placement (but adjust the text). I think it makes sense to do this on both the [landing page](https://beta.fec.gov/help-candidates-and-committees/) and the [main page for each of the buckets](https://beta.fec.gov/help-candidates-and-committees/registering-candidate/)

`Including callouts deeper down in the content, rather than just on the landing page` (from above)
One way to do this is to place the item as a consistent side-bar module that would always be the last item in the list. This keeps it grouped with where people are already looking for a next step:

![screen shot 2017-05-05 at 3 42 38 pm](https://cloud.githubusercontent.com/assets/11636908/25761755/f16be71a-31a9-11e7-962e-0fbdc91c864f.png)

_______________________

## Summary & implementation steps
- [ ] Remove link from mega menu
- [ ] Adjust text in landing page card to say `Get help from the FEC by  phone or email`
- [ ] Add cards to main content page with the same  text ^ linking to contact page
- [ ] Add contact module to CMS "Custom page" template sidebar with the same text^. Should be applied by default with the option to opt out of displaying it

**Comment by jenniferthibault** [comment]
Plus one more to-do:

- [ ] Content strategy for Contact page adjustments to direct the right folks to the RAD analyst lookup & contact form: @emileighoutlaw ?
![screen shot 2017-05-05 at 11 20 43 pm](https://cloud.githubusercontent.com/assets/11636908/25769526/bcb40bf2-31e9-11e7-8a4b-f08e58c402b5.png)

**Comment by emileighoutlaw** [comment]
### Right now:
Because all folks can do right now is look up their analyst, it feels weird to tout a new form that isn't actually up and running. Also, the lookup isn't a new feature. So I might start right now by highlighting the look-up tool:

> **Reports Analysis Division** 

> Including help with report creation, transactions and amendments

> [Look up your committee's analyst]()

> 1-800-555-5555

> 202-555-5555


### In the near term:
Once the form is up and running, we can add in a line about the form to submit a question:

> **Reports Analysis Division** 

> Including help with report creation, transactions and amendments

> New! [Submit a reporting question to RAD]()

> [Look up your committee's analyst]()

> 1-800-555-5555

> 202-555-5555

I added the "submit a reporting question" _in addition to_ the lookup tool, because even though they're housed on the same page, they're different tasks and they felt weird combined on one line— a person might want to do one but not the other; I just didn't feel good tying them together as a single piece of content.

**Comment by noahmanger** [comment]
I made a new issue so it's easier to track the tasks for implementation: https://github.com/18F/fec-cms/issues/1046

Closing this one.
