### ISSUE TITLE
Design solution for form disclaimer

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1039]
@AmyKort noted that when clicking links from the [Forms](https://beta.fec.gov/help-candidates-and-committees/forms/) index, there is no disclaimer, as there is on the old site.

On the [old site](http://www.fec.gov/info/forms.shtml#), here's what it looks like:
![image](https://cloud.githubusercontent.com/assets/1696495/25728315/05fec476-30e3-11e7-9379-cb06b9a8dcc0.png)

This likely does not need to be a popup exactly like this, and is not a pre-flip must, but is a thing we should address in the future.

---

Update from grooming:
- We are not changing the language at all
- We should look at what kind of interaction we want

**Comment by emileighoutlaw** [comment]
Future content on this project: This content was intentionally written to be scary, because lots of people file forms for funsies, and that causes a great waste of resources. So that's why it is the way it is currently. Amy Kort can talk more about this with you.

**Comment by llienfec** [comment]
Quick update - linking directly to webforms with no disclaimer was deemed too risky.  Changed the webform links on the forms page to go to the webforms main page instead of directly to the webform.  This forces the legal language to show up.  

It looks like a different set of contractors were asked to fix this problem somehow, and it should be done in a few days.

**Comment by noahmanger** [comment]
This is no longer relevant.
