### ISSUE TITLE
Usability test the site search

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1043]

**Comment by nickykrause** [comment]
Only two users signed up last week, but both of them showed up. [We have some issues logged from those tests](https://github.com/18F/fec-testing/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20created%3A%3E%3D2017-05-15%20label%3Asearch), but we also have some open questions due to the low turnout. 

I have two users recruited for this week, so I'd like to test the same script again and gather some more data before moving this to "Done."

**Comment by nickykrause** [comment]
Tested again last week and found answers to several questions. Moving this to "Done" 

Issues logged [here](https://github.com/18F/fec-testing/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3ASearch%20created%3A%3E%3D2017-05-15%20%20created%3A%3C%3D2017-05-22%20)

**Comment by noahmanger** [comment]
Excellent. Closing.
