### ISSUE TITLE
Design GovDelivery signup interaction

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1044]
So that users can sign up to be notified of changes on the website, design an interaction flow for signing up for GovDelivery alerts.

---

**Completion criteria:**
- [x] Design entry point into subscription flow -- where do people sign up? 
- [x] Design subscription list structure
- [x] Consider overall strategy

**Comment by johnnyporkchops** [comment]
Link to Google Spreadsheet mapping old pages to new:https://docs.google.com/spreadsheets/d/11YgMMimDLFrLB16qSqdq2G9Qyjw4h8hOMbDapCTM4VE/edit#gid=267166490

**Comment by jameshupp** [comment]
@johnnyporkchops thank you for this

**Comment by jenniferthibault** [comment]
@jameshupp laid out an excellent dependency map for this epic in https://github.com/18F/fec-transition/issues/97— the relevant piece this issue is as follows:

This issue can get started with some preliminary work on 18F/fec-cms#1121, but the latter needs to be completed before we can validate the work in this issue.

When design in this issue is finished, we can make sure that it works on the right pages ( #1121 ) for the right set of lists ( #1090 ), it can be implemented in Wagtail.

I'm going to try to get started on this issue with what's been done so far in #1121

**Comment by jenniferthibault** [comment]
As I dove in, it became clear that there are two possible parts to the experience of this designed interaction:

**1. Designing how the signup widget works, and where people find it**
- What pages it's going on
- Where on those pages
- What it looks like
- How you interact with it

This is the area I'm starting to dive deeply into.

**2. Designing the interaction and flow of signing up, editing/setting subscription preferences, and unsubscribing**
- 🗺 The flow is handled by the GovDelivery interface, and controlled by whoever has the admin privileges on that account. There are large simplifications and improvements what we could make to the experience (having given it a test run with my own subscriptions). I know that @jameshupp has also been thinking about this a lot, and I expect we'll have recommendations in this thread...so I'll lay off this area for now and will add when he begins that.

- 🎨 There are also visual styling and template improvements that could be made to these pages to more closely match the new site. I expect to dive more deeply into this once we have distilled the user flow.

_________

**What pages can you subscribe from?**
- You should be able to subscribe to a specific mailing list through any page that has content on that topic that's sent through a newsletter: this includes the actual article page (_ex: any press release_) as well as the page that aggregates the publications (_ex: Latest updates_)
- You should be able to sign up for any of the FEC's mailing lists through a consistently-placed link, such as in the header or footer (I'd recommend the footer in our case)
Once we've narrowed down the overlap in lists ( https://github.com/18F/fec-cms/issues/1121 ), we'll be able to make a concrete list of what these pages and templates are.

**Subscription interaction and styling**
GovDelivery has [several options](https://insights.govdelivery.com/Communications/CommunicationsCloud/Subscribers/Growing_Your_Audience/Harnessing_Existing_Traffic/02Using_Subscribe_Field_Snippets?mt-learningpath=signupexperience) for how to build the subscription interaction through their snippet tools, but little guidance on best practices. The FEC was previously using an **embedded form** which still feels like a good approach for us, since it starts the process right within the site and saves a click. The other approach we might consider using is a **link or button** to the signup page, for when the space or layout doesn't allow us to embed the signup form. 

I'm going to follow up later this evening with how we could preliminarily style these, I just want to get this thinking to where others can see it first. 🌤

**Comment by jenniferthibault** [comment]
Here's my thinking on basic components for the embedded subscription module and link module.

The embedded subscription module could have these elements, but the design will likely change depending on where we decide to embed it:
![screen shot 2017-08-08 at 8 24 17 pm](https://user-images.githubusercontent.com/11636908/29100283-a52f7122-7c78-11e7-84db-1ed283497948.png)

The call-to-action style button that we use to link from individual article pages could look like this:
(maybe/hopefully with less text?)
![screen shot 2017-08-08 at 8 32 17 pm](https://user-images.githubusercontent.com/11636908/29100309-c3276a5e-7c78-11e7-8661-b150a7d969bc.png)


I think the permanent  "long-form" home could be at the bottom of the Contact page. This would need an anchor link so that we could jump people directly to it:

![screen shot 2017-08-08 at 8 23 42 pm](https://user-images.githubusercontent.com/11636908/29100153-eaadee8c-7c77-11e7-8bf4-9098ac611178.png)

The consistent link to this could be in the footer:
![screen shot 2017-08-08 at 8 30 41 pm](https://user-images.githubusercontent.com/11636908/29100259-6e1de5ce-7c78-11e7-9df9-dec14aed8175.png)




These are pretty broad strokes that I expect to change a bit when we know more about the specific mailing lists and pages, but any initial thoughts are welcome! All content and words are my first general pass, so they'd of course benefit from the wiser minds on the team.

**Comment by jameshupp** [comment]
The [previous work](#issuecomment-321119299) looks great, but it only factors in pre-signup activity, since it's based on the existing signup pattern from classic.fec.gov. In that pattern, someone enters an email address and then leaves the FEC domain to select which lists they want to sign up for on the GovDelivery domain. Ideally, we would take advantage of GovDelivery's API to build a signup form that does the following, all within the page where the signup form lives:

- before submission, displays an email signup form
- upon submission:
  - accepts submission of an email address
  - subscribes the user to a topic specified (by a Wagtail administrator) for the page the user is on
- upon success:
  - displays a subscription message back to the user without leaving the page
  - displays a link to the user's subscription management page where they can subscribe to additional topics (the page linked to is on GovDelivery's domain, so we don't need to design it for this issue)
- upon failed submission:
  - displays a message to the user explaining that the subscription failed
  - displays a link to try again that returns the original signup form

There's a small matrix of patterns we need to design for here:

1. Pre-signup, content pages
1. Post-signup success, content pages
1. Post-signup failure, content pages
1. Pre-signup, data pages
1. Post-signup success, data pages
1. Post-signup failure, data pages

This could end up being just three patterns, rather than six, and the post-signup success and failure could look really similar. Just depends on what the pages and ideal confirmation patterns actually are. In pursuit of that, I'm going to catalog all the page templates we recommend creating signups for, based on the actual pages and GovDelivery topics we've identified. This should give @jenniferthibault a way to validate that the patterns work where they need to.

The next steps for me will be to make sure all the pages IDed for each individual topic are set, so we can nail down the messaging in those patterns.

**Comment by jameshupp** [comment]
In addition to all that: the consistent link in the footer looks great. I think it makes a lot of sense to give people a way to signup from any page, even one that doesn't have a targeted topic. It'd be less ideal to forefront that, since it's kind of an unwieldy experience, but we shouldn't prevent people from doing so.

One thing I'd consider is changing the text to something like `Get email updates from the FEC`. I know that's a little longer than the current text. @jenniferthibault is the button at maximum capacity already? I hate "make it bigger" as a want, but "newsletters" has a narrower meaning to me than "email updates", sort of advertising-y rather than tailored to important new information in smaller doses like they actually get. And since we'll ask them to self-select, we ought to start them off thinking broadly about what they're selecting from.

**Comment by jenniferthibault** [comment]
Thanks for the great setup here @jameshupp. 

James also helped pull together a list of the types of pages and templates we'll need to add subscription capabilities to:

- Legal topic intro pages (we don't really have a name for this template, and it's not in the CMS)
  - https://www.fec.gov/data/legal/advisory-opinions/
  - https://www.fec.gov/data/legal/statutes/
- Resource page templates
  - https://www.fec.gov/legal-resources/court-cases/
  - https://www.fec.gov/legal-resources/enforcement/alternative-dispute-resolution/
  - https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/
- Custom page templates
  - https://www.fec.gov/help-candidates-and-committees/filing-reports/fecfile-software/
- Latest updates feed
  - https://www.fec.gov/updates/
- Each type of article published under latest updates
  - Press release page template
  - Record page template
  - Digest page template
  - Tips page template
- Advanced data tabs (we also don't have a name for this template)
 - https://www.fec.gov/data/advanced/?tab=candidates

The tricky thing is that with the exception of the pages under latest updates, not every page that uses the templates above will need the subscription module, but some of them will. So the module needs to be opt-in for all of those.

## First concepts 
### For everything except the latest updates feed page:
Since those templates are quite varied, I'm thinking that we might offer users a consistent place to look for the sign up if there is one—the very last item above the full-page-width footer elements. If we made the component a slab that was the width of the container, we'd have enough space in each case to embed the signup interaction

![screen shot 2017-08-11 at 4 30 31 pm](https://user-images.githubusercontent.com/11636908/29230773-6be89830-7eb2-11e7-92cc-1bf0bdcf2d2e.png)

### For the latest updates feed page
Since this page has quite a long feed and we'd be giving the choice to subscribe to multiple lists at once, it makes sense to place it more prominently, perhaps within the top accordions?

![screen shot 2017-08-11 at 4 41 32 pm](https://user-images.githubusercontent.com/11636908/29231119-f8d9e14e-7eb3-11e7-94ba-c11fa6b1359c.png)

## Open questions

It is possible that some of these pages are so long that people might not see the sign up field—it's an open question as to whether that's actually problematic. If it becomes so, we could investigate other ways of incorporating the modules, or ways to signal that there's a sign up option available higher up the page. We're considering this the first step, and suspect we'll learn more when we have something to test out.
______________________________________________

And yup, the footer button could get bigger, but only just: 

![screen shot 2017-08-11 at 4 05 26 pm](https://user-images.githubusercontent.com/11636908/29229964-eb19b85e-7eae-11e7-88b5-0b28095f31e9.png)

## Next steps:
For next sprint, I think we need to bring in some front end help and speak with GovDelivery folks about using their API to pursue this approach. I think this issue is "done" (pending feedback), but hesitate to close it before we've started implementation issues, which we'd need front end understanding of the API for .

**Comment by jenniferthibault** [comment]
Created #1194 to start implementation
