### ISSUE TITLE
Changes to Open Meeting Agendas

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1063]
1.	Can we take the “For  . . .” out of the filter? It isn’t parallel with the Commission Meeting information and saying that the Open Meetings are for the public, as opposed to journalists and committees as listed above, doesn’t make any sense. Any of these resources might be of interest to any member of the public irrespective of that person’s occupation.
2.	It is odd to have a link to the full meeting video for meetings that were cancelled
3.	https://fec-prod-proxy.app.cloud.gov/updates/august-16-2016-open-meeting/ On all of these, it’s a little jarring (maybe) to have video options top and bottom. On this one in particular, the video options present oddly at the top of the page.
4.	https://fec-prod-proxy.app.cloud.gov/updates/february-1-2017-public-hearing-open-meeting/ Is there any way to identify which hearing this was without opening the Sunshine Notices? We also need to say it was postponed.
5.	We are going to manually add the Executive Session notices, right? Is there a way we can send folks to the old site so they can see the rest? 
6.	https://fec-prod-proxy.app.cloud.gov/updates/march-9-2017-open-meeting/ Management and Administration Section displays oddly
7.	https://fec-prod-proxy.app.cloud.gov/updates/april-15-2004-public-hearing-open-meeting/ and https://fec-prod-proxy.app.cloud.gov/updates/april-14-2004-public-hearing-open-meeting/ This is really confusing. There’s a transcript labeled meeting minutes and no information on the actual page.
8.	Is it odd to have view full recording at the bottom of a page, like a 2002 meeting page, that pre-dates recordings?
9.	https://fec-prod-proxy.app.cloud.gov/updates/october-18-2012-open-meeting/ Just another example of where we’re not able to pick up the spaces between words

**Comment by noahmanger** [comment]
Good stuff. Most of these are about to be fixed by https://github.com/18F/fec-cms/pull/1060.

1. I don't have a strong sense one way or the other, but I know that the reason we added that "For..." language in the first place was because we were concerned with the fact that the content for filers and content for the press was for very different audiences and we wanted to make that explicit. 

2. This will be fixed. 

3. This will be fixed (same issue as 2). Imported meetings will no longer show any video links at the bottom, just the old-school ones at the top.

4. The meeting will now display the sunshine notices on the page. There's no further content [available on fec.gov](http://www.fec.gov/agenda/agendas.shtml) to show though.

5. Doing so would require adding an archive to the transition site, which I don't think we were planning to do. cc @patphongs 

6. This is a weird issue where there's some bad data in the page. I removed it.

7. On [the old site](http://www.fec.gov/agenda/2004/agendas2004.shtml) there's no content to display, and the transcripts are in the column where approved minutes are. There's about to be a change to the transcript field, but after that, we can move it so that they're not labeled as minutes.

8. Same as 2 and 3 -- this will be fixed. 

9. Noted.

**Comment by AmyKort** [comment]
Thanks! On issue number 1:  I think the logic of splitting these resources up by user group made more sense when we had fewer types of resources available. Also, we've heard from internal users that splitting the resources by user type is sending folks in wrong directions. So, now I'm wondering whether our initial assumption was mistaken when we thought content broke down that cleanly between  media representatives and filers. Maybe this is an issue for usability testing. cc @jameshupp

**Comment by jameshupp** [comment]
A couple thoughts on "For"...

- Is there a reason the filter is in reverse order from how it's presented in the "About latest updates" introductory text above? If the filter is just alphabetized and we want to keep it that way, we might want to do the same in the intro text.

- If we're not going to include these breakdowns in the filters, we might need the "About" heading to be a little more descriptive. The info under that heading will be even more important for people who aren't sure which publication type they need.

- That's to say nothing of whether we should keep it at all. I'm happy to queue it up for testing as long as that's not going to disrupt existing progress toward launch or other priorities. Still finding my bearings, don't want to make too many promises about the state of things.

**Comment by noahmanger** [comment]
I'm fine to remove the groupings, but agree with James that we'll need to rework the text for consistency.

**Comment by AmyKort** [comment]
Okay. Let's figure out what we need to say in the "About" heading and then we can remove the groupings at the same time we implement that change? None of this is a pre-flip issue (unless someone has a flash of About text genius). Thanks!

**Comment by johnnyporkchops** [comment]
Regarding number #9:  From above: https://fec-prod-proxy.app.cloud.gov/updates/october-18-2012-open-meeting/ Just another example of where we’re not able to pick up the spaces between words. 
I have corrected the page mentioned here and and can manually look for and correct similar issues in meeting pages

**Comment by AmyKort** [comment]
thank you @johnnyporkchops ! Would it help if I sent spacing issue pages where I find them?

**Comment by johnnyporkchops** [comment]
@amy , do you feel that your list of pages wi/spacing issues would be comprehensive, or is that just what you cam across?

**Comment by AmyKort** [comment]
Just what I came across.

**Comment by johnnyporkchops** [comment]
Yes, it will help for you to send the ones you have found, or come across in the future.

**Comment by noahmanger** [comment]
These are all resolved now.
