### ISSUE TITLE
Updates folder in Wagtail needs more organization for internal users

### ISSUE THREAD

**Issue by dorothyyeager** [18F/fec-cms#1083]
Updates folder in Wagtail currently houses the Record news articles (Info Div/me); Tips (Info Div); press releases (Press), weekly digests (Press) and Commission meeting pages (combo of @johnnyporkchops, @patphongs, the Commission Secretary and staff director, I believe). There's a ton of content in it, and growing. So it can be really hard to find a page you are working on, especially when trying to find an older page to go back and make an edit or fix a link on. 

It would be really helpful if the updates folder could be divided into subcategories, either by division or by page type. That way Press wouldn't have to comb through all of Info's files to find their pages and vice versa.

**Comment by noahmanger** [comment]
Thanks Dorothy. This totally makes sense and I'm all for it. The one thing we'd need to figure out is the URLs. Right now everything is `/updates/[page-slug]`. But if we nest them, the default would be like `/updates/press-releases/[page-slug]`. Which might be fine, except there won't be a `/updates/press-releases/` page and all the old links will break. I think we could solve this with smart redirects, but it's a thing we'd need to figure out.

@patphongs do you have any ideas?

**Comment by dorothyyeager** [comment]
Thanks Noah. Definitely some issues to consider and I'm sure the Press Office would want to weigh in too. Something for future consideration.

**Comment by noahmanger** [comment]
This issue is redundant with other ones, so I'm closing.

**Comment by jenniferthibault** [comment]
I was looking for how this resolved, so reconnecting the work that addressed this issue here. (I couldn't find the redundant issues noted above, good reminder to us to always add link references!)

Looks like the first approach was to create a page model called a `Folder`but that was problematic for Updates pages because it was going to change the URLs and need redirects. That work is in https://github.com/18F/fec-cms/pull/1172

It looks like there was a revised approach in https://github.com/18F/fec-cms/pull/1200 that adjusts only the admin panel to show links to pre-sorted specific types of updates—it doesn't actually restructure any of the content.

**Comment by dorothyyeager** [comment]
Hi @jenniferthibault. Yes, this issue was resolved with #1200  and also with #1149
