### ISSUE TITLE
Re-assess latest updates

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1101]
Now that the home page has been up for several months (on beta and now production), we want to re-assess how well it's meeting the original goals and see if anything has changed from our original understanding of how businesses processes worked regarding the page.

This gives us the opportunity to look at several interrelated questions, including how latest updates and calendar events are shown, how links to frequently sought sections are surfaced, and more.

This is an open-ended task that should begin with looking at the original principles and goals we wrote and could expand into exploratory design work.

Anything to add @jenniferthibault ?

**Comment by jenniferthibault** [comment]
Getting up to speed on the current status, I've broken the research down into two areas:
- Issues reported
- Auditing original goals and measuring success against them

## Issues reported:
#### Calendar issues
- [Calendar should link to today instead of first day of current month #444](https://github.com/18F/fec-cms/issues/444)
- Hard to find past commission meetings (past years especially) in the calendar
 
#### Meeting issues
- [Can't find recordings of hearings #4206](https://github.com/18F/FEC/issues/4206)
- [Trouble finding past open meetings #4229](https://github.com/18F/FEC/issues/4229)
- [Difficulty finding meeting agendas #4172 (closed)](https://github.com/18F/FEC/issues/4172)
- [Easier path to commission meeting pages #2079](https://github.com/18F/openFEC-web-app/issues/2079)
- Where do meeting pages live?
- Via calendar: hard to find a commission meeting from the past
- People expect list they can easily scan by date, similar to old site
 
#### Home page issues
- [Unclear about difference between "What's happening" and "Upcoming events" #4198](https://github.com/18F/FEC/issues/4198)
    > “I find the difference between the "What's happening" and Upcoming events" sections to be unclear. Both contain future items– sometimes the same item– blurring the difference.”
- [Request: more content above the fold on the home page #4095](https://github.com/18F/FEC/issues/4095)
- [Can't find individual contributors data #4224 (most common issue)](https://github.com/18F/FEC/issues/4224)
- Make it easier to post a temporary update on the home page (with expiration, links)
 
#### Latest updates issues
- [User would like "Latest updates" to be more prominent #4083](https://github.com/18F/FEC/issues/4083)
    > “Please make "latest updates" a drop down tab at the top of the homepage. It links to a lot of info and is not easy for general public to find.”
- [Consider classification scheme and menu microcopy for Latest Updates filters #2047](https://github.com/18F/openFEC-web-app/issues/2047)
- [Confusion around meeting pages being published from the future in latest updates #1094](https://github.com/18F/fec-cms/issues/1094)

________________
Will follow up with goals assessment

**Comment by jenniferthibault** [comment]
Carried home page assessment issues into [Identify and prioritize homepage objectives #2157](https://github.com/18F/openFEC-web-app/issues/2157) 
and meeting issues into [Improve findability of meeting agendas and information #2158](https://github.com/18F/openFEC-web-app/issues/2158).

I think this issue should focus exclusively on latest updates, so that it's not tangled in with changing the other pieces and easier to complete alone. I'm also moving it into the backlog because I think there's more we need to learn before it's ready to go.

**Comment by jenniferthibault** [comment]
We're addressing the home page events/publications feed confusion in #2159.

Since most of the current issues reported in Latest updates revolve around meetings, (being separated from the page and designed in #2158), there's still nothing uniquely actionable for this issue. Staying in the backlog for now, but we may be able to close.
