### ISSUE TITLE
Work on reporting examples using current templates and updated content strategy

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1104]
Before we redesign any templates, we agreed that @jenniferthibault and @jameshupp would work with the content manager group to see if we could figure out how to show the reporting examples content using a the current templates. This might require slight adjustments to the content strategy. 

If necessary, we can design new templates or components, but let's see what we can get done with what we have.

If possible, we'll try to get everything to a publishable state.

**Comment by jenniferthibault** [comment]
[Issue 582, _Implement "example" blocks for CustomPage_](https://github.com/18F/fec-cms/issues/852) documents what we knew we'd need at that point, and what has been built into the Custom Page template (with images! 🖼 ). That gives us a sense of what we have in place now and could make use of immediately. A quick scan makes it seem like we are making use of all modules except of the example form module.

Example forms:
![image](https://cloud.githubusercontent.com/assets/1696495/24067065/42dec69e-0b35-11e7-8992-4df4d9cb4e7f.png)

**Next steps:** 
@jameshupp and I are hoping to set up a time to chat with @llienfec so that we can start to understand if we can make use of the example forms module as is to meet some needs, if changes are needed, and if there are other needs we haven't accounted for.

**Comment by jenniferthibault** [comment]
@jameshupp captured the process and workflow in this wonderful [slide deck](https://docs.google.com/a/gsa.gov/presentation/d/1_NRWxJ7mSFsSXuWpWLGTwvQc8eEuFbqfJEuE3cL_ExE/edit?usp=sharing) 🔒 

At a high level, we've generated the following content model, and tested it with two pages' worth of reporting guidance:
<img width="471" alt="screen shot 2017-06-26 at 4 36 25 pm" src="https://user-images.githubusercontent.com/11636908/27559202-ac8d14e0-5a8d-11e7-9bb5-aa972d540ac3.png">
 
🎨  Simple example: [Day-to-day operating expenditures](https://gsa.invisionapp.com/share/6ZCBWU89B#/240371481_Day_To_Day_Expenditures)
🎨 More complex example: [Personal loans from the candidate](https://gsa.invisionapp.com/share/6ZCBWU89B#/240372369_Personal_Loans_-2-)

## Next steps:

**18F revises and cleans up the model based on what we heard here**
 - Jen solidifies the visual design
 - James starts describing writing requirements for content types so the FEC can work with them directly

**Checking to see whether this really works**
- Lauren pulls together inputs for the other examples we talked about
- James arranges those new examples to see how they fit the model
- Jen and Noah figure out what would need to be created and whether it’s doable

**James and Lauren figure out what this will take within the FEC**

**Comment by jenniferthibault** [comment]
Listing other working resources so that they don't get lost:
📝 🔒 [Testing content model for reporting examples](https://docs.google.com/a/gsa.gov/document/d/1uVkziiTvBSOvYWoywPuOULnXZiLOvCDFkzqYN6UH9GA/edit?usp=sharing)
📝 🔒 [Reporting examples examples](https://docs.google.com/a/gsa.gov/document/d/19jvjYLDDh6BENxlxpGMRkOpyJfhK-2tdAr7Y7xTiE_k/edit?usp=sharing)

**Comment by jenniferthibault** [comment]
I've been working with the page layouts after last week's feedback, and it would be good to wait for the next 2-3 example pages before making a recommendation on final layout. Holding design for now.

**Comment by jenniferthibault** [comment]
@llienfec pulled together more examples for `Reporting receiving an in-kind contribution`, `Reporting employer/occupation information`, and `Federal Election Activity (FEA): allocating between federal and Levin funds` 

@jameshupp took a preliminary look to gut check that the content would fit the model and leave questions where it might not. 

We learned about one additional content/design need:
> **James**: _The one thing that did come up is there was a really good opportunity to cross-link to `How to report purpose of disbursement` within `How to report in-kind contributions`: in-kind contributions have to be reported as expenses, too, which means reporting a purpose of disbursement. I wasn’t 100% sure what the best way was to call attention to the fact that we also have guidance to that somewhat confusing term._

> **Lauren**: _I agree, it would be nice to somehow reference related reporting issues._

Looking at the page layouts, there is design conflict between the goal of using the page-width more effectively (and avoiding longer pages through visual design) and embedding related resources in the right-hand side bar position, which we've done elsewhere, since these two compete for space.

My suggestion for resolving this is to favor using space best, which means avoiding a right-hand resource bar, and instead directing readers to this content through in-context text links, for example:
> "To learn how to report in-kind contributions as expenses, read [How to report the purpose of disbursements](#)"

## Other design changes
- Moved example scenario cards higher in the "How to report" layouts, just following the introductory phrase or paragraph. This bumps them up in the hierarchy and lets readers know they're available resources sooner. There's slight concern that they might be interruptive to the content flow, but I believe that they are easily scanned over, especially if the intro is short.

![screen shot 2017-07-05 at 5 43 14 pm](https://user-images.githubusercontent.com/11636908/27886292-75cbda40-61a9-11e7-9255-4380c20013b1.png)


## Front end summary

I believe that this layout that takes advantage of full-width elements and lack of a resource sidebar is worth making a new wagtail template for (one that's used for How to report's and Example scenarios. Curious to hear if @noahmanger would agree when he's back, but I don't see that as a blocker for any continuing work at this point.

Beyond that, I made a cheat-sheet of new or adjusted components:
 
![reporting examples front end implications](https://user-images.githubusercontent.com/11636908/27886443-0547b0a4-61aa-11e7-9ad1-6561b8550499.png)

**Comment by jenniferthibault** [comment]
@jameshupp I just found this in "Done" but unclosed. Safe to close, as work has moved on right?
