### ISSUE TITLE
Implement home page changes

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1137]
So that users can better find news, meeting agendas, and other events, implement the new designs for the home page:

[Design issue](https://github.com/18F/openFEC-web-app/issues/2159)

We should start with implementing the top portion as designed:

![image](https://user-images.githubusercontent.com/1696495/28230515-302fae04-689c-11e7-9497-04383ef27916.png)

**Completion criteria:**
- [ ] New hero with new photo and call out box
- [ ] New optional red bar for messages . I think this probably makes sense to have configurable as a property of the home page itself, rather than the generic  update type, for ease of use.
- [ ] Rename "What's happening" to "News and announcements" and "Upcoming events" to "Events and deadlines"
- [ ] News section shows the most recent item of the four types of publications. If there's a featured item, the weekly digest drops out.
- [ ] Events includes the next meeting, deadline, outreach event, and legal deadline
- [ ] Create links to filtered views of the calendar / all meetings page

**Comment by xtine** [comment]
What are the calendar filters for meetings, deadlines, outreach, and legal?

**Comment by xtine** [comment]
@jenniferthibault and @jameshupp : what should it show if there is no upcoming date or deadline  in the "Events and deadlines" section? For example, currently there is no upcoming meeting in the calendar. For placeholder in the meantime I'm showing the text "None scheduled."

**Comment by jameshupp** [comment]
So I think "None scheduled" works great for the meetings and trainings. Is it significantly easier to do a single term for all buckets in that section, or is it pretty easy to do different ones? I ask because I don't think that term quite works for open comments. Technically, they schedule the comment deadline, but in practice it's a function of when the thing being commented on is first published. They don't have a free hand in it. And really, it's all the days _up to_ the deadline that matter, not just the one date.

This doesn't look like it's too long for that: `No requests or proposals currently open for comment.` I'm not _sure_ if "requests" (as in AO requests) or "proposals" (as in proposed rules) are the right terms of art from the FEC, but they seem to capture the things that feature open comment periods.

If we need them to be identical terms, can we go with `None upcoming.`? It's a little stiff for the things that actually do get scheduled, but it applies more comfortably to all three.

I'm assuming the filing deadlines are never empty.

**Comment by AmyKort** [comment]
Filing deadlines will never be empty. I'd be surprised to find that there's not a training scheduled, since those are often planned out a year in advance. I think "None scheduled" would work for any meetings and trainings and be more appropriate than "None upcoming" if we're going for a one-size-fits-all solution. While it's true that the comment periods are tied to our publication of a document, we do still schedule the comment deadline.

**Comment by dorothyyeager** [comment]
Like @AmyKort said, there's always a training scheduled too. The ones we've announced are posted on https://transition.fec.gov/info/outreach.shtml but there's always more in the works.

**Comment by xtine** [comment]
@dorothyyeager: should the existing "generic update" now just be used for banner announcements? or is there another way in wagtail you would like to add and manage banner announcements?

**Comment by dorothyyeager** [comment]
Hi @xtine - think this may be a question for the whole content team? There may be people with specific preferences about this. In terms of me and how easy it is for me to update the banner with announcements, the current "generic update" template works fine. One note - it is also used to alert people when RAD and efiling will be available for questions after hours on filing due dates.

**Comment by rhoughfec** [comment]
@xtine I think we talked about the banner update being used primarily for commission meeting notifications and filing deadline extended hours. Now of course I can't remember if we decided it was separate from generic updates. My guess is we will only have a couple things that will go in the banner for very specific periods of time.

**Comment by dorothyyeager** [comment]
I think the confusion may be that the Wagtail template used right now for meeting and deadline banners is currently called "generic updates"? Here's a screenshot of the meeting announcement (I've just been going in and updating it each time).
<img width="679" alt="screenshot-genericupdate" src="https://user-images.githubusercontent.com/24437369/28889603-847e858e-7792-11e7-835f-4bed630cd208.PNG">

**Comment by dorothyyeager** [comment]
And here's what the template looks like used for the filings due today, we're open late notice:
<img width="690" alt="latehoursscreencap-genericupdate" src="https://user-images.githubusercontent.com/24437369/28889835-540747c8-7793-11e7-8a03-4a63d1709449.PNG">

I will say this one was much harder to find in Wagtail and looking in our Slack discussion much harder to word since it needed to be < 140 characters.

**Comment by rhoughfec** [comment]
I may be confusing this but in design pairing didn't we talk about naming this something else so it wouldn't be confusing for content managers making the updates?

**Comment by dorothyyeager** [comment]
Wasn't in the design pairing. But having done these updates, the template's not confusing - but what might be confusing is finding the file to update in the updates folder, which goes to the issue at https://github.com/18F/fec-cms/issues/1149. Right now if we are just going to use one file for meeting announcements and one file for we're open late announcements - you have to search using the text you input. It might make sense in the Wagtail updates to have these separated into their own directory (I know it's not called that in Wagtail). Then it would be easy to find them. 

Also it needs to be decided if we want to hold on to these forever and create a new file for each time, or just re-edit the two entries each time it's needed (which is what we've been doing).
