### ISSUE TITLE
Implement new commission meetings index page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1138]
So that users can more easily find commission meetings, remove them from the "latest updates" feed and create a new page for "Commission meetings".

---

This is still being designed.

**Completion criteria:**
- [x] Implement the page as designed
- [ ] Move all meetings/hearings pages from Latest updates feed to meetings feed (https://www.fec.gov/updates/ --> https://www.fec.gov/meetings/)
- [x] Remove "commission meetings" from latest updates "publication type" dropdown
- [ ] Account for all redirect rules / link issues https://github.com/18F/fec-proxy/issues/59

**Comment by jenniferthibault** [comment]
🎨  [**Styled interactive prototype in InVision**](https://gsa.invisionapp.com/share/3ZCK4WRQM#/244102273_Latest-Updates_V1_Copy_6)
(the side nav is interactive)

**Design notes:**
- Each category should default to showing all years, with the ability to narrow down by year
- Should support searching by keyword (like current latest updates does)
- Question: @noahmanger do you think we should we add filter validation like in the data tables to show that results have changed/search term applied?
- Hearings should show the full title, since they have more variance, but open meetings adn executive summaries should be titled with just the date
- Ability to mark a meeting a cancelled

**Content need:**
- [ ] Intro copy to Hearings section (cc @jameshupp )

**Comment by jenniferthibault** [comment]
@johnnyporkchops just wanted to check in on this—i see it's in "Done" but the completion criteria aren't finished. Can you give an update?
