### ISSUE TITLE
Add "About" section to site navigation

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#1139]
So that users can more easily find meeting agendas and other news items, add the "About" section with links to meeting agendas and latest updates to the site navigation. 

---

@jenniferthibault can you update with designs and completion criteria once you have it?

**Comment by jenniferthibault** [comment]
### Designs:

![screen shot 2017-07-17 at 11 09 11 am](https://user-images.githubusercontent.com/11636908/28274943-6a137dbc-6ae0-11e7-800c-2b033013076f.png)

### Links:
- Get started: https://www.fec.gov/about/
- Mission and history: https://www.fec.gov/about/mission-and-history/
- Leadership and structure: https://www.fec.gov/about/leadership-and-structure/
- Reports about the FEC: https://www.fec.gov/about/reports-about-fec/
- Careers: https://www.fec.gov/about/careers/
- News and announcements: https://www.fec.gov/updates/ (url probably going to change?)
- Commission meetings: https://www.fec.gov/updates/?update_type=meetings
- Working with the FEC: .... Can we add an anchor link to the last section of the about page so it can be a direct link to that headline? https://www.fec.gov/about/

### Corresponding footer changes:
- Changes use of columns: uses columns 1, 4, 5, 6
- Removes `Latest updates` link from footer
- Reorders elements in About column to start with `About` & end with `Contact`
- Switches order of  Open Gov column and API column—this groups the two policy columns (4&5) together instead of splitting them up

![screen shot 2017-07-17 at 11 39 40 am](https://user-images.githubusercontent.com/11636908/28276422-e6abd8fc-6ae4-11e7-9d1c-2033cbc27f30.png)

_________________________________________________
### Completion criteria
- [ ] Update universal site nav
- [ ] Update universal site footer
- [ ] Update mobile menu
- [ ] Update mobile footer
- [ ] Update menu on eRegs (if it's still hard-coded & separate)
- [ ] Update footer on eRegs (if it's still hard-coded & separate)
- [ ] Update transition.fec menu
- [ ] Update transition.fec footer

**Comment by patphongs** [comment]
PRs are in to update the menu to include the new main About section as well as updating the footer. 

https://github.com/18F/fec-style/pull/748
https://github.com/18F/fec-cms/pull/1152
https://github.com/18F/openFEC-web-app/pull/2219
https://github.com/18F/fec-eregs/pull/360

Transition menu and footer will be updated after deployment and release of new menus to main site.

**Comment by noahmanger** [comment]
Resolved! Nice work @patphongs .
