### ISSUE TITLE
Pretty URLs for documents uploaded through Wagtail

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1140]
Make documents uploaded through Wagtail have pretty FEC.gov URLs instead of AWS S3 bucket URLs.

**Comment by patphongs** [comment]
Django documentation for django-storages stipulates that we can use `AWS_STORAGE_BUCKET_NAME` to specify a custom URL. But not sure if this is directly associated with the bucket name that is set in AWS (right now we can't set our own bucket name in cloud.gov). That's why we set routes for the bucket within the proxy. Would be good to investigate further on what this would do.

**Comment by johnnyporkchops** [comment]
So the documents  uploaded through wagtail and in the documents folder start out with a www.fec.gov/ url but are redirected to the S3 bucket. Documents in the /resources/updates/agendas/2017/ stay as pretty urls and do not redirect to an AWS URL.

**Comment by patphongs** [comment]
I'm hoping that if we specify the `AWS_STORAGE_BUCKET_NAME` in the base.py, it will remove the bucket name string `https://s3-us-gov-west-1.amazonaws.com/cg-47928592-406c-4536-8234-99b896e8d57d` and replace it with this `https://www.fec.gov/resources/`. 

For example, this URL 
https://s3-us-gov-west-1.amazonaws.com/cg-47928592-406c-4536-8234-99b896e8d57d/cms-content/documents/mtgdoc_17-29-a.pdf

would be transformed into 
https://www.fec.gov/resources/cms-content/documents/mtgdoc_17-29-a.pdf

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1143
