### ISSUE TITLE
RAD Analyst Form "No Results Found" Validation Needed

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1142]
Got this error when trying to submit search for RAD Analyst by committee when a committee is not assigned to an analyst. If there is no results, there should be some kind of user feedback or validation that there are no results.  

https://www.fec.gov/help-candidates-and-committees/question-rad/

`Uncaught TypeError: Cannot read property 'first_name' of undefined
    at AnalystLookup.showAnalyst (contact-form.js:91)
    at fire (contact-form.js:9887)
    at Object.fireWith [as resolveWith] (contact-form.js:10017)
    at done (contact-form.js:15842)
    at XMLHttpRequest.<anonymous> (contact-form.js:16084)`

Update:

No results message could help direct user to contact RAD according to contact page information phone number.

**Comment by llienfec** [comment]
I tried to replicate the error above and couldn't replicate the exact error.   I had trouble finding a new enough committee where 1) the committee ID exists and 2) it hasn't been assigned to an analyst yet.

In the case where the committee and the ID are registered, but the committee doesn't have an analyst assigned, then could we add the following language in the space where the analyst's information would show up? (Crude mock-up below - needs correct font/size/spacing.)

> Your committee does not have an assigned analyst yet.  Call our toll-free number or 202-694-1130 and our administrative staff will connect you to an analyst.

![image](https://user-images.githubusercontent.com/22914750/29376194-c3488cda-8285-11e7-9a5d-586709ec880d.png)


I think the interaction for a registered committee with no analyst (described above) should be different than the interaction for entering a committee name or ID that doesn't exist.  The current interaction is that nothing happens on the page, and I think it makes sense to keep it like that.  Unregistered committees and people not associated with committees should contact Info/Public Records instead of RAD.

**Comment by patphongs** [comment]
@llienfec How does this look?

![rad-analyst-validation](https://user-images.githubusercontent.com/12799132/29598240-acedb2ca-8795-11e7-89df-6b9e3e2f924f.gif)

**Comment by llienfec** [comment]
It looks so great @patphongs!

**Comment by patphongs** [comment]
Validation code has been created. Need to update tests for validation in this PR https://github.com/18F/fec-cms/pull/1210

Will do this in 3.5.

**Comment by patphongs** [comment]
Completed this in PR https://github.com/18F/fec-cms/pull/1269
