### ISSUE TITLE
Define style for examples of how to fill forms

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1147]
In the reporting examples from #1123 , there will be many example form snippets included to demonstrate how/where/what to put in the form fields.

Since this will be a common component, we should define a style so that it will match the new web styles, and be consistent across the site and across print materials.

**Current styles from print brochures**
![screen shot 2017-07-24 at 12 54 06 pm](https://user-images.githubusercontent.com/11636908/28534588-3490ba94-706f-11e7-85c4-d7e2d83423c0.png)

**Completion criteria**
- [ ] Define necessary design characteristics/constraints
- [ ] Draft design
- [ ] Review with Jim Jones & finalize styles

**Comment by jenniferthibault** [comment]
What seems to be working well from the existing style:
- Different font that makes the form instructions/labels look different from the entered text
- Image frame/border that contains the example

What could be improved?
- Sometimes hard to tell what specific fields or part of the form the example is referencing

**Suggested changes**

**Comment by jjones0618** [comment]
Awesome start. I love the reduction of visual elements. Open space is happy space! The introduction of yellow works perfectly for the web but could add some cost to the print versions which traditionally print in only two color (PMS TBD and black). That PMS, btw, would be one of your primary web colors (federal blue or crimson). I'd probably need to go 4P to match the yellow. More likely, I'd use a tint of the PMS to achieve the same goal. Not ideal but hopefully close enough.

What are your thoughts when multiple examples appear together vertically? Would one gray line extend for all or would each have its own? Presumably examples that should be viewed together would share a line, yes?

**Comment by jenniferthibault** [comment]
Interesting! Just curious, do you usually do offset or digital printing? 

We've kept the site color-coded by main section to be a subtle navigation clue, and the guidance for candidates and committees primary color has been the crimson. It might be easier to tint down to orange (also the section's accent color) than yellow, so I swapped those colors out. 

While thinking about this, it also reminded me that in order to better serve folks with color viewing deficiencies, we should make other visual indicators of focus instead of just changing the color. I made the text in the field we're highlighting bold instead of regular weight to add an additional way to perceive the attention.

Multiple examples could be treated a few ways, depending on the content:

- If they are showing multiple parts of the same example concept, I think they stay grouped in one phrase and share a line & title

![screen shot 2017-07-24 at 6 05 31 pm](https://user-images.githubusercontent.com/11636908/28546978-bbaf11a8-709a-11e7-9e6a-a17111fb6cc9.png)




- If there are two different examples back to back, then they could be separated and each have its own title and line

![screen shot 2017-07-24 at 6 01 34 pm](https://user-images.githubusercontent.com/11636908/28546871-36174344-709a-11e7-9004-11ed12ac1d19.png)


________________________
Bonus thought: I'm trying to keep the accent bright for web, and balance the constraints of printing with a consistent color, and making sure you have to make/export as few images as possible. If the printing costs are prohibitive for printing 4 color, you could do a % opacity on the crimson PMS color. This would meet your print process needs, but would mean exporting an image with orange for web, and 30% opacity PMS-crimson for print:

![screen shot 2017-07-24 at 6 05 02 pm](https://user-images.githubusercontent.com/11636908/28546959-a4d8e6e8-709a-11e7-9e76-ac3f6ba17a2f.png)

**Comment by jjones0618** [comment]
“do you usually do offset or digital printing”

That’s driven by cost. In the past, we’ve gone offset because the large quantity made digital cost-prohibitive. The next printing, however, will be far lower quantity so digital may be the better option. It would certainly solve this issue. I won’t know one way or the other until I get quotes and that won’t happen until the layout is finalized. I’ll bet, however, that it’ll end up going digital. With that in mind, I’d encourage you to go back to your original yellow if that’s what you think works best.

Your intent for the vertical gray line matches perfectly with how I’d want to use it! Well done, us!  :)

I really like these new fonts and how you’ve used them here. I spoke with the book’s author and she gave some pretty strong pushback against the highlights. She’s adamant that users won’t need them, stating that in 20+ years no one has ever expressed the need for them. While I understand her point, I disagreed in general. It’s true that some form examples may not lend themselves to highlights– on examples where every field was to be highlighted, it might be better to have no highlighting– but I think they improve readability and provide some desperately needed color to areas that would otherwise be uniformly b&w.

I’m going to build a sample page with your example concept and will send it to you for your comments.

**Comment by jenniferthibault** [comment]
That all makes sense!

Totally understand that the author may not want to add additional elements to the images, but on a webpage where there are several similar-looking images, it can be hard to tell what is changing in each (and easy to overlook a small box that must be checked). So I'd prefer to keep the highlights for now, but al always open to changing or removing if we find that they aren't adding to the experience, or are causing confusion.

For color: thanks for being flexible! And sounds like if print quantities are shifting, then the move to digital will indeed solve this issue. I think I'm going to stay with orange instead of yellow because it was a good push to stay with our paired accent colors.

Glad to check out the sample whenever it's ready. Thanks for working with me on this!

**Comment by AmyKort** [comment]
Awesome! Are we ready to close this issue?

**Comment by jenniferthibault** [comment]
If @jjones0618 is ok with it, then I think so. I can take a look at the sample template when it's ready, but I don't think it will block any ongoing or upcoming sprint activities, so feels like this can be closed.

**Comment by AmyKort** [comment]
Thanks so much!

**Comment by jjones0618** [comment]
Should we modify the images now or are we waiting for the results of @patphongs's user testing in Chicago?
