### ISSUE TITLE
Design how to access all reporting examples from a filing reports page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#1164]
So that users can find reporting examples for each type of group from the page that tells them about filing reports, design & style the placement and module

These modules would be placed on the following "filing [group type] reports" pages
- [Filing candidate reports](https://www.fec.gov/help-candidates-and-committees/filing-reports/)
- [Filing political party reports](https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/)
- [Filing SSF reports](https://www.fec.gov/help-candidates-and-committees/filing-ssf-reports/)
- [Filing PAC reports](https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/)

**Completion criteria**
- [x] Determine the maximum and minimum quantity of examples the design must accommodate
- [x] Design mockups , review with @llienfec & @jameshupp 
- [x] Create implementation issue for final design to be added to wagtail templates

Design questions to answer:
- what would such a list look like? should it just be a list or should it use some of the design elements from within the help pages that link to the examples? 
- can it just be in one of the basic existing templates or does it need something else?

**Comment by jenniferthibault** [comment]
Got some great direction from @jameshupp's [Managing Reporting Examples](https://docs.google.com/document/d/1Y4qshPcm6eelxqYY_FaxLVE6rLUeZUIsd0N2VlMxzBc/edit#) doc 🔒  and discussion with him.

Our first hypothesis is that these make sense as a collection together, and could be the 4th item on each `Filing [type of group] reports` page

![screen shot 2017-08-04 at 5 49 06 pm](https://user-images.githubusercontent.com/11636908/28988315-384bbd2e-793d-11e7-89de-7bf9be954d95.png)

We'd try this route instead of embedding them with the sections they're in since some examples don't yet have homes.

When I was looking through existing patterns to find a way to visually set these off from the other content sections, but accommodate a lot of links, the slab we're using for [legal citations on guidance pages](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cannot-contribute/) came to mind. 

In design pairing today, @llienfec and @rhoughfec called out that it feels like we need to give the title it a little more prominence, or else it states feeling too similar to a footnotes/citations panel (pattern blindness). We agreed that it's worth a variation to the existing pattern to make a more prominent header, which allowed us to work in the icon as well. We hope that this will create a visual link between here and where these occur as cards in the guidance pages. Here are two examples of differing lengths:

![screen shot 2017-08-04 at 5 43 42 pm](https://user-images.githubusercontent.com/11636908/28988826-cd6315e0-793f-11e7-8a8d-18adce9cab58.png)
![screen shot 2017-08-04 at 5 44 54 pm](https://user-images.githubusercontent.com/11636908/28988825-cd59e40c-793f-11e7-97dc-2d6dc2149d3c.png)


And a full-screen shot of the whole shebang:
![screen shot 2017-08-04 at 5 45 43 pm](https://user-images.githubusercontent.com/11636908/28988845-e3fa148e-793f-11e7-8175-1a6c3dc2bf8e.png)

___________________________

Any thoughts or reactions seeing these variations? @jameshupp @dorothyyeager @llienfec ?

After any feedback, the next steps would be to create an implementation issue to get the component into the resource page templates.

**Comment by dorothyyeager** [comment]
I think it's good and I like that we will have an easy link on the left to click to get to them. For the reporting examples section, I think it will be important to decide how to organize the links to the examples in the bullets. (Alphabetical, labeling etc.) I'd suggest taking out extra words in those links like "the" and "a" so that it works similar to an index.

**Comment by llienfec** [comment]
@dorothyyeager You're on point.  @jameshupp started thinking about the ordering within the subcategories for us.  Candidate receipts side will have a lot of examples (compared to other sections, and so ordering them will become really important.  I usually lean toward organizing by concept (which is also effectively by line number), but that's because it matches the lines on the report and how we teach in conferences/webinars.  But we can also make great arguments for most common to least common entries from what we see on reports.  Or simplest to most complex.  Or alphabetical.  

Since there are so many ways we could do it, @jameshupp we'll need your experience regarding which way to go initially and then maybe we can conduct testing to see if the initial way we go is working effectively?

**Comment by jenniferthibault** [comment]
I checked in with Noah, and we feel good about rolling this implementation into the existing issue for the reporting module front end CMS template work in https://github.com/18F/fec-cms/issues/1160

Closing and transferring
