### ISSUE TITLE
Revisit and refine calendar designs

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#117]
Relevant stories:
- [So that users can know when to report, users can view all reporting deadlines](https://18f.storiesonboard.com/m/fec/!card/IovpMAadH296NDnT3Laojg)
- [So that the public can follow the commission's decision-making activity, show dates for meetings, AOs, and other activities on a calendar.](https://18f.storiesonboard.com/m/fec/!card/5X1JTYVxlgg6XznT3Laojg)

Goal: Review the original designs for the calendar and make revisions and refinements in conversation with FEC.

**Comment by jenniferthibault** [comment]
@jmcarp pointed me to [FullCalendar](http://fullcalendar.io/) an open source calendar that has great, clean basic interactions. I've used this, combined with the template for the [data browse/filter pages](https://beta.fec.gov/data/candidates/?cycle=2012&cycle=2014&cycle=2016), as the foundation for this round of designs, so it will be helpful to poke around that site to get a feel for how it works. (Especially the day/week/month views, and how to see additional events from the month view toggle). If we want to stray from this interaction, better to know sooner than later! ( @noahmanger / @onezerojeremy / @emileighoutlaw )

For discussion about the interaction of the export/subscribe/copy events, check out https://github.com/18F/fec-cms/issues/126

___

### Default view 
Here are the stylized designs for the calendar with event filters in monthly view, which I think would be the default view:
![calendar_monthly](https://cloud.githubusercontent.com/assets/11636908/11618829/f3b3b124-9c6d-11e5-81ab-80c8dfffc27b.png)

In this iteration, I've chosen to incorporate a list of the events right under the calendar instead of as an alternate view, which would have needed an additional button. The top real estate is getting a bit cluttered already, and it would require less clicking (although makes a longer page, so more scrolling). I see this as a possible revision, pending feedback.

___

### Event page
An individual event's page could look like this: (uses the Essentials Article page as a loose base template)
![calendar_event](https://cloud.githubusercontent.com/assets/11636908/11618838/16ed1374-9c6e-11e5-8440-ff4a05b8cc58.png)
Looking through the existing FEC calendars, I tried to pick a few most common patterns and incorprate spaces for them (FEC Live logo, "intended audience" field, ability to register, and links to supporting documents)

___

### Quarterly view
A new and more complicated view would be quarterly. This one stumped me the most, so glad for suggestions at alternative layouts, but it seems like folks who want this view certainly would want to see what events fall on each day (repeating the monthly view):
![calendar_quarterly](https://cloud.githubusercontent.com/assets/11636908/11618864/658a13e2-9c6e-11e5-9a8d-2226351ea7a3.png)


I'm looking at this palette for event categories, which are all tested and WCAG2 compliant with white text:
<img width="446" alt="screen shot 2015-12-06 at 11 15 25 pm" src="https://cloud.githubusercontent.com/assets/11636908/11618927/5418a2bc-9c6f-11e5-8a53-a8c5ce4cf6b4.png">

___

Thoughts? Feedback? All welcome.

**Comment by onezerojeremy** [comment]
Looks clean and well thought out. Nice work!

couple quick thoughts/questions:

What happens when you click "today"?  What about the arrow buttons beside it? 

What happens when you click an item in the "Copy Events" dropdown? Part of me thinks it might help combat feature inflation by launching with the ability to subscribe to an entire calendar, as well as copy a specific event, but not implementing a copy all events. idk.

I really like having the events listing on the same page. I also really liked the old, more elaborative calendar listings that included a bit about what the events were; I think perhaps users might not get enough details just from the title. It could be we want to recommend moving to more elaborative event titling, or it might be that we want to surface something a bit more about what the event will be. Might make for a long-ish page, but it might be worth it, since the calendar view itself isn't likely to give you the context about what an individual event is, given space constraints.

**Comment by noahmanger** [comment]
This is looking so good!

A small smattering of feedback:
- If the export and subscribe buttons apply to whichever set of filters is currently applied, we may want to add a "Select all" / "Clear all" option (there's already a "clear filters" button on the other browse pages)
- Should the list view at the bottom have a section title? I think it might be good to clarify that these are all events coming up, not just those that are filtered
- I think the new checkboxes should still have checks inside them, but I like the color coding
- Does checking the parent checkbox check / uncheck all of the children? Probably would be good, but I think having the checkbox in the accordion button area might be tricky. What would it look like to have the "select all" option nested?
- If an accordion has selected elements but is collapsed, how does it look?
- Last thought: what if we switch the "subscribe" and "copy" buttons so that the bigger button with option is "subscribe" with a number of options, and then there's a secondary link next to it to export events?

**Comment by jenniferthibault** [comment]
### To Jeremy's questions:

**What happens when you click "today"? What about the arrow buttons beside it?**
- Today orients the calendar from wherever you've navigated to back to the day/week/month of today's current date. Depending on your view, the arrows move the calendar ahead or back in time by an increment equal to the view you're in. (If you're viewing months, it will move one month, if weeks, then one week.) [Play around with this FullCalendar demo for a feel of most of these types of interactions.](http://fullcalendar.io/js/fullcalendar-2.5.0/demos/basic-views.html)

**What happens when you click an item in the "Copy Events" dropdown?**
- I'm looking to @noahmanger & @jmcarp 's comments (which I think are still TBD) in this issue to work on that interaction.  https://github.com/18F/fec-cms/issues/126

**I really like having the events listing on the same page. I also really liked the old, more elaborative calendar listings that included a bit about what the events were; I think perhaps users might not get enough details just from the title.**
- I was intending the listed events to also link to an individual events page (meaning the user is required to click to that page to get the information you ask about.) If we want to frontload this info and surface it right on this page, I can shuffle that space around to incorporate it. *Do we want this?*

### To Noah's questions:
**If the export and subscribe buttons apply to whichever set of filters is currently applied, we may want to add a "Select all" / "Clear all" option (there's already a "clear filters" button on the other browse pages)**
- Yes! Let's use the same pattern from the browse pages

**Should the list view at the bottom have a section title? I think it might be good to clarify that these are all events coming up, not just those that are filtered**
- I was actually thinking that this list view would also be controlled by the filter. @LindsayYoung what's your sense of whether it should be "All events" there or "Filtered events" - as a list-view user? 

**I think the new checkboxes should still have checks inside them, but I like the color coding**
- ok

**Does checking the parent checkbox check / uncheck all of the children? Probably would be good, but I think having the checkbox in the accordion button area might be tricky. What would it look like to have the "select all" option nested?**
- Yes, I was thinking it selected/deselected all the children, but "All __xyz___ " could instead be moved to the first child position.

**If an accordion has selected elements but is collapsed, how does it look?**
- I was not thinking it would change visually. It could.

**What if we switch the "subscribe" and "copy" buttons so that the bigger button with option is "subscribe" with a number of options, and then there's a secondary link next to it to export events?**
- Does "export" also require options after you choose it?

**Comment by jenniferthibault** [comment]
Updated based on a really great pairing session with @noahmanger that almost made our brains explode. We can try answering straightforward questions here, but for more complex interaction questions, at this point it will be more productive to move to voice chat. There's a lot to look at here, and I think voice will be better than a stream of comments. 

#### Default view
- We strengthened the pattern between the [data browse filters](https://github.com/18F/openFEC-web-app/issues/754#issuecomment-163340251) and calendar filters here
- When you land on the calendar page, all the events will be shown (as all data is loaded on browse tables). The filters act as a way to cut the events down. 
- There will be a max number of filters viewable, then the rest will collapse, like in the pattern in the linked issue above
- The first child item in each event category will be `ALL DEADLINES` When you click this, it selects each item in that category, and checks each box. If you uncheck one of those boxes, the `ALL DEADLINES` box also unchecks, but the rest of the items stay selected. If you check, then uncheck the `ALL DEADLINES` box, you will select, then deselect each and every box below it in that category.

![calendar_monthly](https://cloud.githubusercontent.com/assets/11636908/11702296/9609dbd8-9ea3-11e5-85dd-2dfe1ad0d14c.png)

___
#### List view
- This brings out more information about each event, but still links to a full Event page for everything.
- Still organized by category
- Filters apply

![calendar_list](https://cloud.githubusercontent.com/assets/11636908/11702297/9a2a639a-9ea3-11e5-9a33-a29bb2be9d02.png)

___
#### Quarterly view
![calendar_quarterly](https://cloud.githubusercontent.com/assets/11636908/11702303/a21759f0-9ea3-11e5-9b35-cb563faa9459.png)

___
#### Event page
![calendar_event](https://cloud.githubusercontent.com/assets/11636908/11702311/ad0ba80c-9ea3-11e5-8ca5-8e5874b90f22.png)
___

For discussion about the interaction of the download/subscribe/add events, check out https://github.com/18F/fec-cms/issues/126

**Comment by onezerojeremy** [comment]
I love this. That is all.

**Comment by noahmanger** [comment]
Looking super sharp. One thing that came up in my sync up with Josh and Lindsay on the data questions, though, is that the state filter really only applies to deadlines and elections. It's almost a sub-filter in this regard. 

Is there a way that this should be visually designed or arranged to signify this?

**Comment by jmcarp** [comment]
About the event detail view: anybody know where the intended audience and attachments are supposed to come from? Also, are the FEC Connect content and link static, or are those also supposed to be populated from the database? Again, I'm not seeing that information in the cal_* tables.

**Comment by jenniferthibault** [comment]
These are elements that I found when looking at existing events on the calendar itself (often a few clicks deep) not from the calendar data tables. It appears that Education and Outreach may be doing things very differently than the rest of FEC, but that's just a non-technical hunch at the moment. There appear to be four types of FEC Connect events, with varying data categories. 

For example, [this webinar](http://www.fec.gov/calendar/calendar.shtml?&day=2&categoryId=-1&eventId=4434) links to an [HTML table](http://www.fec.gov/info/outreach.shtml#roundtables) that includes the intended audience and registration information. Somewhat confusingly, registration happens outside of the FEC.

What do you think? Does this imply that we need some CMS integration on this page, or that we need to build a new category in the cal_* tables ?

**Comment by jmcarp** [comment]
One way or another, all the information in the calendar and event detail views needs to get into the database. Last time we talked about this, the conclusion was that all event information should already exist in a database. If that's true, then we should be able to resolve by getting access to the table with attachments, registration info, etc. If not, then we may need to change the plan.

@LindsayYoung, want to look into this?

**Comment by LindsayYoung** [comment]
@jmcarp I just chatted with @noahmanger  and @jenniferthibault and I think that we don't want to add things to the calendar. 

The most requested feature is the ability to download things to personal calendars, so we will want to keep the simple structure and link to a cms page. The CMS will eventually need things like downloads video links, etc. anyways.

I would like to have a simple-ish widget that inherits date/time and basic description information from an event id. That way we still have one source of date/time info but could add longer, more customizable content too.  This would be a feature that we could add later.

The workflow would be to add the event to the calendar, create a custom content page if necessary, and then add the link to the custom content in the description after the page is created.
  
Before asking FEC if that workflow is reasonable, I wanted to see if you thought this would be do-able or if this might be more complicated than I am thinking. 

I am trying to keep this as simple as possible, it keeps getting more complicated.

**Comment by noahmanger** [comment]
One thing to add to Lindsay's note: we're looking to switch the designs to a model where _by default_ events do not have a separate detail page, but instead we'll have whatever basic description is in the database show up in some context-specific way in the calendar. 

But then for pages that do need supporting content, we can create separate CMS pages, somehow link to the event specifics provided by the API, but also provide space for additional custom content, as Lindsay described.

**Comment by jmcarp** [comment]
Is the idea that users would enter an event ID into the CMS, and that we'd fetch the event details from the API every time we render the page? One issue is that events won't appear in the API until about a day after they're entered, so either users would need to wait a day between creating database and CMS events, or we'd need to add logic to hide CMS events until data is available from the API.

**Comment by LindsayYoung** [comment]
The calendar eventually needs to be updated more than once a day eventually, right? I thought getting those to us in a timely manner was one of the things the FEC was going to work on since meeting times can change etc. 

I think that having the API integration brake gracefully is probably a good idea. I would want the process to be the least duplicative as possible. I am still open to ideas and suggestions.
