### ISSUE TITLE
Design a way to access Citizens content from Introduction to campaign finance and elections section of homepage

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1182]
We've created a section of content to address the needs of citizens looking to get involved in the federal election process by volunteering, making contributions, etc. This information in many ways supplements and builds upon the Citizens Guide video currently on our homepage. We'd like to create a way for users to access the content section from there as well as (or instead of) the video link.

- [x]  Design new layout of Introduction to campaign finance and elections

**Comment by jenniferthibault** [comment]
Hi @dorothyyeager , I'm starting to dive into this today, but need a little more info to get started.

Primarily:
- `We'd like to create a way for users to access the content section...` 
  - Is there a landing page that groups these, or are there multiple independent pages?
  - Are these pages ready (at least drafted in wagtail)  so that I could look at them and reverse engineer how to design the link?

Thanks!

**Comment by dorothyyeager** [comment]
Hi @jenniferthibault - Yes, we've got some pages in Wagtail ready and others that aren't quite ready or we're not sure we are going to use in that way. It may be easiest to send an email with the links and a fuller explanation (it's a little too much to Slack). My issue at #1155 might play a role in all this too, so I'll loop you in on this as well.

**Comment by jenniferthibault** [comment]
Thanks @dorothyyeager , and email (or list here) is totally fine, anything that lets me start to see what we're trying to point people toward.

**Comment by jenniferthibault** [comment]
Based on what Dorothy sent, we have a [landing page](https://fec-prod-proxy.app.cloud.gov/introduction-campaign-finance/) (under password) which will act as a collection for the info in this section, and several child pages.

The primary design change I wanted to introduce to the home page slab would be to drive people to that landing page, while keeping other "entryway" topics for beginners we were already using, like candidate/race comparisons and contribution limits. 

Secondarily, looking at the topics of some of the child pages, such as researching campaign finance data and learning to support federal candidates, there was clear overlap with the topics mentioned above. This allows us to give different user groups links to content targeted at them for these topics:

That all looks like this, using a combination of images (yay!) call to action buttons, and secondary links:

![screen shot 2017-08-23 at 12 14 49 pm](https://user-images.githubusercontent.com/11636908/29626804-fc97c758-87fd-11e7-9425-11b656a4eb72.png)

### Image thoughts
- **Left image, intro:** Themes were researching, learning, reading, and introductory content, to indicate some sort of beginner-level learning. I think we could pretty quickly recreate this image of someone reading an FEC publication (currently it's another govt image, but I'm using it as placeholder for the style and subject) 
- **Center image, historical data:** Themes were candidates, past election activity, observation. I know we typically shy away from showing specific candidates, but this scene of citizens observing a debate from an older election felt evocative and more of a snapshot of a particular period in time rather than supporting a specific party or candidate. 
- **Right image, contribution limits:** A bit on the nose, maybe, but themes were financial, giving, and variety of amounts. I'd like to recreate this image with a check or other paperwork in the envelope as well, and that should be easy to do.
 
____________________________________

### Next steps:
- Get feedback on layout changes, links
- Get feedback on image themes
- Create needed images

______________________________________

### Other issues
@dorothyyeager suggested that there may be redesign work needed on the landing page or individual child pages for this section, and that is probably right, but is outside the scope of this issue, especially with George out of office this week. If these pages aren't ready for launch in their current state, that should be tracked and assigned in another issue.

**Comment by jenniferthibault** [comment]
Spoke with Dorothy, and we realized it would make sense to design an option for an interim solution that just links to the page that's most ready: the [Understanding ways to support federal candidates page](https://fec-prod-proxy.app.cloud.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/) (password needed).

Keeping the same strategy as above so that when more pages are ready we can adjust, that could look like this:

![screen shot 2017-08-23 at 2 41 25 pm](https://user-images.githubusercontent.com/11636908/29632499-2cf7c7c8-8811-11e7-8bee-2c344e6dee75.png)


Since determining which pages are ready for release will need folks out this week, this will likely carry over to the next sprint, and until then the design work is on pause ⏸

**Comment by dorothyyeager** [comment]
Just to add, I am thinking long-term that one of those boxes above (the one on the right perhaps?) might eventually point to a new page we are creating under issue #1155 for non-FEC election-related information.

**Comment by jenniferthibault** [comment]
I ran this by @gsmaragdis who 👍 the general approach but suggested thinking further about specific copy and page titles for the `Understanding ways to support federal candidates` page. 

I carried that over into an implementation issue in https://github.com/18F/fec-cms/issues/1237 which should be groomed before sprint planning next Tuesday. Closing this issue, but we'll need it for adjusting the links when more of the Intro to campaign finance section is ready for publishing.
