### ISSUE TITLE
Design placement of user recruiter tool

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1190]
The recruiter tool will be used to recruit new users from our website. We need to be able to design a way to incorporate this tool onto our site. Ideally it would be persistent to allow users to sign up for user testing anywhere on the site. 
 
**Demo:** https://feedbackmvp-demo.app.cloud.gov/
**Code base:** https://github.com/GSA/recruiter

## Possible Ideas
Incorporate a way for users to get to the tool from our existing feedback box. 

![screen shot 2017-08-11 at 1 49 41 pm](https://user-images.githubusercontent.com/12799132/29225363-f8c4ed1a-7e9b-11e7-9674-f4ed24d5fba0.png)

**Comment by jenniferthibault** [comment]
I got a head start on this one because I also wanted to think about a few improvements to the existing form we've noticed would be helpful.

Changes that might:
- Help people better understand that the feedback is publicly posted
  - Using words like "post" instead of "send" feed
  - Use "Public" in the title
- Further discourage people from posting personally identifiable information
- Show people how to contact the FEC if they have a specific question they'd like a direct answer to
  - Added link to contact and messaging about a specific question

I also think it might be worth restyling the module in a lighter palette as a subtle indicator of friendliness when submitting info, so I changed that here as well.

We're going to want to watch the height of this module when we make any changes in implementation—if the window gets too tall it could possibly trigger a need for a different layout/interaction type.

<img width="420" alt="screen shot 2017-08-15 at 1 08 54 pm" src="https://user-images.githubusercontent.com/11636908/29326839-0fae4ab8-81bb-11e7-97d7-df09a381040c.png">

**Comment by onezerojeremy** [comment]
👋  Weighing in, hope that's ok! 

This looks flippin' fantastic to me! 

I like the language (a lot), palette, visual hierarchy. 

Were I still on the project (sigh) I'd run with this. 

Two questions :
1. with respect to the initial call to action that gets you to this page: right now, as I understand it, it's the as-is feedback tab. It's been around for a while, people might be a hair blind to it. Worth considering visual nudges. If the flow of recruits is low, it might also be worth considering an embiggened version that is a little more eye-catching / prominent (but not too). 
2. edge case: Might think about how to turn off the recruiting ask easily (aka without code changes?). might not be possible.


Oh, I might keep an eye on whether people immediately recognize it as an "or" decision, and if not, potentially add a bit more space (or otherwise demarcate) the two options.

**Comment by patphongs** [comment]
thank you @onezerojeremy for weighing in! @jenniferthibault I too love the new lightness that you brought to the design, definitely gives it a more friendly appearance! 

Here's a few comments about the design and possible implementation:

- Recruits have been low lately and with the current design, the user would have to actively click on the feedback drawer to notice the sign up. It would be really nice if a second round of implementation could call more attention to user sign-ups in a separate feature on the site.
- The current design of the tool is a pop-up that would prompt for a First name and email. But given that we are putting the sign-up within the feedback drawer, a pop-up is not ideal. We would need a landing page. Below is an example of what that landing page could look like. 

![screen shot 2017-08-16 at 11 56 06 am](https://user-images.githubusercontent.com/12799132/29373943-c01f1cb6-827d-11e7-98a7-daa6a6e96735.jpg)

**Comment by jenniferthibault** [comment]
@patphongs thanks for the great page mockup! Great MVP is to embed the interaction on a separate page to avoid creating a modal within the toggle window.

To bring in Jeremy's feedback, we could definitely make a few tweaks to the button on the page to subtly show that there's something new happening. Here's a slightly embiggened button, in our secondary call to action color combo:

I toyed with adding an icon, but it started to compete with the page a bit too much for now

<img width="1434" alt="screen shot 2017-08-21 at 10 06 22 am" src="https://user-images.githubusercontent.com/11636908/29523712-e18046aa-865b-11e7-8d40-f2e41db7afe4.png">

And how we might add slight separation to the form
<img width="415" alt="screen shot 2017-08-21 at 10 28 11 am" src="https://user-images.githubusercontent.com/11636908/29523746-fa71015e-865b-11e7-9386-87f9f4d332ac.png">

**Next steps**
This seems ready for implementation—we will want to make sure the language is consistent and precise on both mockups, which can happen either now or on implementation review. cc @jameshupp

**Comment by jameshupp** [comment]
@jenniferthibault Sorry, which two mockups? There are so many 😀  but I am not 100% certain which are current 😢 .

**Comment by jenniferthibault** [comment]
Oh sorry! The [landing page](https://github.com/18F/fec-cms/issues/1190#issuecomment-322826301) and the [feedback drawer](4 days ago)

**Comment by jenniferthibault** [comment]
Annnnd @jameshupp I commented on a browser tab that had your question before you edited it, sorry! I'm pasting it into [this 🔏 Google doc](https://docs.google.com/a/gsa.gov/document/d/1MErQxTmd49Xppbd5zaCq3c_d2CslDgy4Va93IhB1hWQ/edit?usp=sharing) for easier editing

**Comment by jenniferthibault** [comment]
Closing in favor of implementation issue #1222
