### ISSUE TITLE
Design calendar exporting and subscription interactions

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#126]
**Stories:** So that users can understand their dates and deadlines for reporting, make it easy to:
- [Story 1](https://18f.storiesonboard.com/m/fec/!card/lVU6OcSYFHyYSznUFKPJ-Q): ...export a list of dates from the filtered calendar.
- [Story 2](https://18f.storiesonboard.com/m/fec/!card/rR2SMwIGDfva9DnUBqI-VQ): ...see changes by subscribing to calendars from a pre-defined list of options.
- [Story 3](https://18f.storiesonboard.com/m/fec/!card/H11GDQZbuNu_CjnUFKPJ-Q): ...add single events to their personal calendars.

**Comment by jenniferthibault** [comment]
List of relevant data: https://github.com/18F/fec-cms/issues/118#issuecomment-158192387
List of filtered data: https://github.com/18F/fec-cms/issues/125
List of calendar backend options: https://github.com/18F/fec-cms/issues/120

**Comment by jenniferthibault** [comment]
First, I'd like to make sure that I understand the definitions of these interactions. I've been poking around other examples to see what the common patterns are:

**Export:** By this, we mean that a user gets all the events in the calendar at that specific point in time, and the user is then able to add these to their own calendar. The events will not update in real time. Most commonly, I've seen this be called "**Copy** events to your calendar"  Is this the corect understanding of the interaction? And if so, @emileighoutlaw what do you think of the copy?

**Subscribe:** By this we mean that a user wants to stay updated on FEC events from their own calendar. 
*Open question:* Does this feature imply that the calendar stays updated in real time? @noahmanger ?

The White House uses [this interactive pattern](https://www.whitehouse.gov/blog#date-1449291600)
![wv0h90sijy](https://cloud.githubusercontent.com/assets/11636908/11616742/e5a4bb18-9c50-11e5-900f-8037521e0f25.gif)
@noahmanger can you help me decipher what is happening here on [the new page] (https://www.whitehouse.gov/feed/schedule/president)?

But I've found another example that gives many more subscribe actions: do we have one single action in mind? Or is it again meant to trigger options. If so, what are the options?

<img width="585" alt="screen shot 2015-12-06 at 10 16 15 pm" src="https://cloud.githubusercontent.com/assets/11636908/11618385/c9fb7a16-9c67-11e5-9454-024007732236.png">

**Comment by noahmanger** [comment]
Ok, after doing some sniffing around, I think we have three different interactions that we can offer:

## 1. Subscribe to a full calendar of events
This adds a URL to a user's calendar app of choice (Google, Yahoo, Apple Cal, Outlook) that is updated as changes are published. Not sure if it's truly _realtime_ but it's automatic.

## 2. Export list of calendar events
We should present two options here, to download as a .ics file and .csv file. The user can import these into their application of choice, but it won't auto-update anything.

## 3. Copy individual event to calendar
This simply creates a new event in the user's calendar with all the data in it, but it will not auto-update.

## Remaining questions:
Unfortunately, I don't think it's possible to provide #1 and #2 for a customized calendar feed created with the filters. The simplest solution would be that both apply to the full calendar. But if we wanted to provide them for subsets (say, just deadlines) then we'd need a separate step where the user specifies which calendars they want. 

## Examples
Eventbrite has the "add event to my calendar widget": 
![image](https://cloud.githubusercontent.com/assets/1696495/11637313/81539fbe-9cd5-11e5-8ec0-e2aaabaae399.png)

And [here's another](https://addevent.com/):
![image](https://cloud.githubusercontent.com/assets/1696495/11637332/944002a2-9cd5-11e5-802d-200c174aea2c.png)

**Comment by noahmanger** [comment]
And here's a little library we could use: https://github.com/carlsednaoui/add-to-calendar-buttons

**Comment by jmcarp** [comment]
I looked at Google Calendar and iCal, and both seem to support subscribing to an arbitrary url that returns icalendar-formatted events. Seems like this would work with any filters that we can express in a url, which should be all of them. Also, under this model, "subscribing" is really more a feature of the user's mail app that of our product--we offer a resource at some consistent url, and the mail client pings us at some interval to update.

**Comment by noahmanger** [comment]
Right, I guess the limiting factor though is we need to be able to provide icalendar formatted events at any arbitrary url. That's not a problem?

**Comment by jmcarp** [comment]
Shouldn't be--it's just a question of returning json- vs ical-formatted results. We might write things so that you can add an optional file extension to the url:

json: `/v1/dates/elections?type=primary`
ical: `/v1/dates/elections.ical?type=primary`

or query string:

json: `/v1/dates/elections?type=primary`
ical: `/v1/dates/elections?type=primary?format=ical`

**Comment by jenniferthibault** [comment]
Righto—I was excluding "Copy individual event" because it wasn't initially listed here (I thought on purpose, but seems not now, sorry!), but I have it included in the individual event mockups here: https://github.com/18F/fec-cms/issues/117#issuecomment-162405120

**Comment by emileighoutlaw** [comment]
Copy thoughts:

#### Subscribe
Subscribe seems like the right word for an action that auto-updates information on your calendar.

#### Export and copy
I can see folks confusing **export** for **copy**
- When users add a (non-updating) event to a calendar of their choice, I like **Add to calendar**. I've been looking around, and that seems like that's the most frequent language being used.
- For downloading a .ics or .csv, I like **Download calendar** rather than **Export**, unless users have to go through the same two-step export (then download) process we have on the data site right now.

#### Sub-options
For all three options (**Subscribe**, **Add**, and **Download**), users will have sub-options (calendar type or .ics/.csv). I like the way this option

![944002a2-9cd5-11e5-802d-200c174aea2c](https://cloud.githubusercontent.com/assets/10552702/11664438/bd19dac4-9daf-11e5-8fb1-6e54c798b5fc.png)

opens up on (hover? click?) because it limits the initial amount of copy on the page. I believe starting with only the high-level options will make it easier for users to scan and parse.

**Comment by jenniferthibault** [comment]
Subscribe, Add, Download. :+1: 

My understanding & open questions:

#### Subscribe
- Available on the calendar home page
- QUESTION: Does this button initiate a dropdown list, or open a new tab with an RSS thing? If a drop-down, which sub-items do we want to include? @noahmanger / @jmcarp 
- QUESTION: Does this subscription apply to the whole FEC calendar? Or should we make each category it's own calendar, eligible for subscription?

#### Download
- Available on the calendar home page
- Formats offered will be Google, Outlook, Apple Calendar. (Do we want Yahoo?)

#### Add
- Available from an individual event page
- QUESTION: Does this button require sub-options for formats? @noahmanger / @jmcarp

**Comment by noahmanger** [comment]
Almost. Here's what I understand we want / can do:

## Subscribe
- On the calendar home page
- Dropdown presents a list of options: Google, Outlook, Apple (idk about Yahoo)
- Clicking one of those options takes you to the respective application / website
- Choosing this option generates a subscription to a unique feed of events based on the filters you have applied

## Download 
- Available on the calendar home page
- Simply downloads a static list. Options should be (I think): .ics and .csv

## Add an individual event
- Available from an individual event
- Same options as the subscribe button

**Comment by jenniferthibault** [comment]
Thanks very much for helping me clarify!

From the calendar control center, here's what these could look like in action:

#### Calendar home: Download or Subscribe
![screen shot 2015-12-09 at 6 28 13 pm](https://cloud.githubusercontent.com/assets/11636908/11702193/c8b71d4e-9ea2-11e5-9ef3-5050a541f0c6.png)

#### Event page: Add to calendar
![screen shot 2015-12-09 at 6 28 30 pm](https://cloud.githubusercontent.com/assets/11636908/11702201/ce964668-9ea2-11e5-8dc4-e127200906aa.png)

@emileighoutlaw: wordsmithing?

**Comment by jenniferthibault** [comment]
A small edit to the work above. @emileighoutlaw what do you think of the following shortened button text? Too abbreviated? I'm trying to reduce visual clutter, but not to the point of adding confusion because there isn't enough instruction.

<img width="318" alt="screen shot 2015-12-10 at 3 49 03 pm" src="https://cloud.githubusercontent.com/assets/11636908/11728063/99ee06ea-9f55-11e5-80f8-7da9940f62e0.png">

**Comment by emileighoutlaw** [comment]
Yes! I think trimming down to just the words `Download` and `Subscribe` is a great call.

### Download dropdown
How about these for options:
> .ICS (Apple calendar)
> .CSV 

I like having the extension prominent (and first), so people don't think they're adding, rather than downloading.

### Download dropdown
I think we need to add the word "calendar" after Outlook too, since it's a suite that has several arms (one of which is calendaring)

**Comment by noahmanger** [comment]
in download I think you can leave off "Apple Calendar". .ICS isn't strictly Apple Calendar (it's a generic standard), it's just what Apple Calendar uses.

**Comment by emileighoutlaw** [comment]
Oh great. Even better.

**Comment by noahmanger** [comment]
I think just the extension is fine. Do we capitalize extensions?

**Comment by emileighoutlaw** [comment]
Good thought, Noah! 

Just consulted the Content Guild on this one. The answer is we don't capitalize extensions when there's a period before them.

My preference:
>Download
>.csv
>.ics

Alternative:
>Download
>CSV
>ICS

**Comment by emileighoutlaw** [comment]
Final suggestions

> Download
.csv
.ics

>Subscribe
Apple calendar
Google calendar
Outlook calendar


(I made the options under both alphabetical)
