### ISSUE TITLE
Design way for users to navigate to audit search

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1311]
Implement way for users to navigate to audit search
Research findings and history in 18F/openFEC-web-app#2317

- [x] Content-review for possible [Enforcement](https://www.fec.gov/legal-resources/enforcement/) page reorganization
- [x] Decide on which design patterns/solutions to include in order to address navigation issues
- [ ] Design hi-fidelity mock-up

**Comment by JonellaCulmer** [comment]
History in https://github.com/18F/openFEC-web-app/issues/2317

**Comment by JonellaCulmer** [comment]
@llienfec @jameshupp @AmyKort There are some content-related questions included in the research findings issue for you all. Would love your feedback. 18F/openFEC-web-app#2317

**Comment by jenniferthibault** [comment]
We had a great design pairing on this today that cleared up some process questions. We're going to do a better job of using the same vocab for stages of work that delineate what type of task it is, and who should be assigned. To support that, I've 

- renamed https://github.com/18F/openFEC-web-app/issues/2317 as a "Research" issue where we uncover needs and trends
- renamed this issue as a "Design" issue, where we will end with mockups that meet the needs identified in research
- moved the last completion criteria from this issue in to an "Implement" issue, which will be assigned to @johnnyporkchops , and will end with a pull request that turns the design work into interactive elements on the site through code

Important to acknowledge that this process is not always so linear. Many of our workflows will likely follow this process in order, but some should not. It's ok to use code to design things, and it's ok to design before you research, especially when you want to have a concept to test with in your research. Please don't interpret this ordering as a rule.

Next up, and actual update on the design work for this issue 🙃

**Comment by johnnyporkchops** [comment]
@jen, thanks for clarifying the process ( and its flexibily) this is definitely going to be helpful going forward

**Comment by jenniferthibault** [comment]
Based on @JonellaCulmer 's [research](https://github.com/18F/openFEC-web-app/issues/2317#issuecomment-337281010), I'm pulling her foundational sketch from the research issue in here so we can see things all together:

![enforcement2](https://user-images.githubusercontent.com/31663028/31675603-1f13173c-b333-11e7-95a4-5cb9139e8492.JPEG)

In design pairing, we talked through a few factors that make certainty for this issue complex:
1. We expect the changes to the legal resources landing page to impact how people navigate to the audit search
2. Since we continue to move systems for enforcement resource searching from the old site to the new site, there may be changes needed to the enforcement landing page model. Since that's evolving, we want to focus our content and development efforts on making them available first, and making them better navigated and designed when we have a more complete picture of the new system.

To make the audit search recognizably available on the new site, we should use the embedded search modules on the slab pattern (like we do with AOs and MURs) and integrate the most often first-used filter fields, which are the candidate/committee field for external users, and category for internal users.

### Placement of search modules
Based on observed navigation behaviors, we think that we should place the embedded search on the enforcement landing page, and on the audit overview page. 

#### Enforcement page changes
- Embeds audit search module and link to advanced search
- Calling more attention to secondary overview pages and search systems by changing links to buttons
![screen shot 2017-10-23 at 8 47 57 pm](https://user-images.githubusercontent.com/11636908/31919895-97072030-b833-11e7-83f2-3e41504ae7bc.png)
![screen shot 2017-10-23 at 8 48 16 pm](https://user-images.githubusercontent.com/11636908/31919896-9716cabc-b833-11e7-8e2a-63b085d00bf3.png)

#### Audit report overview page changes
- Embeds identical audit search module and link to advanced search
![screen shot 2017-10-23 at 8 48 32 pm](https://user-images.githubusercontent.com/11636908/31919912-a81df5ba-b833-11e7-8e11-047f796b6e9c.png)

____
@JonellaCulmer @llienfec would appreciate if you could take a look to make sure that this reflects our discussion on Friday. 👀

**Comment by JonellaCulmer** [comment]
Thanks, @jenniferthibault! I believe this matches what we discussed. 

Would love @llienfec @AmyKort thoughts on the example text below the candidate/committee or ID search. I ran into a similar issue when wireframing. Don't necessarily want to call out a specific candidate or committee that has been audited, but also don't want to give an example that will yield no results if someone tries to use it.

**Comment by AmyKort** [comment]
Does this search across all types of audits? One option is to pick a presidential candidate committee that accepted public funding and, as a result, agreed to an audit. So, if you chose Ford for example, that would be PRESIDENT FORD COMMITTEE(C00031336) -- in some sort of way that makes a good example. One thought.

**Comment by llienfec** [comment]
Yep, I think this matches what we discussed too.  Also, really great solve @AmyKort.  I think an old, required Title 26 audit is a great choice.

**Comment by JonellaCulmer** [comment]
That's sounds like a wonderful solution, @AmyKort! Thank you!

**Comment by JonellaCulmer** [comment]
@jenniferthibault With the consensus on the mock-ups you've done and the examples, can we now move this to implementation? Of course, we need the [audit search](https://github.com/18F/fec-cms/issues/1304) and [canonical](v) pages needs to be built first.

**Comment by jenniferthibault** [comment]
Moved to implementation in #1360. Closing!
