### ISSUE TITLE
Refine descriptive text for the new audit search

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1347]
To help users better understand and use the audit search system, find what they are looking for and understand what they are looking at, we need to review and refine the API descriptive text of our new audit search. We'll focus on making sure the descriptions are accurate and easy to understand.

- [x] We'll need to find a way to make this language editable for content folks (google doc?)
- [x] Review for accuracy
- [x] Review for plain language
- [x] Determine whether we need any SME review
- [x] Get that review if we think we need it

**Comment by AmyKort** [comment]
@fec-jli  Do you have access to the placeholder text we have for the audit search? We need to put that text into a document so that @rhoughfec can edit the text, share it with stakeholders, etc. It could be a google doc, for example.

**Comment by jenniferthibault** [comment]
@AmyKort is this in reference to the text on the API? Or is it text that shows up on the main site?

**Comment by AmyKort** [comment]
My understanding is that there was text associated with the search to let users understand what they were filtering for and what they were looking at, and that for the purposes of the work completed on the Audit search so far this was text brought directly over from the old site. So, I thought this task was to have someone look over that carry over language that would be visible to users searching through the new audit search.

**Comment by jenniferthibault** [comment]
@fec-jli can you help us out and clarify what text this issue is about?

Since I wasn't in sprint planning, I can't be sure, but if this is in reference to the text that appears above the search system here, I think we can safely leave it out in favor of the filters being self-explanatory. 

<img width="1112" alt="screen shot 2017-10-23 at 9 17 49 pm" src="https://user-images.githubusercontent.com/11636908/31920547-c71baae4-b837-11e7-8614-2f019f0fb742.png">


If this is talking about the language on pages like the [Enforcement](https://www.fec.gov/legal-resources/enforcement/) page or the [Audit report overview](https://www.fec.gov/legal-resources/enforcement/audit-reports/) page, in [the designs for embedding the search tool links](https://github.com/18F/fec-cms/issues/1311#issuecomment-338838486), we haven't changed any surrounding text (and I'm not sure there's a need, but you may recognize it better than I).

**Comment by AmyKort** [comment]
@jwchumley Can you help us out?

**Comment by AmyKort** [comment]
OK! My mistake--we are looking at the API descriptions. @jwchumley can you help us get readable text for those and take a first pass at it? After that, @rhoughfec can take a crack at readability, and we'll also need to make sure there's nothing we need to run past our SMEs. Thanks!
