### ISSUE TITLE
Check merges into old release branch release/public-20170913

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1355]
This release branch release/public-20170913 was never deployed due to issues moving to our new continuous integration tool, CircleCI. We need to check any PRs that were directly tied to that release branch to ensure other resolved tickets do not get left behind.

**Comment by patphongs** [comment]
2 existing PRs that were made directly to the `release/public-20170913` branch need to be checked and we need to determine if they are still necessary to merge into the new release branch: `release/public-20171011`.

https://github.com/18F/fec-cms/pull/1243
https://github.com/18F/fec-cms/pull/1246

**Comment by johnnyporkchops** [comment]
- [ ] #1243 can be safely deleted, this related to the home-folder conflict which is resolved in migration 0094
- [ ] 1246 edited to reflect changes since, and a new PR to release/public-20171011 has been made [1356](https://github.com/18F/fec-cms/pull/1356)
This branch has been tested locally when merged with release/public-20171011

**Comment by dorothyyeager** [comment]
Hi - just to make sure - can you check to make sure this PR from late August makes it into the release? https://github.com/18F/fec-style/pull/765 It was done around the same time as the typo fix PR that @jenniferthibault asked about.

**Comment by patphongs** [comment]
The latest terms.json has been merged into the release branch. https://github.com/18F/fec-cms/pull/1362
