### ISSUE TITLE
Add filter components to pattern library

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-cms#1368]
Ensure that the base components of filter interactions are recorded in the pattern library for consistent use and construction in interfaces.

Pull designs from https://github.com/18F/fec-cms/issues/1428

**Completion criteria**
- [ ] Run migration script (@xtine)
- [x] Decide how we want to list or nest filters in the side-nav of the pattern library
- [ ] Add components that were identified to the pattern library repository via pull request

This is a combo design & implementation issue

**Comment by jwchumley** [comment]
Xtine needs to do the migration script first.

**Comment by jenniferthibault** [comment]
Identified base components have been broken down into the following implementation issues:

- Checkboxes: https://github.com/18F/fec-pattern-library/issues/22
- Radio buttons: https://github.com/18F/fec-pattern-library/issues/25
- Dropdown: https://github.com/18F/fec-pattern-library/issues/23
- Toggle button: https://github.com/18F/fec-pattern-library/issues/24
- Search fields: https://github.com/18F/fec-pattern-library/issues/26
  - Boolean search fields (separate because it's a little more complex): https://github.com/18F/fec-pattern-library/issues/27
- Ranges: https://github.com/18F/fec-pattern-library/issues/28

For nesting the filter patterns, we suggest the following:

![screen shot 2017-11-13 at 1 33 06 pm](https://user-images.githubusercontent.com/11636908/32742371-3ae5689e-c877-11e7-93ce-353f52f7fb1d.png)
