### ISSUE TITLE
Election page compare candidates: add coverage end date

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1372]
Add coverage end date to election page compare candidates data table.

https://www.fec.gov/data/elections/house/CO/04/2018/

**Comment by JonellaCulmer** [comment]
Related issue: #1373

**Comment by JonellaCulmer** [comment]
Researching this issue, I spoke with Christian in the Press Office. We discussed the issue facing press contacts when trying to use this information (links above) and have some key takeaways:

- Press contacts often want to know whether the numbers reflected in the election tables included the latest figures
- To verify data was up-to-date, users were encouraged to total the figures shown for previous reports to see if the totals matched up
- Wanted to know if the data included the 30th or before.

Coverage dates were again discussed as an option to resolve this work-around, as is noted in the initial comment on this issue. While coverage dates are important, the same information can be gleaned simply by knowing which reports have been filed.

Recommendation
Incorporate the `Most recent filing` in the column for source reports. Including the latest report in this column would provide relevant and up-to-date information on what the figures already represented in the table mean. The proposed solution does not break any design patterns that already exist on the site and should be relatively easy to implement compared to the introduction of a new interaction. 

![electiontablescreenshot1372](https://user-images.githubusercontent.com/31663028/32508194-8cc1a296-c3b7-11e7-9514-4d86259ff430.jpg)

**Alternative solutions also considered but not pursued:**
Similar solutions were considered for this issue as #1373, in addition to creating a new data visualization pattern such as expandable rows that allow for additional information, such as Receipt date, and a breakdown between raising and spending. However, including additional information beyond the need could create new issues and would introduce a new interaction that we have not used previously. Essentially forcing users to learn a new interaction that they won't use on any other part of the website. 

**Next steps:**
@PaulClark2 Flagging for your review. This proposed solution as well as the solution for #1372 (forthcoming) can be discussed 
cc: @patphongs @johnnyporkchops

**Comment by jenniferthibault** [comment]
I think this very smartly uses an existing field as an opportunity to provide more context instead of introducing complexity with new interactions.

Looking at it closely, I'm wondering if we can accommodate the end date through slightly different microcopy.

For example, here's one option next to what's been proposed already that pulls the coverage end date in with the report title. I don't love that it's a little more verbose, since space really matters here—so maybe our content geniuses might be able to offer a more concise suggestion. What do you think @AmyKort ?

![screen shot 2017-11-07 at 4 54 38 pm](https://user-images.githubusercontent.com/11636908/32520111-dcfd0384-c3dc-11e7-80c6-4e6d92336aea.png)

**Comment by PaulClark2** [comment]
Thank you for these recommendations. My concern is instead of being able to quickly look down a colum to determine which reports we have processed, or candidate committees have submitted, users need to read the contents of the `source reports` cell.  The example above, Virginia’s Senate race, only has two candidates. Look at Florida’s 27th CD, https://www.fec.gov/data/elections/house/FL/27/2018/.  There are 17 candidates in that race.

**Comment by jenniferthibault** [comment]
Right— my understanding is that this is an acceptable compromise because the coverage date is a supporting fact for the other data in the table. I.e., the common pattern of digesting the information is to scan the financial total columns, make a brief mental note of who's got what money, then check the coverage dates to make sure you're comparing the same time period across candidates. OR— if you're a less advanced data user, you might just stop at making the note of who has what money, and what party they're from.

To that end, I could see focusing the language on the coverage end date only, instead of the report title (which adds a lot of letters). Using the FL 27th race as an example, here's a screenshot with the real dates:

![screen shot 2017-11-07 at 5 57 39 pm](https://user-images.githubusercontent.com/11636908/32522457-56eab53a-c3e5-11e7-977d-011d7d9d5397.png)


Is it common that the coverage end date for most reports will be the same? Page 2 of the 17 candidates for FL 27 includes reports with coverage end dates in 2018...which seem like errors since they're in the future

**Comment by PaulClark2** [comment]
Most of them will be the same except for a few days around filing deadlines. 

The coverage end date information is particularly important to reporters and researchers close to filing deadlines. It allows them to determine if they are comparing like totals. My understanding of the source of this request was from calls to Press and Public Records about what data we were presenting a few days before and after a filing deadline. 

Yes, a 2018 coverage end dates are most likely a mistakes.

**Comment by PaulClark2** [comment]
It makes sense to me to focus on language on the coverage end date.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/18F/fec-cms/issues/1470
