### ISSUE TITLE
Check transition jQuery version

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#1386]
Make sure that if transition uses jquery, it is on the most up to date version.

**Comment by patphongs** [comment]
Sorry I did not get to actually implementing this. I do know that it needs to be done on transition as it is using an older version of jquery. This will require an edit to all pages on the transition site. Will work on this in 4.4.

**Comment by johnnyporkchops** [comment]
There are a few different versions of jquery referenced on the site, the highest being jQuery 1.12.4
The transition site uses a few versions of jQuery for some pages where switching to newer version **will  break something**. 
1)transition.fec.gov/info/forms.shtml uses:
jquery-1.12.4.js

2)The datatables we use for [Enforcement Statistics](https://transition.fec.gov/press/bkgnd/EnforcementStatistics.shtml) and [Presidential Funding](https://transition.fec.gov/press/bkgnd/presidential_fund.shtml) uses jQiery 1.10.2 and uses  datatables feature that breaks if using above jQuery 1.10X for [this reason](https://datatables.net/forums/discussion/17431/fixedheader-extra-breaks-with-jquery-2-x)

The temporary compliance map that we put together to fix the problem with CORS error with the original map, unfortunately has to use jQuery 1.9.0,  but this CORS issue seems to be resolved and so we can remove this temporary map and use the original files as we have successfully tested for 2018 map.
jquery-1.9.0.js

If necessary we can try to use a higher version for the forms and enforcement tables (1st two above) and use jQuery migrate patches to correct anything that breaks functionality. This was not originally done because it did not seem worth refactoring legacy content if the transition site was going to be temporary.

**Comment by johnnyporkchops** [comment]
The following pages that were using differing jQuery versions have been updated to work with the latest jQuery (juery-3.2.1) and the CDN link for that has been added directly to the pages (tested on the https, S3 bucket)

- [ ] https://transition.fec.gov/info/forms.shtml
- [ ] https://transition.fec.gov/press/campaign_finance_statistics.shtml
- [ ] https://transition.fec.gov/press/bkgnd/presidential_fund.shtml
- [ ] https://transition.fec.gov/press/bkgnd/EnforcementStatistics.shtml

There are a few files that represent URLs that are immediately redirected from like fecviewer and the map applications that contain references to outdated jQuery versions, but they can be removed since they are never loaded into the browser due to the redirects. 
Example: https://transition.fec.gov/pindex.shtml

**Comment by dorothyyeager** [comment]
Just a note - we are planning on taking the forms.shtml page down as it has been replaced by the forms page at https://www.fec.gov/help-candidates-and-committees/forms and is no longer needed. See https://github.com/18F/fec-cms/issues/1352

**Comment by patphongs** [comment]
Files have been updated and will be uploaded to the transition site tomorrow (Tues). This should complete updating of jquery.

**Comment by AmyKort** [comment]
Is this ready to go into done?

**Comment by patphongs** [comment]
Files have been uploaded to the transition staging server and synced with production. This completes this ticket.
