### ISSUE TITLE
Determine buckets for SSF content

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1392]
Now that we're ready to put up our campaign guide content for SSFs, we'll need to determine whether the structure for organizing guide content we've established needs to be tweaked to meet the needs of SSFs.

- [x]  Find the prior research on this issue
- [x]  Decide whether we need to adjust our assumptions based on what we've learned since we started launching this content
- [ ] Identify the high-level buckets for SSF content

**Comment by dorothyyeager** [comment]
I have found the prior research and turned it into a google doc. It will need some updating to make sure it tracks the new Corp/Labor Guide but I think the basic framework is pretty solid.

https://docs.google.com/document/d/1A29RluvEEjaPMC1v8LcUgieqADCs5Ei5fGYgyB1rHtc/edit?usp=sharing

**Comment by dorothyyeager** [comment]
In reviewing the new Guide, I'm finding the prior research will indeed need some updating, but do like the approach we took. Am working on creating my suggestions for the buckets in this spreadsheet - https://docs.google.com/spreadsheets/d/1Jnkagj1Dnf_cu0IViNcR8WKXTyDzmaJstOLxdfg3qT4/edit#gid=0

**Comment by dorothyyeager** [comment]
Today @AmyKort @gsmaragdis @llienfec @PaulClark2 @jameshupp and I had a really solid meeting and have decided to go with the buckets as laid out in the google spreadsheet linked in my last comment to start. Because SSFs have a unique set of fundraising rules, but don't normally make disbursements for fundraising, we are treating those rules as an additional bucket that will slot in between receipts and disbursements (so this type of committee will end up with 8 buckets instead of the 7 the other categories have).

I'll make a new issue for the work to come to fill up these buckets, so work on this issue is completed and it can be closed.

**Comment by AmyKort** [comment]
Thanks @dorothyyeager !
