### ISSUE TITLE
Request: add authorizing candidate information to about this committee tab

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1414]
So users can more easily identify candidates of authorized committee, we should add candidate name, candidate state, candidate district and candidate party affiliation to the `about this committee` tab of authorized committees.

- [ ] add candidate name
- [ ] add candidate state
- [ ] add candidate district
- [ ] add candidate party affiliation
- [ ] add link to candidate profile page
- [ ] consider adding this information below the committee name in addition to adding it to the `about this committee` tab
- [ ] remove political party for all committees except party committees and authorized committees
    - [ ] For committee profile pages of political party committees, the Political party label makes sense.
    - [ ] For committee profile pages of authorized committees, the label should probably be Candidate party (or Candidate party affiliation).
    - [ ] For all other committee profile pages, the label shouldn't be displayed or the text following the label should say not applicable.

![image](https://user-images.githubusercontent.com/11817734/32169564-70df454a-bd47-11e7-82ea-8ecd859d643f.png)

Related issues:
https://github.com/18F/FEC/issues/4682
https://github.com/18F/FEC/issues/4714
https://github.com/18F/FEC/issues/4719
https://github.com/18F/fec-cms/issues/1438

**Comment by JonellaCulmer** [comment]
Will take a closer look at this issue, but at first glance this requested information includes information that is already available on the candidate panels seen at the following links: 
https://www.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true
https://www.fec.gov/data/candidates/senate/?election_year=2018&cycle=2018&election_full=true
https://www.fec.gov/data/candidates/house/

This information _should_ be easier to find on the actual candidate page, where the most complete picture of who the candidate is is available. 

![candidatesforsenatedatapagewithpanel](https://user-images.githubusercontent.com/31663028/32340978-8459f0a6-bfd2-11e7-983a-12c51ffd3c68.jpg)

**Comment by PaulClark2** [comment]
There a few goals here: 1) to have candidate information on committee profile pages of authorized committees, 2) to have links to candidate profile pages from committee profile pages of authorized committees, and 3) to have party affiliation display properly on all committee profile pages.

These bullet points expand the last item of the checklist in the original post. 
- For committee profile pages of political party committees, the Political party label makes sense.
- For committee profile pages of authorized committees, the label should probably be Candidate party (or Candidate party affiliation). 
- For all other committee profile pages, the label shouldn't be displayed or  the text following the label should say not applicable.

**Comment by JonellaCulmer** [comment]
@jenniferthibault and I walked through a few approaches to solve this issue and came away with a good direction to consider with the larger group. Other approaches are discussed below.

### Recommended approach
**Approach 1**
The approach we want to discuss includes adding key candidate information bound on a card beneath the committee's information on `About this committee`. Using the card here would mirror the use of the card on candidate pages. Which are currently in place to take a user from a candidate page to the committee page. 
![screen shot 2017-11-06 at 11 30 03 am](https://user-images.githubusercontent.com/31663028/32451894-1487b1f2-c2e6-11e7-816a-ee110e665df1.png)

![screen shot 2017-11-03 at 1 07 21 pm](https://user-images.githubusercontent.com/31663028/32451025-da7e0e22-c2e3-11e7-8d78-af34e74ff556.png)

In order to further support the link between candidate and committee, we recommend moving the committee information (including authorized committees) above `Other documents filed`

Additionally, we would include a button on the left-nav. In the event a user is not looking at the `About this committee` page, they would miss valuable information about the candidate and who the candidate is that is connected to the committee. The placement of this button on the left-nav also reinforces and supports the placement of the button currently seen on candidate pages that reads, `Compare to opposing candidates`. So a user could essentially move from a committee page, to the candidate page and then compare that candidate to others in the same election. 

Below are some examples of how the [callout](https://fec-pattern-library.app.cloud.gov/components/detail/callout.html) would look in the `About this committee section`:
![screen shot 2017-11-03 at 1 08 07 pm](https://user-images.githubusercontent.com/31663028/32451218-4c880ca2-c2e4-11e7-898b-c14916acef18.png)

And how the [button (call-to-action basic)](https://fec-pattern-library.app.cloud.gov/components/detail/basic.html) would look on the left nav: 
![screen shot 2017-11-06 at 11 30 42 am](https://user-images.githubusercontent.com/31663028/32451921-21722ae6-c2e6-11e7-9acd-9a0ae5cf427d.png)

### And here are other approaches we talked about, but decided not to pursue
**Approach 2**
We considered adding the candidate name and a link from the subtitle, but were not convinced that users would notice this addition and nowhere else on the site is there a link in the subtitle. Making this change would break the pattern held on all other pages featuring a subtitle. 
- Adding candidate name as a link to candidate profile (but not directly pulling other info onto the page)
  - TAMMY BALDWIN

**Approach 3**
We also considered including the information requested in this issue to the subtitle below the committee name, but that would extend the line so much so that in the event of a long candidate name (or vice presidential candidate name) this would create wrapping. Which is not ideal as a first attempt in this redesign.

**Approach 4**
Another option we considered included listing out the information detailed in this issue to below the Committee information on the `About this committee` page. While this would lay out all the requested information, we were not convinced that this was the most effective and usable way to incorporate this information. This would also yield a long list and not be as visually appealing.

- Surface the information requested directly on the page:
  - in a section about the candidate
   - Candidate name: XXX
   - Candidate party: XXX
   - Candidate office: XXX , District XX
   - Candidate state: XXX

### Next steps
In order to move this forward, want to flag this for @PaulClark2's review. Paul, if you have any questions about this approach, happy to plan some time this week to review it and address any concerns. 
cc: @patphongs @johnnyporkchops for your awareness on this issue. If you have any questions about this approach, we can talk about this at design pairing.

**Comment by PaulClark2** [comment]
Thanks for talking me through this. Let's go with your recommended approach.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue:https://github.com/18F/fec-cms/issues/1476
