### ISSUE TITLE
Search for committee with no 2017/2018 activity causes error

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-cms#1421]
https://www.fec.gov/data/committee/C00583658/

This link is throwing a server error. I think what is going on is that they have no 2017/18 activity. 
https://www.fec.gov/data/committee/C00583658/?cycle=2018 gives a "no data found" message.

**Comment by LindsayYoung** [comment]
I think this is the same as #1416 Pat and I are looking at it now

**Comment by LindsayYoung** [comment]
We made progress and we think we can git this finished and deployed tomorrow

Basically it was looking for the most recent processed document and looking for all the efilings since the last processed document. If there was no document, there was date passed and that caused an error. We are going fix this by passing the first day of the cycle if there is no processed forms for the cycle.
