### ISSUE TITLE
Political party always says "none" on candidate committee pages

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-cms#1438]
https://www.fec.gov/data/committee/C00213512/?cycle=2018&tab=about-committee

API has "Dem" but displays "None"

**Comment by pkfec** [comment]
Myself and Helen would like to pair and work on this.

**Comment by pkfec** [comment]
fixed the bug. tested in my local.
submitted a PR for @xtine and @fec-jli to review.

**Comment by PaulClark2** [comment]
https://github.com/18F/fec-cms/issues/1414

**Comment by JonellaCulmer** [comment]
@PaulClark2 @jwchumley Is there a greater desire to fix the error and have a Political Party displayed? Or remove Political Party from candidate committee pages? In a previous discussion we talked about removing the Political Party line from committee types other than Party Committees, particularly from candidate committees, since it's the candidate with the Party affiliation, not their committee.

**Comment by PaulClark2** [comment]
@JonellaCulmer I think Priya's fix here is a good intermediate solution. The end-goal here is to have party affiliation display properly on all committee profile pages. 

- For committee profile pages of political party committees, the Political party label makes sense.
- For committee profile pages of authorized committees, the label should probably be Candidate party (or Candidate party affiliation). 
- For all other committee profile pages, the label shouldn't be displayed or  the text following the label should say not applicable. 

I'll add this comment to #1414, too.

**Comment by xtine** [comment]
There are some committees that still have "None" like Actblue that has `party_full: None` here: https://api.open.fec.gov/v1/committee/C00401224/?sort=name&page=1&api_key=DEMO_KEY&per_page=20

In cases like these, would it be worth just removing the the Political Party line entirely, unless there is an explicit `party_full` defined from the API?

**Comment by PaulClark2** [comment]
Removing the `political party` line entirely for committees that shouldn't have party affiliations would be great. This issue is part of a larger issue https://github.com/18F/fec-cms/issues/1414. 


type	|	type_description	|	party affiliation
----	|	----	|	----
H	|	house	|	yes
P	|	presidential	|	yes
S	|	senate	|	yes
X	|	non-qualified party	|	yes
Y	|	qualified party	|	yes
Z	|	national party organization. non fed acct.	|	yes


type	|	type_description	|	party affiliation
----	|	----	|	----
C	|	communication cost	|	no
D	|	delegate	|	no
E	|	electioneering communication	|	no
I	|	independent expenditure - person or group not a committee	|	no
N	|	non-qualified non-party	|	no
Q	|	qualified non-party	|	no
O	|	independent expenditure-only committee	|	no
U	|	single candidate independent expenditure committee	|	no
V	|	non-qualified non-party with non-contribution account	|	no
W	|	qualified non-party with non-contribution account	|	no

**Comment by PaulClark2** [comment]
Fixed by https://github.com/18F/fec-cms/pull/1449
