### ISSUE TITLE
Replace "None" on About this Candidate page button

### ISSUE THREAD

**Issue by JonellaCulmer** [18F/fec-cms#1439]
For candidates participating in the upcoming [Alabama special election](https://www.fec.gov/data/candidate/S8AL00340/?tab=about-candidate), and [Georgia House District 6 Special election](https://www.fec.gov/data/candidate/H8GA06286/?tab=about-candidate),  the button on the `About this candidate` page, that connects you with other candidates in the same election, currently reads: "View all candidates in the None Alabama Senate election". The "None" could be replaced with "Special" or "2017 Special". 

Not entirely sure, but possibly related to this issue? https://github.com/18F/openFEC/issues/2621#event-1280376083 

- [ ] For the first step, we will make "None" not show.

![noneelection](https://user-images.githubusercontent.com/31663028/32343831-47c41140-bfdb-11e7-8886-5d51166483db.jpg)

**Comment by JonellaCulmer** [comment]
@jenniferthibault This is off-topic, but I noticed the two buttons that lead you to the same place. The "View all candidates..." on the right and "Compare to opposing candidates" on the left. Do you happen recall, or can you point me to, the reason for including both?

**Comment by lbeaufort** [comment]
Good catch, @JonellaCulmer! Looks like the issue is [here](https://github.com/18F/fec-cms/blob/94cf215d68735a1874a4350a91922aef85389e7d/fec/data/templates/partials/candidate/about-candidate.jinja#L68)

I think that should be `election_years` but when I try it, it shows up in brackets.

**Comment by jenniferthibault** [comment]
@JonellaCulmer I'm always glad for a chance to do some GitHub archeology!

The `View all candidates in the [year] [state] election` card in the "About this candidate" tab was the first link to exist. This feature exists to help people put the candidate and their financial data in context of the race and other contenders. 

We researched the existing experience of available elections info 
**Issue:** [Elections/Map research: Conduct user interviews and synthesize the results #2100](https://github.com/18F/openFEC-web-app/issues/2100)

And then we identified some quick wins to improve the experience 
**Issue:** [Elections work-stream: Identify quick wins and mid-to-long-term wins #2167](https://github.com/18F/openFEC-web-app/issues/2167)

One of the things we identified is that people were having a hard time finding the link to the full election from the candidate page, since it's only visible inside one tab (the "About" tab)

So that users could easily compare candidates running in a race, we created a more prominent link to comparison pages from candidate profile.
**Issue:** [Design new button linking to candidate comparison pages from candidate profile #2198](https://github.com/18F/openFEC-web-app/issues/2198)


What I haven't found is any evidence of us discussing the duplicative nature of the link. Relying on conversational memory here, but I _think_ we chose to keep it in both places because there was evidence that when people were in the "About" tab, they did expect to find a pathway there. Open to discussing further!

**Comment by JonellaCulmer** [comment]
Thanks for that background @jenniferthibault!

I understand the button on the "Compare opposing candidates" button being placed there so users can get to other candidate information regardless of the page they were viewing. And there is greater visual appeal to the "About" page button: it's larger, in the center of the page and features a nice little icon. So I understand why someone would click on that button too. I don't think they're have been any complaints or issue on this, so I'm not advocating for change _just_ because I noticed something, but it's helpful to understand the background.

**Comment by JonellaCulmer** [comment]
Updated initial comment to reflect both the Georgia and Alabama special elections that are affected by this bug.

**Comment by xtine** [comment]
There's a fix going into next release that will not show "None" as an election year anymore.

**Comment by ccostino** [comment]
Fixed for the next release, and we've confirmed on the staging site:

<img width="1097" alt="screen shot 2017-11-21 at 3 16 36 pm" src="https://user-images.githubusercontent.com/121565/33094767-3a0c8c96-cecf-11e7-8dea-b28f7a8bb674.png">

**Comment by AmyKort** [comment]
Thanks!
