### ISSUE TITLE
Link to API on homepage is incorrect

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1447]
![image](https://user-images.githubusercontent.com/11817734/32394659-3e48f62e-c0b4-11e7-8331-8fdca879e8ea.png)

The API link directs users to `https://www.fec.gov/` instead of `https://api.open.fec.gov/developers/`.

- [x] Hard-code API link on homepage and data app
- [x] Enter new issue for transition_url variable

see if it’s used on any other templates, and hardcode
and then remove it from settings as well
you can see this in `/fec/settings/base.py:123`
sets template variables for data app
only data app pages can grab those constants
and not in any other app (because they are django templates not jinja template)

**Comment by lbeaufort** [comment]
@xtine - I looked into this and can't figure out why the URL isn't correct because it looks like `footer-navigation.html` is inserting the FEC_API_URL environmental variable: https://github.com/18F/fec-cms/blob/94cf215d68735a1874a4350a91922aef85389e7d/fec/fec/templates/partials/footer-navigation.html#L64

It could be related to issues we were having with detecting environment - in the short-term, would it make sense to hard-code the link to the API?

**Comment by xtine** [comment]
@lbeaufort: the both `{{ transition_url }}` and `{{ FEC_API_URL }}` are not showing up in the templates because they are not actually passed into the template. For a global Django variable we actually need to define a context processor for that. Django Jinja actually provides a global constants in its context processor but that only helps with data pages, not the other apps.

So you can notice this behavior as any https://www.fec.gov/data/* URL has the correct footer links for API but the others do not.

**Comment by lbeaufort** [comment]
New issue to handle Django global variables: https://github.com/18F/fec-cms/issues/1493
