### ISSUE TITLE
Identify redirects for classic site

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1472]
A number of static pages from the classic site are out of date, and others contain links to pdf and audio files that are now housed on fec.gov. Let's go through the static pages on classic and create additional redirects where necessary for pages that are either completely captured on the new site or are now out of date.

- [x] Determine methodology
- [x] Create spreadsheet

UPDATE: Our last content inventory closed well over a year ago. As a first step for this new issue, we're going to update our inventory of what is on classic and what is on the new site. I'll keep this issue open, since it has so much great information in it, but we'll need to determine next steps once we better understand the universe of content we currently have.

**Comment by AmyKort** [comment]
moving to the next sprint

**Comment by AmyKort** [comment]
Two more from Dorothy:

Was looking at this issue (#1310 (comment)) and there's a few classic pages in the press section in the comment I'm linking that will need some sort of redirect (but there's not really a great page to redirect to so the pages might need to be moved into transition) - just wanted to note it here and then maybe we can close #1310 .

While I'm at it, two more classic links in a different issue: 18F/FEC#4538 - Again, two older documents that will need to be moved into transition and have a redirect applied.

**Comment by llienfec** [comment]
Suggesting moving this to next sprint because of outages and other priorities.

**Comment by dorothyyeager** [comment]
Totally agree.

**Comment by dorothyyeager** [comment]
Noted for when we tackle this issue: Quick answer at classic.fec.gov/ans/answers_candidate.shtml#nonfederal_fundraising and the help page at classic.fec.gov/law/nonfederalfundraisingfaq2.shtml can be replaced now by this 2017 Record article with updated examples:
https://www.fec.gov/updates/fundraising-federal-candidates-and-officeholders-other-candidates-and-committees-2017/.
Tagging @patphongs because she asked me to. :)

**Comment by AmyKort** [comment]
I have one more. http://classic.fec.gov/pdf/commissioners_tips.pdf 

I'm not sure where this pdf actually lives, but we need to link from the Tips link under Compliance to the pdf https://www.fec.gov/updates/week-october-31-november-4-2016/

**Comment by dorothyyeager** [comment]
For the Commissioner tips one, we can upload that PDF into the CMS and then update links and redirects accordingly.

**Comment by dorothyyeager** [comment]
Just linking a google doc from a previous issue that might be useful for this one too. https://docs.google.com/document/d/170HXm70q8MVZ7zbuDNLWtR670DRF3QPprwJs3pIw_3Y/edit

**Comment by dorothyyeager** [comment]
The spreadsheet we used to inventory Guides and publications on classic and transition worked well for that issue in terms of listing what we have, what we decided to do with it, and the redirect to use, so I've made a copy of it as a starter for us and updated where needed. I'll add sections to it for the pages on classic that weren't covered. 

Spreadsheet is here https://docs.google.com/spreadsheets/d/10BodftlKF--VBavaAtDJirGVGrKY8Oow-K4M0ht2Ovw/edit#gid=0 @llienfec

**Comment by dorothyyeager** [comment]
I've uploaded that 2016 Commissioners tips document and it's live at https://www.fec.gov/resources/cms-content/documents/commissioners_tips_2016.pdf.

Have added it to the spreadsheet for the redirects and updated the link to it in the 10/31/16 weekly digest that @AmyKort linked.

**Comment by dorothyyeager** [comment]
@llienfec  and I are finding that there are a number of pages on transition that are duplicative and in cases, outdated. So they probably should come down. As we find them, we've started a page on our inventory spreadsheet for them. https://docs.google.com/spreadsheets/d/10BodftlKF--VBavaAtDJirGVGrKY8Oow-K4M0ht2Ovw/edit#gid=1102356871. In the meantime, the inventory of classic continues on that same spreadsheet.

**Comment by dorothyyeager** [comment]
Just spoke with @AmyKort and we agreed that this issue has morphed into one that identified issues that need to be resolved with the classic and transition pages, to ensure we aren't leaving info behind or bad info up. Issues #1727, #1728, and #1729 have been created to address those in the next PI. 

We modified this issue's completion criteria to reflect that this issue is mainly taking inventory of the classic and transition sites - an ongoing process but we will try to get as far as we can with it for this sprint in advance of the PI-5 planning sessions so that participants will have reliable information as they plan out the next months' tasks.
