### ISSUE TITLE
update jQuery + Handlebars in swagger

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#1491]
I don't see the package listed here, so you will have to figure out where this is coming from too
https://github.com/18F/swagger-ui/blob/master/package.json

(I am adding the issue in this repo so it doesn't get lost It won't show up on all the boards if it is in the swagger repo)

**Comment by jwchumley** [comment]
(xtine says) Look at package-lock to identify dependencies on dependencies.

**Comment by LindsayYoung** [comment]
@xtine checking on this one since it is ATO related, tell us if you need support

**Comment by xtine** [comment]
Fixed in https://github.com/18F/swagger-ui/pull/14

**Comment by patphongs** [comment]
*Update:* We discovered a bigger problem with the way that jquery and handlebars js dependencies are being updated. A temporary solution has been put in place and is pending merge of this hotfix: https://github.com/18F/swagger-ui/pull/16

In sprint 4.5, @xtine would like to take on updating swagger-ui to 3.x so that we can streamline the library better. https://github.com/18F/openFEC/issues/2770

**Comment by LindsayYoung** [comment]
Thank you @xtine and @patphongs
