### ISSUE TITLE
Beta warning on content pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#155]
Warning that content is in beta— a requirement from OGC before we can launch Registration and reporting content

Document here: https://docs.google.com/document/d/1-mOlrfxv5vM2fuVSk6jk7OAk4vdtQ5uxKQHjG-GuLrI/edit
 * [x] Draft content
 * [x] Amy review
 * [x] Edits
 * [x] Final Amy approval
 * [x] Talk to @jenniferthibault and @noahmanger about the best way to design and implement this

**Comment by jenniferthibault** [comment]
My first inclination for where it should go, is to have it *after* each page's copy. Putting it into the users' view early could interfere with their experience too early and cause doubt. If this disclaimer does cause users doubt, or any uncertain/otherwise negative feelings, I'd like them to have experienced (/fancy word for "read and interpreted") the content on their own FIRST, so that they can give their own judgement.

Here's one design in two scenarios for how that could look. Sometimes, we already have in informational bar at the bottom, sometimes, it would stand alone:
 ![reg-disclaimer-1](https://cloud.githubusercontent.com/assets/11636908/11786980/85f8e22c-a257-11e5-8be5-8b18d038cd0c.png)

Thoughts?

**Comment by emileighoutlaw** [comment]
I think this looks really nice— it's there on every page, but it doesn't overwhelm the design. Looking forward to @amykort's and @amypike's thoughts.

**Comment by AmyKort** [comment]
I think it looks great. It's a good middle-ground--on every page but not distracting. Thanks!!

**Comment by jenniferthibault** [comment]
Sounds like we are good to go, glad we could find a way to make it informational but not distracting. Transferring this over to @noahmanger for implementation.

**Comment by amypike** [comment]
I think this looks great - it's there as a warning but doesn't smack the user in the face.  Nice job!

**Comment by jenniferthibault** [comment]
This has been implemented! Closing
