### ISSUE TITLE
Implement GovDelivery signup in footer

### ISSUE THREAD

**Issue by jameshupp** [18F/fec-cms#1669]
This builds on #1194.

GovDelivery has provided us HTML to initiate the email signup process. This is a universal button that goes in the footer across the website. Rather than implementing this as in-line HTML, we want to work this into the template using our own button classes.

There are a couple assets associated with this.

Here's a mockup of how the button renders in the footer (see lower right).
![usfec_buttonv2](https://user-images.githubusercontent.com/6314097/34268987-c1f86204-e650-11e7-901f-1ad5dc125594.jpg) 
I don't think this is entirely in keeping with our styles, but the basic idea is clear. A couple things to note about this:
- Use the call to action button style, if possible. I don't think it's so close to the feedback drawer button that it causes confusion. In fact, the extra color might attract more attention to that portion of the screen.
- The GovDelivery icon might not be the right resolution. If that's the case, let me know and I'll track it down.

Here's the HTML they provided for the button.
[USFEC_Buttonv2.txt](https://github.com/18F/fec-cms/files/1580143/USFEC_Buttonv2.txt)
There's a query string in the target URL — `qsp=CODE_RED` — that I'm not sure about. I am tracking this down to see if it's something we actually need or if we want to use something else for tracking purposes.

**Comment by xtine** [comment]
Because this is just a link to their site to sign up, are we allowed to modify the button to get there? If so, then we can re-use any of our existing button styles on the site to make it fit in better.

**Comment by jameshupp** [comment]
I definitely think we should modify the button to fit our styles. Their mockups show placement and general concept but they recognize the FEC team has a strong sense of style: consistency and principles.

The only issue I see is I think all the current text-and-icon button styles specify which icon to use in the class. We don't have one that uses a mail icon. We don't _have_ to use the GovDelivery-specific branding, but they can provide that to us really easily if we want to. Otherwise, a generic mail icon would be fine.

Both on FEC's and GovDelivery's side, having some icon seemed important, but we could also start without and come back to that. I know it's slightly faster to implement without one.

**Comment by xtine** [comment]
@jenniferthibault: thoughts on what icon+button to use?

**Comment by jenniferthibault** [comment]
Yep! You can see the initial intended styles from https://github.com/18F/fec-cms/issues/1044#issuecomment-321915091

Use our regular [standard basic button](https://fec-pattern-library.app.cloud.gov/components/detail/basic.html) and the icon we've used for email throughout the site is `.i-moving-envelope-circle` from https://fec-pattern-library.app.cloud.gov/docs/icons.html

I prefer this icon to GovDelivery's custom icon because there's no benefit of introducing their brand to FEC's app, and it keeps our icon system consistent if we don't deviate here.

However, we need it outside it's containing circle here, so I've re-exported it, and we'll need to add the new icon to the codebase as part of this. Here's the zipped svg file: [moving-envelope.svg.zip](https://github.com/18F/fec-cms/files/1580461/moving-envelope.svg.zip)


That should give us the following, using the language above:
![screen shot 2017-12-21 at 3 11 36 pm](https://user-images.githubusercontent.com/11636908/34273181-4ab976f4-e661-11e7-990d-1b670d89e23e.png)


Anything else I can get you, @xtine or @jameshupp ?

**Comment by jenniferthibault** [comment]
Resolved by #1673
