### ISSUE TITLE
Align calendar event types with API

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-cms#172]
At the moment, the event types described in #118 don't line up with the work-in-progress API implementation in https://github.com/18F/openFEC/pull/1412. Some of these discrepancies may require discussion. Here's a probably incomplete list:

* There are a few election categories included in the API that aren't currently listed in #118: convention, special primary, special convention, and whatever "R" means.
* The proposed API implementation is using more granular reporting deadline categories than listed in #118. The issue lists monthly, quarterly, etc., but the API lists February Monthly, April Quarterly, etc.
* I don't see webinars, state outreach workshops, or administrative review hearings in the database.
* The data include a "Conference" category and a "Conferences and Outreach" category. I'm not sure whether these should be considered a single category or two distinct categories, or how to surface them in the calendar view.

Paging @noahmanger and @LindsayYoung for discussion.

**Comment by noahmanger** [comment]
Thanks for flagging. Here's some thoughts:
- Convention, Special Convention and maybe "R" should be listed in a different filter as "Conventions", as to the user they're not actually "Elections". "Special primary" however should be part of "Elections"
- I think it's more useful to browse Monthly and Quarterly deadlines as the parent category. If you're a monthly or quarterly filer, you want to see everything applicable to you. Is there value to keeping the more precise categories? If so, maybe we need an additional field for "parent category" or seomthing
- Not sure what to do about those missing events. They're on the existing FEC calendar, so hopefully we can get them.
- Do you have examples of what's included in "Conference" and "conferences and outreach"? They might be part of the the webinars and outreach workshops that are missing.

**Comment by jmcarp** [comment]
> I think it's more useful to browse Monthly and Quarterly deadlines as the parent category.
There's a few options here. We could collapse all monthly filings into a single category in the API (and do the same for quarterly), or we could make the change on the frontend side and map a single checkbox ("Monthly") to many values ("M2", "M3", etc.). I think the first option is simpler, although it means we'd lose the ability to filter on finer-grained categories for this endpoint. Which is probably fine, since we'll direct users to different endpoints for more granular queries and data output anyhow.

> Do you have examples of what's included in "Conference" and "conferences and outreach"?

Conferences and Outreach:
```
fec=> select event_name from cal_event join cal_event_category using (cal_event_id) where cal_category_id = 22;
                                        event_name
-------------------------------------------------------------------------------------------
 Webinar for Trade Associations
 FECFile Webinar for PACs/Parties
 Member/Labor Webinar
 Seminar/Webinar for Campaigns & Political Party Committees
 Corporate Seminar/Webinar
 Trade/Member/Labor Seminar/Webinar
 Candidate 101: Preparing for the Next Election Cycle Webinar
 Test Conference
 Nonconnected PAC Seminar
 Party Committee Seminar
 Candidate Seminar
 Campaigns/Party Seminar/Webinar
 Seminar/Webinar for Trade Associations, Membership and Labor Organizations and their PACs
 Candidate-Party Seminar/Webinar
 2012 Year-End Reporting Roundtables & Webinars for PACs & Parties
(15 rows)
```

Conferences:
```
fec=> select event_name from cal_event join cal_event_category using (cal_event_id) where cal_category_id = 33 limit 20;
                                        event_name
-------------------------------------------------------------------------------------------
 Nonconnected Committees Seminar
 Registration Deadline -San Diego Conference
 Conference for Campaigns & Political Party Committees - Final Day
 Conference for Campaigns and Political Party Committees Continues
 Conference - San Diego
 Trade Assoc, Membership Org Conference
 Deadline - Conference Registration
 Conference for Campaigns and Political Party Committees
 Conference - San Diego
 Trade/Membership/Labor Conference
 Seminar/Webinar for Trade Associations, Membership and Labor Organizations and their PACs
 Corporate Webinar
 San Diego Regional Conference
 Chicago Regional Conference
 DC Candidate/Party Conference
 Tampa Regional Conference
 Conference for Corporations & Their PACs
 Nonconnected Seminar
 Conference for Corporations
 Conference for Corporations
```

**Comment by LindsayYoung** [comment]
For a presidential election, the national party conventions are elections were delegates cast votes to determine who win's the party's nomination for the ballot. That is an election, with a increasingly small risk that it will not be determined with strict primary results. (Checkout [faithless electors](https://en.wikipedia.org/wiki/Faithless_elector) if you want to go down the election possibility rabbit hole.) We don't need election in their short title, but they are elections that determine who is on the ballot.

**Comment by jmcarp** [comment]
To keep this moving: how do you all feel about collapsing categories for M2, M3, etc. into monthly, Q1, Q2 into quarterly, etc? This is one way to get the filter categories that @noahmanger mentioned above.

@noahmanger @LindsayYoung

**Comment by noahmanger** [comment]
Yep, I think that makes more sense than having a single checkbox that actually triggers multiple filters.

**Comment by LindsayYoung** [comment]
We could also do this in the API query, to filter for monthly, we could just ask for the relevant filing deadlines. That is how I imagined we would deal with it, but we never talked about it. Happy to concider doing it the other way.

**Comment by noahmanger** [comment]
Ok, and on the last point on webinars, state outreach workshops, or administrative review hearings:

I didn't realize that these weren't individually categorized. It looks like the "Conferences" and "Conferences and outreach' tables above contain everything we need for the first two, so maybe just have one filter that's "Conferences and outreach" or "Conferences and training" --> @emileighoutlaw ?

Looking back over that issue, "Administrative review hearings" seem to just be another instance of "Commission meetings". So maybe we don't need to be able to filter by them. --> @amykort

**Comment by emileighoutlaw** [comment]
Outreach sounds more like marketing and press. So I prefer "Conferences and trainings"

**Comment by noahmanger** [comment]
Looking back over this, it looks like we're still missing some dates (either in the API or on the frontend, I'm not sure) or have mis-matches with what we originally planned for. I've highlighted discrpenacies in orange:

![screen shot 2016-01-04 at 11 04 08 am](https://cloud.githubusercontent.com/assets/1696495/12097834/e849479c-b2d2-11e5-8e75-b52a854f3276.png)

On some of these, it's ok if we diverged because the data just isn't there (e.g. if the outreach events just aren't as narrowly categorized). But the big ones that we seem to be missing are 24 / 48 hour reporting periods and all of the rule making. 

Are those events contained under a different category? Or are we missing the data all together?

**Comment by noahmanger** [comment]
Also, on the question of state primary conventions, can / should we categorize those as primary elections? For example, the March 26 Dem convention in Alaska and Washington.

**Comment by AmyKort** [comment]
A couple of thoughts: We're in the process of finalizing the compliance pages and the current calendar to cover 2016 reporting dates. I expect this information to be on the FEC website by the end of next week. Presidential election years are tricky. I think having access to the updated Commissioner Calendar and Compliance pages will answer a lot of these questions for us, including which conventions count as elections (whether they are primary elections, run-off elections, etc.) and the various reporting dates and compliance periods that go with each of those elections. Some states hold primaries, some hold caucuses, some hold conventions. Many states hold more than one of these during a Presidential election year. We want to capture the ones with reporting and compliance requirements--we can grab that off the compliance map as soon as the map is up. Whether to specifically label them as caucuses or conventions is a semantic issue for us. Under FECA, they have reporting requirements because they are considered elections.

As far as the conferences tab goes: We've used conferences and outreach forever, or educational outreach. We have a pretty regular customer base for those activities. I think we should hold onto the outreach language.

Administrative Review Hearings are essentially just Hearings--for rulemakings, generally, under the Administrative Procedure Act. So, let's just call them Hearings. Those are scheduled as they come up.

**Comment by noahmanger** [comment]
Closing in favor of tracking all date data questions here: https://github.com/18F/openFEC/issues/1441
