### ISSUE TITLE
Implement calendar styles

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#175]
Brain dump of things that need to happen for the calendar, based on [this mockup](https://cloud.githubusercontent.com/assets/11636908/11618829/f3b3b124-9c6d-11e5-81ab-80c8dfffc27b.png):
- [x] Set filter panel to adjust height to be full height
- [x] Make all rows in the month view the same height
- [x] Style other views
- [x] Style calendar control buttons
- [x] Create dropdown component for subscription / download buttons
- [x] Set limit on number of events show in a day
- [x] Show full text of event on click
- [x] Implement color coding in checkboxes and events
- [x] Add "clear filter"
- [x] Add push state for filters
- [x] Add event limit popup

**Comment by jmcarp** [comment]
Do the mocks include behaviors for max events per day and showing event details on click? I can cap the number of events in a day and add an "n more" widget, but what happens when you click "n more"? Similar question for event details--we can add click listeners on event widgets, but where would we show details on click?

**Comment by noahmanger** [comment]
FullCalendar apparently has [event limiting](http://fullcalendar.io/docs/display/eventLimit/) but I wasn't able to get it to work yesterday. I think using their default "popover" interaction for now will work.

As for viewing event details on click, can you set it to append a div with all the info for that event, and then when @jenniferthibault has time to design it we can figure out exactly how we want it to look.

**Comment by noahmanger** [comment]
Ok, this is coming along pretty nicely. I have the widget areas styled:

![screen shot 2015-12-24 at 12 57 02 pm](https://cloud.githubusercontent.com/assets/1696495/11997856/fa5bfe90-aa3d-11e5-8711-16ddab12d3f3.png)

I can't remember if we've discussed doing usability testing on the 30th, but if anyone's around and wants to, I think this is in a decent place to do some initial tests with.

**Comment by jenniferthibault** [comment]
@noahmanger I think we might we want to integrate the color-coding before testing. I mean, it's not critical, but it does help parse information, so if we waited for that we wouldn't need to test again after, necessarily, just because we added it in. Does that make sense? 

@jmcarp Here's a few mockups of the event limiting interaction. Could we try limiting to 3 events per day, then adding a `+ # more` toggle? This interaction closely mirrors the full calendar default interaction, with the exception of keeping full-day events color blocked but specific-timed events as standard text.

**Showing event cutoff**
<img width="701" alt="screen shot 2015-12-28 at 3 32 56 pm" src="https://cloud.githubusercontent.com/assets/11636908/12025845/d45f7e88-ad80-11e5-8308-39d4c6933bb9.png">


**Showing when the user selects `+ 2 more`**
<img width="728" alt="screen shot 2015-12-28 at 3 57 50 pm" src="https://cloud.githubusercontent.com/assets/11636908/12025848/d9dbe374-ad80-11e5-90f2-ef0163712594.png">

The event detail preview would use the tooltip style. The "Full event details" would take you to an individual event page for events that have that info. If not, the link would not appear. 

Here's what that would look like over an event in an overflow container:
<img width="723" alt="screen shot 2015-12-28 at 4 32 58 pm" src="https://cloud.githubusercontent.com/assets/11636908/12025899/4ab86996-ad81-11e5-83a0-b519ee9496e4.png">

And with a multiple full day event:
<img width="725" alt="screen shot 2015-12-28 at 4 33 19 pm" src="https://cloud.githubusercontent.com/assets/11636908/12025900/4abd3b6a-ad81-11e5-808a-56fb9a788d7f.png">

**Comment by noahmanger** [comment]
Made some more progress on this:

![image](https://cloud.githubusercontent.com/assets/1696495/12057860/809432a0-af13-11e5-9718-1c21ebc2ebc2.png)

(Note, this doesn't include Jen's most recent tooltip style edits).

Still not ready for a true visual review, but wanted to share progress.

**Comment by noahmanger** [comment]
@jenniferthibault can you share the exact hex codes for the different colors you want to use? I just picked them out of the screenshot, but I know they can get messed up with that method.

**Comment by jenniferthibault** [comment]
HAYYYYYY! Looking nice!

Here's the colors I was using, which I tested for color contrast ratios. All have X:1 of greater than 4.5 with white text :+1: 

<img width="446" alt="screen shot 2015-12-06 at 11 15 25 pm" src="https://cloud.githubusercontent.com/assets/11636908/11618927/5418a2bc-9c6f-11e5-8a53-a8c5ce4cf6b4.png">

Green: #006A6A
Purple: #810082
Bright blue: #2B47DA
Dark blue: #12447C
Bright red/orange: #DB3100
Dark red: #961A16

**Comment by noahmanger** [comment]
It's coming together... 
![gif](http://g.recordit.co/evXCWq71LI.gif)

**Comment by jenniferthibault** [comment]
Nice work @noahmanger ! Let me know when you're ready for a design review and we can pair up. How we did it last time seemed to work really well.

**Comment by noahmanger** [comment]
These are merged in now.
