### ISSUE TITLE
Design menu option A--no submenu--for testing

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1763]
What we're after: We've learned from users that our menus for the data, legal resources and H4CC pages might not be as effective as we'd like in getting folks to the resources they need. We're going to try some A/B testing on alternatives to see if we can learn more about what works for users.

Option A will be to remove the submenu and send users directly to the landing page.

- [x] Create design for the no-submenu option

**Comment by patphongs** [comment]
This is currently what is prototyped in code. 3 main buckets: Campaign finance data, Help for candidates and committees, and Legal resources all do not have submenus. About menu retains its submenu due to the fact it is needed to call out other areas such as meetings, updates, and contact. 

![no-menu-design](https://user-images.githubusercontent.com/12799132/36044699-78f43434-0da1-11e8-98d4-f8c4833f2ac2.gif)

**Comment by patphongs** [comment]
I would say that this is good to go for testing @JonellaCulmer. Let me know if you see anything that needs tweaking before we test.

**Comment by jwchumley** [comment]
Already done
