### ISSUE TITLE
Identify each state's 2018 prior notice page link

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1765]
We're building a graphic overview of House and Senate races by district to help users get more comprehensive at-a-glance information about particular races. Part of this work includes offering compliance information for users who are participating in the election of have particular compliance questions about the election.

What we're after in this issue: We want to display appropriate state-level reporting date information associated with each race. We'll accomplish this by linking to the prior notice page for each state, as listed on our transition site. Step one is to:
- [x] identify the link to each 2018 prior notice page on the transition site
- [ ] create a list of state codes and the url the respective prior notice page

**Comment by dorothyyeager** [comment]
The inventory of the 2018 prior notice pages has been completed. There are a few states that have more than one prior notice page, however. In some cases, we are waiting on state party committees to tell us the dates of their nominating conventions, so those specific URLs are not yet available. To help us identify likely patterns, I've put in the URLs used for those in 2014 (the last non-presidential federal election year). The spreadsheet used for the inventory is available for viewing at https://docs.google.com/spreadsheets/d/1I0gQHwt5stHU8EX8a_oWXS7uwZFfrybC1A6cOjV2L3w/edit?usp=sharing

**Comment by AmyKort** [comment]
Thanks, @dorothyyeager ! It's really helpful to see all of this in one place. Are we ready to close this?

cc @patphongs and @JonellaCulmer

**Comment by dorothyyeager** [comment]
@AmyKort If how it's set up will work for the list of state codes and URLs, then yes! I have asked Kathy in Information to review it to make sure nothing was missed (other than the state party conventions we don't have 2018 URLs for yet). The big thing for @patphongs and @JonellaCulmer is that while most states only have one prior notice URL, there are quite a few states and territories that have multiple prior notice URLs because of the way they organize their elections. Tried to capture in the spreadsheet what was going on in each of those states.

**Comment by AmyKort** [comment]
Thanks, @dorothyyeager !
