### ISSUE TITLE
Add coverage time period to House/Senate race overview

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1767]
We're building a graphic overview of House and Senate races by district to help users get more comprehensive at-a-glance information about particular races. Part of this work includes offering compliance information for users who are participating in the election of have particular compliance questions about the election.

What we're after in this issue: We need to let users know what time period of data they're looking at. 
- [x] Add Two-year period (ex. 2017-2018) to design

**Comment by JonellaCulmer** [comment]
In order to make it more clear which election a data user was reading, we updated the design in-progress to include a two-year period dropdown date filter. This matches the current functionality of these election profile pages, and maintains the same filter pattern seen throughout the rest the data section.

<img width="314" alt="screen shot 2018-02-09 at 5 17 25 pm" src="https://user-images.githubusercontent.com/31663028/36052888-87d7fd20-0dbd-11e8-829f-dc72e8d4d2d4.png">

These designs will be tested at the Arizona conference.

**Comment by JonellaCulmer** [comment]
Closing in favor of testing issue: https://github.com/18F/fec-cms/issues/1769
