### ISSUE TITLE
Districts listed out of order on Election search results page - Dev space

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1782]
When displaying the search results for a state, the districts are out of order. We need to take a look at what kind of sort order is in the API

**Example:** https://fec-dev-proxy.app.cloud.gov/data/elections/?cycle=2018&state=AZ

**API Call:** https://fec-dev-api.app.cloud.gov/v1/elections/search/?api_key=DEMO_KEY&per_page=100&cycle=2018&state=AZ

- [X] Front-end fix
- [x] API fix

**Comment by lbeaufort** [comment]
It looks like it's related to the changes I made to use a new table with [this PR](https://github.com/18F/openFEC/commit/7a836fabcbe66a11c8f1ae5e43a28757d0fd7baa) 

Thank you for catching that, Pat. I could probably get a fix in before the release branch is cut, especially because Jun is cutting it in the afternoon. 

I should probably add an automated test for sort order - I think I was under the impression that the CMS sorted the house results by district.

**Comment by patphongs** [comment]
Thanks @lbeaufort, I think it is a good idea to have the CMS handle the sort in the API call. Since the API already handles sorting districts, I made a PR (#1783) to just handle the sort in the form submit itself rather than having to change any of the backend code. I added you as a reviewer, let me know if you have any questions.

**Comment by lbeaufort** [comment]
I'm removing the "high priority" label because we have a short-term workaround on the front end side that's already been implemented.

**Comment by lbeaufort** [comment]
API fix merged: https://github.com/18F/openFEC/pull/2936
