### ISSUE TITLE
Statements of candidacy prior to 2000 not showing up

### ISSUE THREAD

**Issue by JonellaCulmer** [18F/fec-cms#1825]
User feedback received via email:

> clicking on a candidate's statement of candidacy for the election cycle 1993-1994 the links redirect to an error message. Have a great day!

Since a candidate wasn't specified in the request I tried to find a candidate with many years going back to see at what point there's a breakdown. After looking at [John McCain](https://www.fec.gov/data/candidate/S6AZ00019/?tab=about-candidate&cycle=1992&election_full=true), and a few others, it looks like there aren't any statements of candidacy prior to 2000 showing up. 

cc: @PaulClark2

**Comment by PaulClark2** [comment]
@JonellaCulmer the information below is on classic, https://classic.fec.gov/finance/disclosure/help_candidate_committee_viewer.shtml, but doesn't seem to have made to the new site.  Public Records is in the process of scanning all older documents, but I don't know when we will be ready to upload those images to docquery.

We currently scan all paper reports received at the Federal Election Commission. This includes reports filed by campaigns for the House of Representatives and for President, along with reports by political party committees and political action committees who participate in Federal elections. Scanned images of reports filed with the Secretary of the Senate are included here as well.

Older paper reports are available with the following limitations.
PAC, party and presidential filings since 1993
House committee filings since May 1996
Senate filings since May 2000

You will also see miscellaneous correspondence between the FEC and committees in cases where there are questions about information included in reports or where committees want to clarify what they have reported.

**Comment by JonellaCulmer** [comment]
Thanks, Paul. I'll pass that information along. Closing this issue.
