### ISSUE TITLE
On Registration Home, Confusion between button copy

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-cms#19]
Explore your registration options
and 
Start your registration process »

Go to the same place, but it was not apparent that they would to users. 

This is a design/content question, but I'm not sure how to make those labels so instead just tagging @emileighoutlaw and @noahmanger and @jenniferthibault 
![screen shot 2015-08-21 at 6 48 32 pm](https://cloud.githubusercontent.com/assets/474916/9420639/d6e3b3aa-4835-11e5-92d2-9af0a5a1fa0c.png)

**Comment by jenniferthibault** [comment]
@emileighoutlaw what is your thoughts on language for these two buttons that go to Registration Options page?

**Comment by emileighoutlaw** [comment]
Interesting question— buttons do seem like different options. Each speaks to a different and important piece of content on the essentials page. Maybe an ideal button would include both pieces? Something like:

"Explore your options or register"
"Explore your options and register"

**Comment by emileighoutlaw** [comment]
Thanks for brining this back up @jenniferthibault ! We had talked about trying out making both buttons say "Explore registration and reporting". We'll see how that works.

**Comment by jenniferthibault** [comment]
Hate to be the negative Nancy, @emileighoutlaw  but I'm not sure that really gives users a clear picture of where that button takes them—can we be more direct and helpful?

**Comment by emileighoutlaw** [comment]
Not to worry @jenniferthibault. Happy to discuss further.

If I remember the user testing sessions correctly, the confusion was:
1. The links had different text but went to the same place.
2. Folks who used the site primarily for research didn't want to click an "options" button, because they felt it applied only to those people who actually wanted to register.
3. It wasn't clear the link went to both registration *and* reporting info.

We could do something like 
"Explore registration and reporting options and essentials"
"Registration and reporting options and essentials"

Does that feel more direct and helpful? Other thoughts?
