### ISSUE TITLE
Fonts vary on checklist page (bug?)

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#193]
Editing the checklist today, I noticed some of the words look like they're different fonts? 

<img width="796" alt="screen shot 2016-02-02 at 9 54 19 am" src="https://cloud.githubusercontent.com/assets/10552702/12753963/433180e0-c997-11e5-8de8-06e95803769b.png">

I looked at the code, but it doesn't seem like anything wonky is going on, so I'm not sure what to make of it. 

For example, here's the `<li>` for Pre-election reports.

              <li><a href="/registration-and-reporting/pre-election-reports/">Pre-election reports</a></li>

cc @noahmanger @jenniferthibault

**Comment by jenniferthibault** [comment]
What browser are you on @emileighoutlaw ? I'm trying to recreate the issue.

**Comment by jenniferthibault** [comment]
This is the weirdest thing. I couldn't recreate this on my end in Safari/Firefox/Chrome, but Screenhero-d Emileigh to see what was going on. EVEN WEIRDER, the issue was recreated on a different word this time, and NOT on the Regular filing section.

@noahmanger check out `Contact` us below:

<img width="497" alt="screen shot 2016-02-02 at 10 54 25 am" src="https://cloud.githubusercontent.com/assets/11636908/12755062/e50df52a-c99b-11e5-930f-46d00d4e3323.png">

Here's the inspector for it: everything is wrapped in one tag, but it looks like the `font-family: "ghandi",  serif;` is being overwritten by something?

<img width="597" alt="screen shot 2016-02-02 at 10 54 31 am" src="https://cloud.githubusercontent.com/assets/11636908/12755065/e991d1c0-c99b-11e5-99cd-87d74d05f905.png">

**Comment by jenniferthibault** [comment]
This has also been reported here, but none of us could see it. There's definitely some bug in here. https://github.com/18F/FEC/issues/215

**Comment by jenniferthibault** [comment]
I'm seeing A LOT of this right now on the registration side. Karla is being replaced by default sans-serif in almost every instance unless it's text that's under focus state:

<img width="264" alt="screen shot 2016-02-24 at 3 33 12 pm" src="https://cloud.githubusercontent.com/assets/11636908/13300017/0a1a879e-db0c-11e5-8850-c7301099d910.png">

<img width="1278" alt="screen shot 2016-02-24 at 3 32 52 pm" src="https://cloud.githubusercontent.com/assets/11636908/13300019/0f71a93e-db0c-11e5-989a-ffa7860108b6.png">

**Comment by noahmanger** [comment]
Weeeeeird. Ok, I'll look into it.

On Wed, Feb 24, 2016 at 12:34 PM, Jennifer Thibault <
notifications@github.com> wrote:

> I'm seeing A LOT of this right now on the registration side. Karla is
> being replaced by default sans-serif in almost every instance unless it's
> text that's under focus state:
>
> [image: screen shot 2016-02-24 at 3 33 12 pm]
> <https://cloud.githubusercontent.com/assets/11636908/13300017/0a1a879e-db0c-11e5-8850-c7301099d910.png>
>
> [image: screen shot 2016-02-24 at 3 32 52 pm]
> <https://cloud.githubusercontent.com/assets/11636908/13300019/0f71a93e-db0c-11e5-989a-ffa7860108b6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/fec-cms/issues/193#issuecomment-188443635>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
Very strange. One suggestion from Slack is this may be a caching issue. I'm not able to replicate this right now, but I've definitely seen it.

**Comment by noahmanger** [comment]
I haven't seen this in a long time, so I'm closing.
