### ISSUE TITLE
Order events based on category

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#199]
We want to have events from the categories `Open Meetings`, `Executive Sessions`, and `AOs and Rules` show up first on the calendar above all others. Beyond those, I don't believe it matters.

**Comment by jmcarp** [comment]
The `fullcalendar` library includes an `eventOrder` option that allows for custom event sorting, but only to break ties between events that happen at the same time. To be concrete, here's how `fullcalendar` sorting works:

* Earlier events first
* If tied, longer events first
* If tied, all-day events first
* If tied, apply user-defined ordering

In other words, setting `eventOrder` doesn't guarantee that `Open Meetings` always go first within a day--just that they appear before other events with the same time and duration. If this is the desired behavior, then I'll submit a patch setting `eventOrder`. If not, I'll try monkey-patching some internal methods of the `Grid` class. I think using `eventOrder` would make more sense, because monkey-patching is ugly, and because I'd guess users expect to see events in a calendar sorted by time.

Here's the relevant code in `fullcalendar`: https://github.com/fullcalendar/fullcalendar/blob/554532aff193dec5599199f736241f299c057f2b/src/common/Grid.events.js#L942-L948

@noahmanger

**Comment by PaulClark2** [comment]
@noahmanger the order you describe above is correct.  I understand what @jmcarp explains about the `eventOrder`.   If creating a patch to override the `eventOrder` will cause problems perhaps we go with `eventOrder` only for now and figure out a better solution.   @ChristianHilland

**Comment by noahmanger** [comment]
So I think the only time when this will be confusing is if there is ever an event that isn't one of those categories that is scheduled to take place _before_ one of the prioritized events. i.e. If there's a webinar at 9am and a commission meeting at 11am, and the commission meeting shows up first.

As it is now, the "all day" events like deadlines have a "start time" of midnight of that day, which is why they show up before events of any other time.

I'm wondering if we might thread this needle simply by ordering all day events below events with specific start times, rather than prioritizing specific categories.

**Comment by ChristianHilland** [comment]
That makes sense to me.

**Comment by PaulClark2** [comment]
I agree.  That seems like a reasonable solution.

**Comment by noahmanger** [comment]
This is resolved. Thanks, Josh.
