### ISSUE TITLE
Fix calendar tooltip alignment 

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#200]
Currently calendar tooltips on the right-most column are cut off by the edge of the page:

![calendar](https://cloud.githubusercontent.com/assets/1696495/13086447/20705778-d498-11e5-9fb9-8f6d254784c3.png)

The simplest solution would be to just align the right edge of the tooltip with the right edge of the event cell, but this means that events on the left would have the tooltip overlap with the filters, though I think this is ok:
![screen shot 2016-02-16 at 10 31 19 am](https://cloud.githubusercontent.com/assets/1696495/13086560/90bf7194-d498-11e5-94c8-9f5eb542a00c.png)
![screen shot 2016-02-16 at 10 31 25 am](https://cloud.githubusercontent.com/assets/1696495/13086564/93838d98-d498-11e5-9ec3-b77299a025bd.png)

**Comment by noahmanger** [comment]
Ping @jenniferthibault for thoughts.

**Comment by jenniferthibault** [comment]
Ideally, it would be cool if events on the left and right could have different tooltip placements, so that on the left, it doesn't overlap the filters, and on the right, it doesn't run off the edge. I could definitely see how that adds bulk to styling though, and might be hard to predict.

Unless you can think of a good solution that would enable the above, I'm :+1: with what you have mocked up above @noahmanger 

One thing is sticking out to me on your screen shots though, there seems to be some mystery text overlap. 
<img width="235" alt="screen shot 2016-02-16 at 1 40 53 pm" src="https://cloud.githubusercontent.com/assets/11636908/13086816/ed87fbca-d4b2-11e5-9f23-1356eb110ae3.png">


Is that just a local instance glitch? I'm not seeing it on the proxy site.

**Comment by noahmanger** [comment]
Ok! I found a pretty simple way to align them differently _just_ for events on the last day of the week and fixed the text overlap:

<img width="458" alt="screen shot 2016-02-16 at 4 49 01 pm" src="https://cloud.githubusercontent.com/assets/1696495/13096297/48d39a7e-d4cd-11e5-93c6-043b5d5680e8.png">
<img width="361" alt="screen shot 2016-02-16 at 4 48 58 pm" src="https://cloud.githubusercontent.com/assets/1696495/13096296/48d3ca9e-d4cd-11e5-9ad3-866e5b27f041.png">

Implemented in the latest calendar patch.

**Comment by jenniferthibault** [comment]
@noahmanger you are a wizard. :crystal_ball:
