### ISSUE TITLE
SSF content:  link questions

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#250]
- [ ] https://beta.fec.gov/registration-and-reporting/ssf-election-year-filing/
Should "Quarterly filers," "Monthly filers" and "Independent expenditures" be links? 

- [ ] https://beta.fec.gov/registration-and-reporting/quarterly-filers/
Form 3X hyperlink takes users to form instructions not the filing form, is this correct?   

- [ ] https://beta.fec.gov/registration-and-reporting/monthly-filers/
Form 3X hyperlink takes users to form instructions not the filing form, is this correct?   

- [ ] https://beta.fec.gov/registration-and-reporting/ssf-non-election-year-filing/
Should "Semi-annual filers" and "Monthly filers" be links? 

- [ ] https://beta.fec.gov/registration-and-reporting/non-election-monthly-filers/
Form 3X hyperlink takes users to form instructions not the filing form, is this correct?

- [ ] https://beta.fec.gov/registration-and-reporting/semi-annual-filers/
Form 3X hyperlink takes users to form instructions not the filing form, is this correct?

@emileighoutlaw @amykort

**Comment by AmyKort** [comment]
In places where the hyperlink goes to the form instructions rather than the form, I don't know how to best serve our users. The links should go straight to the form, because that is what you are trying to click on--we should make that change. But, sending the user straight to the form from these pages potentially means that the user never knows she could have referenced instructions. Can we have the link to the form and then another link that is *(instructions)*?

**Comment by emileighoutlaw** [comment]
How about this: I'm going to change the sentence below the table to say:

"Access the Form 3X and step-by-step instructions."

I'll make "Form 3X" a link to the form and "instructions" a link to the
instructions. Then I'll take the hyperlinks out of the table?

Sound good?

(Also, good catch on the inter-page linking. That's fixed now.)


Best,
Emileigh

**Comment by AmyKort** [comment]
I like it. Thank you!

**Comment by noahmanger** [comment]
Did we make these changes?

**Comment by emileighoutlaw** [comment]
Yes! All changed. Closing now.
