### ISSUE TITLE
Calendar Weekday/Weekend distinction

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-cms#264]
At first glance something about the calendar (on proxy) doesn't read instantly as "CALENDAR" to me.  I think...

First, there is no weekend  indicator. Could you do something to the Saturday and Sunday columns to make them visually distinct from Monday through Friday? 

Second, would it read better if the first column was Monday and the last was Sunday so the weekend days would be adjacent?

**Comment by jenniferthibault** [comment]
@jwchumley doing a little cleaning of old visual design issues—since the calendar default is now the list view and only shows days with events on them (therefore, no weekends) do you still think this interferes with the experience?

![screen shot 2017-04-26 at 3 19 16 pm](https://cloud.githubusercontent.com/assets/11636908/25459594/ce2e5714-2a93-11e7-9960-c0869e05a7e2.png)

**Comment by jenniferthibault** [comment]
Closing this issue, given that we haven't heard any similar feedback with the new format
