### ISSUE TITLE
Unify registration and reporting landing blurbs

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#299]
The intro blurbs on our registration and reporting landing page are a little inconsistent.

![screen shot 2016-05-17 at 11 55 57 am](https://cloud.githubusercontent.com/assets/10552702/15329349/6318a23a-1c26-11e6-83ad-eb753469e823.png)

![screen shot 2016-05-17 at 11 56 04 am](https://cloud.githubusercontent.com/assets/10552702/15329352/66803d98-1c26-11e6-8ae5-d1881734e3d7.png)

![screen shot 2016-05-17 at 11 56 10 am](https://cloud.githubusercontent.com/assets/10552702/15329356/69fa694e-1c26-11e6-9cfa-43636c2eadae.png)

Candidates and committees and SSFs talk about _what the registrant is_. The political party intro blurb talks about _how to register_. 

For this page to be consistent and make sense, I think we need to consider moving the political party intro as it currently exists onto the registration checklist page. Then we'll want to write a new blurb about what political parties _are_ for the main page. This probably won't be super fun, but I think it's important. 

@amykort @amypike, do you have thoughts on this?

**Comment by AmyKort** [comment]
Okay, so we've been back and forth on this issue on our end for a while now without coming to a consensus about the best way forward. What if we wait until we've finished the content for this page and then see where we're at? Is that terrible? 

Because maybe this is just too many words on a page anyway, and we need really short headers or something by the time we're done. ???

Also, seeing the whole puzzle might help make the picture clearer for us.

**Comment by emileighoutlaw** [comment]
Sure thing. I'll take it out of this sprint, and we'll circle back around to it!

**Comment by emileighoutlaw** [comment]
Okay! It's been awhile since we talked about this, but I've been thinking about it lots and working on it between content migration tasks.

So here we are today, and I have a proposal for a better unified landing page. It's a Google Doc, that I've shared specifically with @amykort and @amypike. Access that [Google Document here](https://docs.google.com/document/d/1GErIVb5bAB17tGuy49WVXt144VPy07v39wvv04ioZUQ/edit?ts=57969390#).

I can easily turn this into a Word Document to share around, but I think it's be easier for the three of us to do the first review asynchronously in one document. I'd love to hear what you think of this, Amys.

**Comment by emileighoutlaw** [comment]
Hey @AmyKort ! I let this fall of our radar, but I think this would be a great thing for us to think about. Are you able to check out that Google Doc, or should share in another format? (I can send it over as a Word Doc 😃 )

**Comment by AmyKort** [comment]
I read the document. The rewrite works better as a page because it's internally consistent, but if we do it this way we aren't being consistent with the actual statutory and regulatory definitions and requirements. Even the revision to the header at the top of the page is problematic. Let's talk about this.

**Comment by emileighoutlaw** [comment]
Sounds good! I'll set up a time for us to talk!

**Comment by emileighoutlaw** [comment]
I just had a great chat with Amy about this! The problem with making these introductory blurbs parallel is that it assumes a parallel system exists for the different registrant types, which _it does not_. These are uneven, because they mirror the law. We can certainly ask OGC to help us make this _better_, but that would mean pulling their gaze away from other migration work, which we don't want to do. So I'm going to move this to the Icebox for now.

**Comment by emileighoutlaw** [comment]
This was addressed when we re-did our "Candidate and committees services" home. Closing now.
