### ISSUE TITLE
Find home for FEC brochures

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#387]
This one is cc @jenniferthibault, @noahmanger, and possibly @onezerojeremy 

Brain dump alert. Also alert that I've been putting this issue off because it's hard for me. But here's a first stab. Open to all challenges of my assumptions and ideas!

The FEC has a number of Commission-approved brochures, which contain valuable information. For each brochure we need to either: 
- Deprecate, if all the content has been covered on our new `Registration and reporting` checklists 
- Find a new home within `Registration and reporting`

# What to do
## Deprecating brochures
In preliminary discussions, FEC has been firm that they aren't willing to get rid of these brochures; they view them as a very important piece of the migration. I'd still like to argue that we don't transfer brochures that are duplicative (one of our main migration goals is one piece of content = only one place).

## Re-homing brochures
There are a couple different questions to think about for finding a `Registration and reporting` home for brochures. 

- Where will brochures live within the information architecture?
- What will they look like? 

#### Where will brochures live within the information architecture?
A few places, I think.

1. We'll want to link to them as "Additional resources" within individual checklist pages:
<img width="274" alt="screen shot 2016-06-24 at 1 59 32 pm" src="https://cloud.githubusercontent.com/assets/10552702/16346167/eb250424-3a13-11e6-9b2b-9516fa5934fa.png">
2. We'll also want them within the "checklist" hierarchy. I see a couple options for this. 

- **We could include them** _inside_ the categories that already exist (maybe we have some kind of visual indicator that they're a different content type?)

<img width="391" alt="screen shot 2016-06-24 at 1 56 11 pm" src="https://cloud.githubusercontent.com/assets/10552702/16346078/80bae11c-3a13-11e6-88e4-6bcdc7eb1d9c.png">

- **We could create a new checklist category** for supporting publications (which could later be expanded to include cross-linked to Record articles, etc.):
<img width="483" alt="screen shot 2016-06-24 at 1 50 50 pm" src="https://cloud.githubusercontent.com/assets/10552702/16346095/94a332e2-3a13-11e6-80b5-f2b8845e9fc8.png">

#### What will they look like?
Because "brochures" are a different content type than our essentials pages, I was imagining we'd want to give them a slightly different look and feel than we give the essentials checklist pages. But that's a question for @jenniferthibault. Here's what they look like now (nothing in particular design-wise):

<img width="978" alt="screen shot 2016-06-24 at 1 39 10 pm" src="https://cloud.githubusercontent.com/assets/10552702/16345773/bbe3f50a-3a11-11e6-8f69-57cb6674d2db.png">

# The brochures
And here's what they actually are (lots of this is for me to keep track of and talk to Amys about next week), divided by audience:

**For candidates**
- Committee treasurers
- Candidate registration (deprecate)
- Testing the waters

**For party committees**
- Local party activity

**For volunteers** 
_(This section isn't drafted, so it's hard to say for sure if either of these can be deprecated)_
- Citizens’ Guide 
- Volunteer activity 

**For more than one registrant types**
- Contributions
- SSFs and Nonconnected PACs
- Sale and use of campaign information
- Coordinated communications and independent expenditures _(I'm iffy on this one because it covers a huge amount of content, including reporting)_
- Electioneering communications _(I'm iffy on this one because it covers a huge amount of content, including reporting)_
- Partnerships _(I'm iffy on this one because it covers a huge amount of content, including reporting)_

**Not about registration and reporting** (and thus can be ignored right now)
- Filing a complaint
- Foreign Nationals 
- Reports Analysis Division (deprecate)
- The $3 tax checkoff
- Special notices on political ads and solicitations
- Internet communication and activity
- FEC rules for national convention delegates
- Public funding of presidential elections
- FEC and federal campaign finance law
- Federal and state campaign finance law
- Compliance with laws outside FEC’s jurisdiction
- Joint fundraising

**Comment by noahmanger** [comment]
Good questions. Some passing thoughts:

Does this information need to live in PDF form? Or for some of them could we extract it to regular pages? If they're PDFs, do they need the intro HTML page? Does that content need to stay the same, or can that be edited?

If it has to live in a PDF, then I think your first suggestion of linking to them from within the section where they're applicable + giving them a special style is good. This stays true to the original goal of the checklist page, which is to give people a sense of confidence in seeing a complete list of what they need to do and the order they need to do it. For that reason, I think it's better to have them in-context, rather than grouped together at the end. 

If we need to have PDFs we should still try to organize content by it's...er...content, rather than by the form it takes, imo.

**Comment by emileighoutlaw** [comment]
Those are all really good points. So most of these documents exist as both a PDF and an HTML, but there's no reason they need to stay a PDF. I believe we can turn them all into Wagtail pages. 

Calling these things "brochures" has been important in the past, because at the FEC "brochures" are a specific type of content that has been approved by the Commission. They're a rare bird. Because they're Commission approved, we can't change any of the content. But it might be possible to change what we call them or how we categorize them? 

@AmyKort understands this more than I do, so maybe she can weigh in when she isn't playing catch-up from vacation.

**Comment by noahmanger** [comment]
Interesting. One "yes and" approach might be to turn them all into HTML pages and a) link to the PDF from the page, and b) give them some special kind of visual designation.

**Comment by AmyKort** [comment]
So, "deprecated." What exactly do we mean by that? Resorting to Google: "Another important thing to remember is that if some code feature is deprecated, it really is just a status, or a label, applied to that code by the creators of that software to indicate that it should not be used. It doesn’t mean that deprecated software will behave any differently from software that is not labeled as deprecated." If we don't migrate a brochure, what eventually happens to it?

I think we should sit down and think through what "one piece of content, one place" means. If the Commission issues an advisory opinion, then that opinion is on the website. The agency summarizes the opinion in the FEC Record and, in a more truncated fashion, in a press release. Those are both on the website. The guidance provided in the AO will be incorporated into campaign guides and other information provided to the public. It may appear in the instructions for reporting forms. These will be on the website. The guidance is the same in each place. The communication of that guidance is different because it serves a different function: I am filing a form and need to know how. I am undertaking an activity and need to know how. I am trying to get oriented with a to-do list, and I need to know what boxes to tic. I am submitting a petition for rulemaking and need to describe the current state of the law. Are we saying that we can only provide the guidance once irrespective of what the function of the communication is?

For the brochures, I think it's fine to provide them in HTML rather than as pdfs. I don't think it would be a significant issue to call them something else (rather than brochures). I think we have them as pdfs now because they're short and people want to print them out (at least they used to). Maybe that's not a current need. I am hesitant to say that we don't need a brochure anymore. I feel like that's taking away a resources that's helpful to folks.

When we're looking at the brochures, can we also take a look at the YouTube videos, etc. that go with particular content? I feel like those should migrate together.

Let's talk too about the Record and making that content more accessible to people. A lot of that content will be related to the registration categories we've established.

**Comment by emileighoutlaw** [comment]
Hey @amykort! You're spot on to ask how "one content one place" applies across content types. Thankfully, this is something that folks smarter than me have thought about and have great answers (and realistic solutions) for. It's a bit more of a content theory question (an important one!), and I think it merits a separate issue. I'm writing one up here: https://github.com/18F/fec-cms/issues/392. I'll ping you when I've collected my thoughts, and we can discuss!

# Continued brochure discussion

### Deprecation
This is my fault for not being more specific. The brochures I marked as possibly for deprecation are brochures that — to my thinking — should either be unpublished or archived (more on those two concepts in a sec!). In this case, the questions I've been thinking about are: 
- Is the information is _fully covered_ in our `Registration and reporting` content? If so, what's the benefit to additionally covering it in a brochure? How is the brochure different? 
- Is the information _mostly covered_ by our `Registration and reporting`  content? If so, is there a way we can add those last bits of outstanding information into our existing registration and reporting pages or other sections of the website? If we can, what's the benefit to additionally covering it in a brochure? 

These are our options for deprecation:
- **Unpublishing** removes a piece of content from the site. Usually I recommend this when the content has been thoroughly covered elsewhere. 
- **Archiving** keeps content on the website but clearly indicates that it's no longer being updated. That can look something like this:

![52d56226c6ba5dbf34000015](https://cloud.githubusercontent.com/assets/10552702/16784972/4d7eeb5a-4840-11e6-936a-c0b13c65e919.jpeg)
**Picture above:** This is GOV.UK. On archived pages they include a banner that says when content was archived and why. This page is super specific, but, it might be possible for us say something like _"This content was archived as part of the FEC.gov redesign on July 11, 2016 and is no longer being updated."_

Our archive process _might be_:
- Find a place in the new website's information hierarchy where archived content can live (perhaps in the "Library"?)
- Make a Wagtail CMS page for each piece of archived content (this also forces us to think strategically about what we really need to archive and what to unpublish)

### PDF vs. HTML
As long as people can `file > print` the HTML without formatting issues, I think it'd be fine to convert these to HTML pages in the CMS, @noahmanger. I do think they're a special content type and should have some sort of visual designation as such.


### Emileigh to dos:
- [ ] Open GitHub issue for Record cross-linking to registration and reporting
- [ ] Open GitHub issue for Youtube videos
- [ ] Open GitHub issue to start thinking about what our FEC content types are

**Comment by emileighoutlaw** [comment]
I'm going to move this back to the backlog — we're focusing on creating templates for our library section of the website first— we'll come back to this soon.

**Comment by emileighoutlaw** [comment]
This can be closed because it fits neatly into our IA work.
