### ISSUE TITLE
Apply printer-friendly styles to registration and reporting

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#446]
We have clear signals from research, users, and stakeholders that printer-friendly pages are important for betaFEC. Ensuring `Registration and reporting` pages are printer friendly will allow us to eliminate redundant PDFs documents. 

This is a front end task.

To do:
- [ ] Applying printer-friendly styles to `Registration and reporting` pages.

cc @noahmanger @jenniferthibault @xtine

**Comment by noahmanger** [comment]
@amykort sorry again for the delay, but here's a proof-of-concept for how printer styles can be implemented: 
- [Quarterly reports | FEC.pdf](https://github.com/18F/fec-cms/files/443744/Quarterly.reports.FEC.pdf)
- [Essentials for House and Senate candidates and committees | FEC.pdf](https://github.com/18F/fec-cms/files/443747/Essentials.for.House.and.Senate.candidates.and.committees.FEC.pdf)

We can discuss more what we'd like it to do, but for the purposes of this demo I:
- Removed the header, footer, and any sidebar or auxiliary content
- Removed the little book icons from glossary terms

Pretty simple stuff really, but does ensure that the pages print without extraneous stuff that you don't need on the printed page.

What do you think?

**Comment by jenniferthibault** [comment]
@noahmanger I'm not sure if this is the right time/place for design feedback of this sort, or if that comes later, but on a quick review, two thoughts:
- I'd be interested to hear more about leaving out the header entirely. Eliminating the header eliminates the primary source of FEC branding. What do you think about a simplified header on the first page of the printout so that it retains basic FEC brand recognition?
- For wayfinding, it also seems like it would be helpful to keep the breadcrumbs (which would be easy if we are keeping some header element) so that there are contextual hints of what part of the site someone is looking at, and where how they might be able to get back to it. Thoughts?

**Comment by LindsayYoung** [comment]
¢  ¢ 
I like the idea that we could add a minimalist print header - I think that is what you were suggesting, Jenn. The breadcrumbs idea is a great suggestion too.

**Comment by noahmanger** [comment]
Cool cool. Yeah I'd agree on both fronts. In my 5 minutes of work on this, I had trouble getting things to display right, so just left them off, but I'm sure we could get something like that going.

**Comment by AmyKort** [comment]
I think the printer friendly versions generally look great. One question--and I think this is what Lindsay and Jen are saying--is whether we need enough of a header that people know it's an FEC document that they've printed.

**Comment by noahmanger** [comment]
Yep, that's easy to do. @jenniferthibault can you make a black and white version of the mark to use?

**Comment by AmyKort** [comment]
Also, I have mixed feelings about the breadcrumbs. I think there was some idea of wanting to print a thing that didn't look quite so much like it was a printed page of a website. But, I can be convinced the other way about breadcrumbs, too.

**Comment by noahmanger** [comment]
We could do something like this (no breadcrumbs):
![image](https://cloud.githubusercontent.com/assets/1696495/18187784/782aa760-7061-11e6-853f-2f30bd81eff9.png)

Or this (breadcrumbs):
![image](https://cloud.githubusercontent.com/assets/1696495/18187913/814da5b2-7062-11e6-8346-df086078af3d.png)

**Comment by AmyKort** [comment]
I shared these around. Our preference is for the breadcrumbs--thanks for showing us both options. We've also got questions about what the statistical press releases would look like. Would they hold the styling for the tables and also be sure to page break at the right places? Can you help us get a better idea of how that would look?

**Comment by jenniferthibault** [comment]
@noahmanger,   instead of creating a new color suite of assets ([from your earlier comment](https://github.com/18F/fec-cms/issues/446#issuecomment-244186213)), can we keep the full-color seal and leave color printing preferences to the user in the print modal? This seems more flexible for later on when we move toward print templates for graphic pages. 

<img width="365" alt="screen shot 2016-09-02 at 9 51 54 am" src="https://cloud.githubusercontent.com/assets/11636908/18206011/ec4f5dde-70f2-11e6-8abc-cfc5e9c47e29.png">

**Comment by noahmanger** [comment]
@AmyKort breadcrumbs it is! And yes, it's possible to have the page break before or after a table. I'll whip up a demo of that. 

@jenniferthibault for the asset, you're right. But since the seal and wordmark are currently two different assets, would you mind making a single one for the lockup that we can use?

**Comment by noahmanger** [comment]
@AmyKort here's how it looks when you force it to not do a page break inside a table: 

![image](https://cloud.githubusercontent.com/assets/1696495/18214019/ceab017c-70ff-11e6-9232-1176bca38afe.png)

[Here's the PDF](https://github.com/18F/fec-cms/files/452683/Quarterly.reports.FEC.copy.pdf)

**Comment by AmyKort** [comment]
Looks great! I think we're good to go!
