### ISSUE TITLE
Visual design of Latest Updates index page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#454]
This is a placeholder issue. We need to discuss if we need to do more interaction design or if we can jump into visual design.

**Comment by jenniferthibault** [comment]
Moving the mockups from https://github.com/18F/fec-cms/issues/443 to visual styling, using the two drop-down pattern. Ready! Set! Go visual design go! 🏇

**Comment by jenniferthibault** [comment]
I've been updating these in an InVision prototype, though with limited functionality because it didn't seem necessary to make a static version of every category page by hand at this point.

Here are direct links to the Latest updates page from that prototype showing... 
- [All Updates, all subjects: ](https://gsa.invisionapp.com/share/758J375YX#/186914551_Latest-Updates_V1)
- [For media professionals, all subjects: ](https://gsa.invisionapp.com/share/758J375YX#/186914550_Latest-Updates_V1-For-Media)
- [For committees, all subjects: ](https://gsa.invisionapp.com/share/758J375YX#/186914549_Latest-Updates_V1-For-Filers)

For mobile, this would largely follow existing patterns, but here's a quick templatized capture to demo the dropdown fields and the articles with images:
![latest-updates_v1-mobile](https://cloud.githubusercontent.com/assets/11636908/18330527/157f961e-7527-11e6-90d3-5da36d079366.png)


Direct next steps from here would be to accommodate the text updates when they are ready from @emileighoutlaw 

👀 @nickykrause @noahmanger @onezerojeremy

**Comment by noahmanger** [comment]
👍 one question I have is: are we ever letting people filter by "press releases" / "weekly digest" specifically? Or just by the broader "for media professionals" category?

**Comment by jenniferthibault** [comment]
Yes! Each category level on the dropdown should be selectable, from what I understand. (but I'd wanna check that with our interaction crew)
I don't have individual mockups for those bc it was pretty tedious to make by hand.

**Comment by onezerojeremy** [comment]
I agree with @jenniferthibault : each individual content type should be selectable as a filter

**Comment by noahmanger** [comment]
👍  Agree that's important. It poses some challenges for the dropdown format that I explain in the PR over here: https://github.com/18F/fec-cms/pull/478#issuecomment-245462934

**Comment by emileighoutlaw** [comment]
I _thiiiink_ the only outstanding content we needed for this page was the intro sentence below the big `Latest updates` header. Let me know if I'm wrong. I wrote something super brief and included it in Noah and Christine's PR: https://github.com/18F/fec-cms/pull/478

What it says is:
> Search or browse the latest information on the Commission and federal campaign finance law.

I feel iffy about the "Search or browse" part, because Jeremy has taught me not to like calls to action with an "or" in them. At the same time, I don't want us to fall into the content trap of _explaining_ what a press release (Record article, etc.) is, which is what often happens on these types of pages and is not helpful to users. So if folks have thoughts, I'd love to hear them. And I'll keep mulling this myself, too.

**Comment by jenniferthibault** [comment]
A thought: a brief intro to what each publication type is has been helpful to us, and is something the FEC already has on their own site, just spread across the pages. What if we were to consolidate those snippets, and bring them here? 

Something like an improved version of...
> Search or browse the latest information on the Commission and federal campaign finance law.

> Weekly Digests are published every Friday and summarize the week's publicly disclosed activity. Covered topics include enforcement matters, litigation involving the FEC, meetings information and advisory opinion actions.

> The FEC Record is an online resource for political committees and others interested in latest information on the Commission and the federal campaign finance law. Until August 2011, the Commission published the Record as a monthly newsletter. Now, the agency posts articles as news happens, then compiles those articles at the end of each month.

> Press releases are... ? (maybe this one is too obvious...)

Just to give people a sense of what's included in the section and why publications are separated from one another.

**Comment by noahmanger** [comment]
☝️ I think an explanation here of the different types is really helpful. Otherwise there's nothing to suggest what they are (though press release is maybe self explanatory).

**Comment by emileighoutlaw** [comment]
It does feel weird to address 2 of 3 types of content, though. How about something like this:

> Search or browse the latest information on the Commission and federal campaign finance law.

> Weekly Digests are published every Friday and summarize the week's publicly disclosed activity, including enforcement matters, litigation, meetings information and advisory opinion actions.

> Press releases and FEC Record articles are published as news happens. Press releases are written for media professionals. Record articles are a written for political committees

**Comment by jenniferthibault** [comment]
👏

**Comment by noahmanger** [comment]
Works for me! I'll throw it in and close this issue. Nice work team!
