### ISSUE TITLE
Narrow down terminology for news and press pages

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#461]
Unified language is one of our content principles for this project. In keeping with that, we need to hone in on the lexicon we want to use to discuss our "Missives" section and the things that live there.

Tasks to completion
- [x] Draft content proposal
- [x] Team approval
- Implementation

**Comment by emileighoutlaw** [comment]
For the "Missives" section of the website, we need two pieces of microcopy:
- Page title
- Drop-down content

# Page title
I've been doing some content auditing, but there's not a great, well-established pattern we can to turn to for content here. So these options come to you only from my brain:

#### _Option 1(A)_
> ### Latest updates

This is what Jeremy has in as placeholder, and honestly, it ain't bad! 

#### _Option 1(B)_
> ### The latest 

A flashier version of Jeremy's name (better mouthfeel, I think), but it loses the word "updates." I'm not sure how important that word is, without input from users. If we wanted to do a "lowest fidelity" approach here (like we are with the drop-downs), B is better than A. We could add the word "updates" back, if we find in testing that people can't get there with "Latest" alone.

#### _Option 2_
> ### What's new 

Wagtail uses this as their link to highlight release notes, which is a slightly different purpose than what we're going for. But what intrigues me about this approach is that it's more in the mindset of the users we're hoping will click into this section (i.e., people looking to see "what's new" at the FEC).

# Drop-down content
I wish I could think of a better way to visualize this. Let me know if any of this needs clarification. 

**First drop down**
> _Publication type_
- For journalists 
    - Press releases
    - Weekly Digests
- For filers
    - FEC Record

**Second drop down**
> _Subject_
- Advisory opinions
- (And so on. No change to the subcategories, except that we want to follow our sentence case capitalization scheme)

**Year fill-in box**
>_Year_
yyyy


Okay! Proposal over. My reasoning follows—

Publication type: "Publication" feels more concrete (less abstract) than "update." Ultimately, what we are talking about are different publications, whereas "update type" could many many things, including "publication type."  Additionally, the word "Publication" fits better with the mental model that I believe folks will have when they visit this page. Again, research would be helpful here.

For journalists: I'm narrowing it down to "journalists" rather than "journalists / press." It's one less word to pay attention to, and I don't think any press member won't be able to identify "journalists" as the correct category.

Subject: I think the FEC calls these "categories," but I believe what they are are subjects (please correct me if I'm wrong). Subjects is a more plain English word than "categories," which can mean subjects, but can also mean other things too. 

Okay! That's it! As always, open to all edits and suggestions.

related to: https://github.com/18F/fec-cms/issues/443

cc @onezerojeremy @jenniferthibault @noahmanger @nickykrause

**Comment by jenniferthibault** [comment]
The time zone difference is really giving me a lot of first responder advantages today. Please folks, I don't think any of you would hesitate to disagree, but just in case: **don't hesitate**! 😸 

### Page title

I find the straightforwardness of 
> Latest updates

to feel consistent with the tone of the rest of the site. `The latest` feels a bit hip, and `What's new` feels a bit broad (though maybe useful on the home page later on for more comprehensive new things??)

### Drop-down content

- Publication type: ✅ good logic to me, I agree!
- For journalists: ✋ (question/thought) Over in https://github.com/18F/fec-cms/issues/455#issuecomment-244046347 the phrase "Media professionals" popped up. Is that more broadly accurate? I know it's longer, but feels like it's worth considering
- Subject: ✅ I'd buy that!

**Comment by nickykrause** [comment]
Piggy-backing on @jenniferthibault's comment:

> Drop-down content
> 
> Publication type: ✅ good logic to me, I agree! 
_(+1)_

> For journalists: ✋ (question/thought) Over in #455 (comment) the phrase "Media professionals" popped up. Is that more broadly accurate? I know it's longer, but feels like it's worth considering.
_(+1, but my perspective is inspired mostly by an abstract discussion I witnessed in grad school re: the changing definition of 'journalism' and the reality that there are now many different types of 'media' workers -- i.e.,  'media professionals,' including journalists. In a less abstract (more practical) sense, though, it seems very likely that any media professional would know to choose 'journalists' when faced with a choice between 'journalists' and 'filers,' so it may not matter here)_  
> Subject: ✅ I'd buy that!
_(+1)_

As for "the latest" and "latest updates," etc., my vote is for "what's new," because I think that the phrase would be meaningful to users seeking the most recent info, as @emileighoutlaw suggested. "The latest" feels too hip, as Jen said, and "latest updates" feels very useful, but also potentially redundant...? I am in favor of making our best guess and testing it :smile:

**Comment by onezerojeremy** [comment]
Mostly agree with everything! 

On whether or not we use "For filers" as a top level holder of the record or not, I think I'm torn. 
Pros: 
- it gives us parity with the press stuff
- it makes it clearer that it's less intended for journalistic consumption then the press content, whereas the name "FEC Record" could be misinterpreted by the government covering press as similar to other records (congressional record, i'm looking at you)
Cons: 
- clicking "for filers" would do the same thing as clicking "FEC record", if we make it clickable (which we should on the press side). So it's duplicative of the thing below it (unless we get other content for filers). if we don't make it clickable then it's inconsistent. (so we should probably make it clickable)


Little things: 
-"FEC Record" might be overplaying the FEC branding of it, given that the user will be encountering the dropdown/sidebar on the FEC's site. But just calling it "The Record" has it's own set of problems (see above). 
- "Subjects" vs "Categories" - i feel like i've seen these described more often as categories while perusing the web than as subjects. But if everyone else wants to try subjects first, I'm game!

**Comment by emileighoutlaw** [comment]
Thanks for the awesome thoughts, y'all!

#### Media professionals
Let's do it!

#### FEC Record
It _does_ feel like overbranding. But `Record` feels much more confusing. Could be campaign finance records? Could be records of filers? Could be.... I'm not sure why `FEC Record` seems more clear (because adding FEC doesn't actually add information), but it does to me. So my vote is still there.

#### Subject
I am always afraid to break with convention, especially for something like my gut. But I'm feeling wild today, so maybe we can try "Subjects" first and see how it goes?

**Comment by emileighoutlaw** [comment]
@onezerojeremy, what about `For committees` as the top-level holder of the Record ? 


The existing Record page holds that it's:
> an online resource for **political committees** and others interested in latest information on the Commission and the federal campaign finance law.

**Comment by onezerojeremy** [comment]
Sorry missed this yesterday @emileighoutlaw:  seems good, let's try it!

**Comment by jenniferthibault** [comment]
@emileighoutlaw I did my best to get the design issues
https://github.com/18F/fec-cms/issues/479
https://github.com/18F/fec-cms/issues/454 
and https://github.com/18F/fec-cms/issues/480
updated with all of these most recent decisions. Would appreciate your sharp eye and review in context. Feel free to leave feedback in those issues or here, just tag me and I can know to update the files.

**Comment by emileighoutlaw** [comment]
I think I got all the relevant content notes into those issues (let me know if you notice something missing, so I can rectify!). 

Thanks for doing so much initial organization, Jen. <3

**Comment by emileighoutlaw** [comment]
I think we can mark this issue as done and move all content talk to the design/implementation issues.

**Comment by jenniferthibault** [comment]
Awesome. Ok to close this issue then?

**Comment by jenniferthibault** [comment]
omg jinx @emileighoutlaw !
