### ISSUE TITLE
Home page stakeholder research

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#462]
Step 1 of our [home page plan](https://github.com/18F/fec-cms/issues/432) involves various types of research. This captures one aspect of this research, which is stakeholder research:

- Who are the stakeholders? i.e. Who at the FEC has an active stake in what goes on the home page and how those decisions are made
- What are their needs and concerns?
- What is their own internal understanding of user needs when it comes to the whole site and the home page in particular?

**Tasks:**
- [x] Identify stakeholders with help of partners at FEC
- [ ] Schedule interviews
- [ ] Conduct interviews
- [ ] Synthesize results

**Criteria for completion:**
- [ ] Findings from interviews synthesized into new research artifacts

**Comment by nickykrause** [comment]
@noahmanger: Just updating this issue quickly with the latest. Per the sprint planning meeting, it'd be great if you could push this issue forward a bit (while I focus on the research consolidation) by connecting with the partners to help identify the stakeholders. 

Also, during sprint planning, I believe you suggested that I would this issue back to design and conduct the actual research, and I don't know if I responded at the time, but: yes, I agree

**Comment by noahmanger** [comment]
Update: Emailed partners to update them on the plan and get input on stakeholders.

**Comment by nickykrause** [comment]
thanks, @noahmanger! I added to your comments, which I'm sure you saw. Hopefully this exchange helps to clarify things for the partners

**Comment by nickykrause** [comment]
@noahmanger, @onezerojeremy @emileighoutlaw @jenniferthibault  

I think we were planning to update this issue based on our conversation from the mid-sprint check-in on Friday. Essentially, I think we said something like this:
- We should design a focus-group-style feedback session with the partners, rather than conducting individual stakeholder interviews
- We should come to that session with something concrete for the partners to react to, rather than leaving the conversation open-ended
- This concrete thing should take the form of guiding principles and high-level recommendations for the homepage design, drawn from the synthesis of pre-existing user research
    - This is the point on which my memory is fuzzy...am I remembering this right? Or did we say we want to show the partners something visual, even if it's just simple, hand-drawn sketches? Anyone have clarification?

Given that we are moving away from stakeholder interviews and toward this different kind of session, we also mentioned that this task has changed: It should now be about designing the session itself. Some questions I'm considering:

- What is the goal of that session?
- What will we deliver in that session (see above)? 
- What feedback are we seeking? 
- What activities/tasks will we complete with the partners during the session?

**Comment by noahmanger** [comment]
Good summary. Sorry for not updating this on Friday. That all sounds right to me. Re: what we bring, we said we'd bring recommendations for principles and goals drawn from our research, not anything visual. We also want to have a quick meeting with the core FEC partner team before _this_ meeting to get a brain dump of agency needs and requirements from their perspective. 

I ran this by folks at the FEC today and they like the plan. So I agree — let's turn this task in to the task of planning that meeting.

**Comment by nickykrause** [comment]
@noahmanger: Do you think it's accurate to say that this issue officially become issue #464? If so, can we close it?

**Comment by jenniferthibault** [comment]
Where do we stand on whether any additional interviews are necessary? 

Is the exercise in https://github.com/18F/fec-style/issues/504 enough to get you what you need to know about stakeholder needs/concerns?

**Comment by nickykrause** [comment]
@jenniferthibault: Well, I don't think any additional stakeholder interviews are necessary if the FEC partners are confident that a series of individual, open-ended interviews would not go over well (or that they wouldn't be fruitful, for various reasons).
 
Given our trust in their concerns, our conversations so far have steered away from the stakeholder interview approach, in favor of (a) gathering the partner team's input (completed last week), and then (b) presenting the homepage design principles to a larger group (which we have put together based on research and input from the partners). 

I believe item B is what is being addressed in issue [#504](https://github.com/18F/fec-style/issues/504), which is the one I meant to reference (instead of 464)! 😬

**Comment by noahmanger** [comment]
Yep, that makes sense to me. We'll have a future task of planning and running that principles meeting, but that can be a new issue.
