### ISSUE TITLE
Visual design of Press index page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#479]
This issue carries over the interaction design/wireframes in https://github.com/18F/fec-cms/issues/455

**Comment by jenniferthibault** [comment]
There are a few content design areas that I wanted to flag for @emileighoutlaw's eyes in context of the page's design (No doubt you already know about them, you maybe even have a doc for them already, I'm just not sure where!)
- Hero area copy intro-ing the press section
- The intro copy for each section on the landing page
- The inviting friendly contact copy

Here is a first rough swipe at styling, with a few remaining visual tasks:
- [ ] find hero image
- [ ] accommodate copy changes to come
- [ ] mobile mockup

Question for @onezerojeremy / @nickykrause that I want to confirm: as far as I could tell, and also looking at Jeremy's latest mockups in https://github.com/18F/fec-cms/issues/443 there really aren't excerpt blurbs that we can pull from the Weekly Digests to put in any sort of feed. Is this true? Do we want to write a recurring general blurb/description with @emileighoutlaw 's help?

![press-index-v1](https://cloud.githubusercontent.com/assets/11636908/18292909/dd576fb0-745d-11e6-9be2-8b7ffca8ea58.png)

**Comment by nickykrause** [comment]
@jenniferthibault 
cc: @onezerojeremy 

I am not very familiar with the weekly digests (which, due to my ignorance, I didn't include in my original wires), but, after looking at [some of them on fec.gov](http://www.fec.gov/press/weekly_digests.shtml#search=weekly%20digests), I agree with you that there don't appear to be any blurbs that would be easy to pull into a feed.

However, it does appear that the weekly digests are always broken in the same way, to address all of the same topics, so perhaps that reality would make it easier to the "general blurb" you mentioned.

@emileighoutlaw - what do you think?

**Comment by onezerojeremy** [comment]
My hope is that perhaps in the future, when a digest is published it might have an authored blurb that perhaps condenses and elevates some of the things that are most noteworthy in the digest. But that's a future content authoring thing, and in the exciting meanwhile I don't know how much value a blurb that was applied to each digest would serve. 

my (apologetically grumpy, but nonetheless grumpy) .02: it wouldn't be too bad if you were on a page like this one with one digest, but if you had filtered to just digests on the full latest updates page, that blurb repeated 10-15 times might annoy.

**Comment by nickykrause** [comment]
@onezerojeremy: Yes, good point about the longer page! I agree it would be very annoying to have the blurb repeated that many times

**Comment by jenniferthibault** [comment]
I've been updating these in an InVision prototype, though with limited functionality because it didn't seem necessary to make a static version of every category page by hand at this point.

Here's a direct link to the Press index page from that prototype: https://gsa.invisionapp.com/share/758J375YX#/186914552_Press-Index-V1

Next steps from here would be to accommodate the text updates when they are ready from @emileighoutlaw .

Since this is a direct copy of the registration/reporting landing page template, I think it's ok to forgo mobile mockups, unless there's any questions from @noahmanger

**Comment by emileighoutlaw** [comment]
Just left a note about content in this PR: https://github.com/18F/fec-cms/pull/478

**Re: the top-level content** on this page (the main description for Press and then the intro blurb for `Latest updates` and `Resources for media professionals`) I want to work with Judy to write this— she's a fantastic writer, and I want her to feel she has a hand in personalizing this.

I'll talk to Amy first thing tomorrow about the best, fastest path forward.

**Re: the Weekly Digests.** I'm with Jeremy that I hate seeing a million identical blurbs in a row. How hard would it be to use wizardry to pull out a section of the Digest as a teaser? (this may be a @onezerojeremy or @noahmanger ask). We could do something like:

> Included in this Digest: Commission staff, together with our partners at 18F, continue to add new features to the agency's beta.fec.gov website...

I don't know how we'd pick what to pull from the Digests, because if we pick the first paragraph from the publication, it's always going to be something like 

> Included in this Digest: No Commission open meetings or executive sessions were scheduled this week....

Also, it would have to be an automated process, because it wouldn't be feasible to hand pick paragraphs for the hundreds of Digests.

Alternately, if that's not possible at this point, we can have a 😷  boring, short, repetitive thing 😷  like: 
> Weekly Digests are published every Friday and summarize the week's publicly disclosed activity. Covered topics include enforcement matters, litigation involving the FEC, meetings information and advisory opinion actions.

**Comment by emileighoutlaw** [comment]
(Or no description at all. That might be an option?)

**Comment by jenniferthibault** [comment]
Totally look to your guidance on this—this seems like it's a content design question with a front end dependency more than an interaction design problem.

If I'm reading correctly, seems like best case would be if there's any smart scraping that can be done a la your first option:
> Included in this Digest: Commission staff, together with our partners at 18F, continue to add new features to the agency's beta.fec.gov website...
( @noahmanger this possible?) 

Second best case: either the repetitive `Weekly Digests are...` blurb or no blurb at all (?)

**Comment by noahmanger** [comment]
As far as I can tell, the actual content of each Digest isn't structured data in any way. There might be something fancy we _could_ do at some point, but almost certainly not now, and I'm not sure it'd be worth the development effort. My vote is for just no blurb at all.

**Comment by emileighoutlaw** [comment]
I also vote for no blurb to start, since fancy structuring isn't feasible. Thanks for weighing in, Noah.

**Comment by jenniferthibault** [comment]
Thanks all— since the visual design of the page is going to be the same, and @emileighoutlaw is working with Judy on the intro content that can go straight into the implementation PR, I'm closing this issue.
