### ISSUE TITLE
Figure out all the required things we need to link to, and where they should/need to appear on the site

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#484]
So that users can access all the legally required material on fec.gov, figure out which links are mandatory and add them to the site.

**Completion criteria:**
- [x] Complete list of required links
- [x] Determine where they go
- [x] Implement

**Comment by emileighoutlaw** [comment]
For inclusion
- Plain Language
- Privacy Act Notices
- FOIA information

**Comment by jenniferthibault** [comment]
Adding a few notes here from our content manager group's feedback on the home page:

<img width="796" alt="screen shot 2016-12-21 at 10 38 42 am" src="https://cloud.githubusercontent.com/assets/11636908/21395245/c51f309a-c769-11e6-9289-aeb10eb3cd26.png">

**Comment by jenniferthibault** [comment]
@noahmanger since we are talking about navigation & preparing for a unified site experience, this makes sense to try to bump into this sprint. It came up today when talking about https://github.com/18F/fec-cms/issues/833

**Comment by emileighoutlaw** [comment]
Pinging @AmyKort on this one. Let us know when you find that magic memo of requirements 😄

**Comment by AmyKort** [comment]
https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2017/m-17-06.pdf

Check out # 16.

**Comment by jenniferthibault** [comment]
@emileighoutlaw I took a quick tour, and here's what jumped out as relevant to me

> **6. Protect Privacy**
> A. Each agency must maintain a central resource page dedicated to its privacy program on the
agency’s principal website. The agency’s Privacy Program Page must serve as a central
source for information about the agency’s practices with respect to PII. The agency’s Privacy Program Page must be located at www.[agency].gov/privacy and must be accessible
through the agency’s “About” page. [...]

-  Action needed: Identify plan for linking to Privacy page from About

_________

> 6 B. Privacy Policies on Agency Websites
Agencies must post Privacy Policies on their principal, sub-agency, component, and program
websites, mobile applications, and other digital services. For each website, **agencies must
post a link to that website’s Privacy Policy on any known, major entry points to the website
as well as any webpage that collects PII.** This requirement does not apply to internal agency
activities (such as on intranets or online interactions that do not involve the public). [...]

-  [bolding mine] Action needed: Identify plan for linking to Privacy page from home page

_________

> 6 C. Privacy Act Statements for Online Collections of Information
> A Privacy Act statement is required by law whenever an agency asks individuals to supply
information that will become part of a system of records under the Privacy Act.17 [...]

-  It feels like we don't meet this requirement, right?

_________

> **16.  Ensure Access to Mandatory Content** 
> [...] At a minimum, agencies must post links to the following information on the agency’s principal
website and on any known sub-agency or other major entry points to their site:
> - A. USA.gov;
> - B. the website’s privacy policy;
> - C. the agency’s Freedom of Information Act webpage; 
> - D. a page about the agency with descriptions of the agency organization structure, mission, and statutory authority, and links to the following information:
>   - 1. the agency’s strategic plan and annual performance plans;
>   - 2. the agency’s Privacy Program Page;
>   - 3. the agency point of contact as required by the Small Business Paperwork Relief Act of 2002;
>   - 4. the agency’s Open Government Page;
>   - 5. the agency’s Plain Writing Page;
>   - 6. information as required under the No Fear Act of 2002; and
>   - 7. information associated with the agency’s implementation of the Information Quality Act.

> For other required links, Federal agencies should determine the best location on their website to
place those links based on user needs and the underlying requirement from law or policy. 

- This definitely feels like the biggest ball of yarn to untangle—this mentions specifically the sub-bullet list that must be accessible through the About page, but we could do that in a number of ways (section or sub-section of the page, universal footer, custom footer etc). 
- I went hunting for the guidance on the plain language memo, and it took me a while to find because the new whitehouse.gov doesn't have it up anymore. Grumble. Linking here for future easy reference: [Final Guidance on Implementing the Plain Writing Act of 2010](http://www.dtic.mil/whs/directives/plainlanguage/omb_memorandum_m1115.pdf) 
_______

**Comment by emileighoutlaw** [comment]
Fantastic! Thanks, Amy :) So here's what I'm taking from that memo:

**Required links for either utility nav or footer** _(i.e., must be linked on every page)_
- USA.gov
- Privacy policy
- FOIA 
- About FEC

**Not required for on every page but maybe good practice to include in the footer**
- Plain language policy
- No FEAR Act information


**Required links for inclusion in the About FEC page**
- Plain language policy
- Agency point of contact as required by the Small Business Paperwork Relief Act**
- Open government page**
- No FEAR Act information
- Information pertaining to the Information Quality Act**

** I don't know if we've talked about these pages/information yet.

**Comment by emileighoutlaw** [comment]
@jenniferthibault!  I think we both commented on this at the same time, but as far as I can tell our takeaways were the same! 👯

**Comment by jenniferthibault** [comment]
@emileighoutlaw @AmyKort I mocked up two approaches to this:

**1:** The things that **must** be on every page are put on every page go in the footer. Other elements are linked from "About"

![screen shot 2017-03-06 at 5 05 43 pm](https://cloud.githubusercontent.com/assets/11636908/23632276/315dd616-028f-11e7-882e-4c5d3359237e.png)

________________
**2:** The things that **must** be on every page + some things that **could be** on every page go in the footer. No major changes to "About", but we would need to figure out how to incorporate the links to "Agency point of contact as required by the Small Business Paperwork Relief Act" and "Information pertaining to the Information Quality Act" into the page structure appropriately. 

![screen shot 2017-03-06 at 4 46 18 pm](https://cloud.githubusercontent.com/assets/11636908/23631482/ae44890c-028c-11e7-9878-87044e586f38.png)

_________________
Since both of these add additional complexity, I've simplified the contact information surfaced in the base footer itself in favor of moving that entirely to the "Contact" page. 

After seeing these, I feel like the first approach is more successful because it captures folks who are govt-savvy and expect that information to be there, AND it keeps the overall clutter down on pages where the utility footer is really helpful (quick test: try finding "Latest updates" in both versions)

There are a lot of ways to execute each approach, so feel free to fire back "this approach, but what if we also/instead tried X structure or Z pattern"
 _Example: Legal notices as page section instead of resources slab_

![screen shot 2017-03-06 at 4 56 23 pm](https://cloud.githubusercontent.com/assets/11636908/23631879/e5cb487e-028d-11e7-9d47-ca1e2192ea7f.png)

**Comment by AmyKort** [comment]
I think one of my (many) failings is that I can never see past the words. I prefer the idea of putting more of these links in the footer, but it's possible that I actually am just uncomfortable calling the other section "Legal Notices." That term means something very different as used in other parts of the website.

What do you think of a more robust footer with labeled columns so it's easier for folks to tell what "About" is about, for example. Like https://www.amazon.com/ ?

**Comment by jenniferthibault** [comment]
@AmyKort your ability to point out the nuanced differences in terms is exactly one of the (many) reasons you are so great at this work!

Using category labels in the footer is definitely another approach we could take. We use a mixed approach like that on [18f.gsa.gov](https://18f.gsa.gov/) too. I'd need @emileighoutlaw's guidance on how to break up those categories, so she and I can take a stab at that today!

**Comment by AmyKort** [comment]
Thanks @jenniferthibault !

**Comment by AmyKort** [comment]
Thanks for the link! I actually like the 18F footer a lot.

**Comment by emileighoutlaw** [comment]
Awesome thoughts both of you! Excited to pair on this today, Jen :) <3

**Comment by noahmanger** [comment]
I'm cool with this and don't want to workshop to death, but a couple thoughts:

1. What if we moved the "Required on every page" links (perhaps along with the Github repo and release notes and maybe API) to the bottom footer? That would reserve the top portion for the pages that people are much more likely to want to access?

2. I'm a little reluctant to remove the contact information from the footer entirely. I get the cleanliness argument, but I think it's an important part of credibility and people just expect it (a quick scan of the writing out there [suggests](http://www.uxbooth.com/articles/6-things-to-include-for-a-user-friendly-footer/) [as much](https://www.orbitmedia.com/blog/website-footer-design-best-practices/) as well).

**Comment by emileighoutlaw** [comment]
Just as a note for @AmyKort's visibility, I believe FEC is exempt from the Information Quality Act requirement and the Small Business Paperwork Relief Act requirements.

The Small Business Act is an amendment to PRA— if PRA doesn't apply to FEC, it seems like the amendment shouldn't either? Right?

And the [Information Quality Act](https://fas.org/sgp/crs/RL32532.) also seems to carve out an exception for FEC: 

> Because of the scant legislative history of the IQA and its lack of detail, OMB’s
guidance interpreting key provisions in the act has a major effect on its
implementation. OMB published proposed governmentwide IQA guidelines in the
Federal Register on June 28, 2001 (66 Federal Register 34489), and published final
guidelines (with a request for further comments on certain points) on September 28,
2001 (66 Federal Register 49718). OMB later republished the guidelines (after
making changes pursuant to public comments) on February 22, 2002 (67 Federal
Register 8452).9 OMB noted that the guidelines apply to all federal agencies that are
subject to the Paperwork Reduction Act — i.e., Cabinet departments, independent
regulatory agencies (e.g., the Federal Communications Commission), and other
independent agencies (e.g., the Environmental Protection Agency, or EPA).
Agencies not subject to the PRA (**and therefore not covered by the IQA or OMB’s
guidelines**) are the Government Accountability Office, **the Federal Election
Commission**, and government-owned contractor-operated facilities (e.g., laboratories
engaged in national defense research and production activities).

These exemptions jive with the legacy FEC.gov, which also doesn't include this content as far as we can find.

**Comment by emileighoutlaw** [comment]
@jenniferthibault and I paired on the footer today, and I think there are a couple interesting ways we could go with this. 

One of the things that came up as a possibility was to cluster related links in the footer (similar to the groupings @AmyKort noticed on IRS), but not necessarily label them. Adding labels has the potential to create tricky valuations of the links.

They'd still be clustered by affinity, but not necessarily given a label:

![screen shot 2017-03-07 at 8 26 07 pm](https://cloud.githubusercontent.com/assets/10552702/23687571/bfe35178-0374-11e7-9410-ebb0764fbe6b.png)


We could also go with a mixed approach, like 18F has, where some link groupings are labeled but not all:
![screen shot 2017-03-07 at 8 27 36 pm](https://cloud.githubusercontent.com/assets/10552702/23687589/d90642c8-0374-11e7-80a5-a4f9c51dee9f.png)




And some intel for @jenniferthibault — 

I did a little looking into USA.gov, and it's the
> official web portal of the United States federal government. It is designed to improve the public’s interaction with the U.S. government by quickly directing website visitors to the services or information they are seeking, and by inviting the public to share ideas to improve government

Thinking about it that way, it feels like it could go nicely with the "Open government" cluster of links

**Comment by AmyKort** [comment]
We are exempted from the PRA. I'll double check on the the other requirements. Thanks!

**Comment by AmyKort** [comment]
The Small Business Paperwork Relief Act and the Information Quality Act do not apply to the FEC.

**Comment by emileighoutlaw** [comment]
Great news! Thanks for confirming! I ended up leaving both of those links out of the potential options in my previous comment (very optimistic of past Emileigh). :) Do you have thoughts on either option?

**Comment by jenniferthibault** [comment]
@AmyKort small nudge on this—if we could wrap this task up before new ones are assigned in sprint planning this week it would really help us keep focused. Are there open questions in your mind we could help with to see which direction feels best to start with?

**Comment by AmyKort** [comment]
I think the "clustered by affinity" makes sense. It keeps us from having to force the labels, and it still makes sense intuitively.

**Comment by emileighoutlaw** [comment]
Thanks for weighing in. @jenniferthibault — what do you think about this approach? Should we sync up again?

**Comment by jenniferthibault** [comment]
👍 

![screen shot 2017-03-15 at 10 33 26 am](https://cloud.githubusercontent.com/assets/11636908/23953416/deac20ac-096a-11e7-835e-0564bee237cb.png)

Built on a six-column grid that leaves the first column empty. @emileighoutlaw I made one suggestion to the order of the "policy"-ish column, and put Privacy first, since I think it's a safe assumption that this is used more than the No FEAR . Were your orderings intentional otherwise? 

@noahmanger I brought back the address to the base footer (good point) but dropped the phone off because there is no "one" phone number that's best, and it would likely be more helpful for users to navigate to the contact page to see if they can skip the general intake # and find one for the office/dept that suits their needs best.

**Comment by emileighoutlaw** [comment]
I think that's a smart move putting privacy policy first. I think this is looking good to me.

**Comment by emileighoutlaw** [comment]
One more thing for @AmyKort — in order to make all these links work, we need our new No FEAR and Plain Language pages approved for launch:

[No FEAR](https://beta.fec.gov/about/no-fear-act/) 🔒 
[Plain language](https://beta.fec.gov/about/plain-language/) 🔒 

These pages are the same content as the existing FEC.gov pages. Hopefully they'll be fast to approve! Let me know if I can help with that at all.

**Comment by noahmanger** [comment]
Resolved by #909

**Comment by jenniferthibault** [comment]
Found this through another conversation today, and wish we had known about it at the time! https://www.digitalgov.gov/resources/required-web-content-and-links/
> ### Required Web Content and Links
> If you manage a public website in the federal executive branch, it’s a requirement to have certain content—or link to that content—from various places on your website. Here’s a table to help you comply with these requirements.

**Comment by nickykrause** [comment]
@jenniferthibault yes. that would have been helpful 😆
