### ISSUE TITLE
Test new Press page layout

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#526]
In order to validate that we the new press section helps users accomplish their goal, test it with users.

Here's a starting list of tasks:
- [x] Draft script
- [ ] Review script with members of the press office and adjust it to affect real world situations
- [ ] Recruit members of the press
- [x] Line up a member of the office to join testing
- [ ] Run the test
- [ ] Synthesize results

**Comment by noahmanger** [comment]
Issue updated and assigning @nickykrause and @ethanheppner

**Comment by nickykrause** [comment]
Script draft: https://github.com/18F/FEC/blob/master/test_scripts/2016-10-06.md

**Comment by noahmanger** [comment]
For the script, a couple thoughts: 
- Should we narrow the questions about finding things to more specifically prompt for resources for the press about litigation / responses to violations? On the one hand it might nudge them too far, but on the other I worry that this open-ended will have them trying to search in other sections. Alternatively, maybe choosing categories that are less likely to be confused with things in "legal resources" might do the trick
- Do we want to prompt any further on the landing page? Maybe asking them about the difference between press releases and weekly digests, or asking them to go from this page to the feed for either?

**Comment by nickykrause** [comment]
@noahmanger: Thanks for your thoughts! 

After noodling about it a bit, I think I have mixed feelings about the first bullet. 

I totally agree that with the open-ended navigation question, users will be more likely to search around in other sections. That makes me wonder, though: Is that an argument for the idea that people don't necessarily identify with a specific group (i.e., "journalist") when they come to a site attempting to complete a task? I don't know. I am curious to know if the journalists say to themselves "Well, I'm a journalist, so first I'd go to the Press section, and then look in there." I'm not all saying that we shouldn't have a Press section, but I think it's interesting to consider that journalists might not necessarily be drawn there for some kinds of things. 

But, on the other hand, testing that kind of thing at this point might yield really misleading results because, in reality, the full set of the navigation options just isn't there at the moment. So, when the users are presented with a task that says "You're a journalist who is looking for the latest info on litigation," they might actually be inclined to look for a homepage module or navigation item that showcases "What's New," which we haven't yet deployed. So, then, how good is the test?

As a compromise, I put in a first question for "where would you go..." _from the home page_, and then, after that, a prompt to bring them to the press section to try to accomplish the task there. (So: testing both things.) However, I don't want to go down a rabbit hole during the session, especially if it's the first time we're involving more partners in usability testing, so I am open to revising the test to start directly from the press page, and seeing how they'd accomplish the task (e.g., "Find the latest info on litigation") from that page. 

Responding to your second point: I had designed the first task to nudge users toward the Latest Updates feed, since it asks "What would you do if you wanted to find _only_ information about press releases?" The idea was that they would go to Latest Updates and use the filters, but, if they didn't, then I included a prompt to push them there:

>If it doesn't happen naturally, eventually direct the user to the Latest Updates section...

I did think, though, about asking a more pointed question on the Press landing page about how the page is structured, and whether or not they think the little "previews" of the feeds are useful. Maybe we should add that? 

I am still very much open to suggestions; just sharing my thoughts and explaining what went through my head when writing it today

**Comment by emileighoutlaw** [comment]
These are great thoughts y'all. I really connected with Nicky's noted:

> That makes me wonder, though: Is that an argument for the idea that people don't necessarily identify with a specific group (i.e., "journalist") when they come to a site attempting to complete a task?

I think our team does want more data on whether we can winnow the amount of information in resources for reporters if that information is easily accessible elsewhere on the website. Seeing if people will click into "Press" or "Legal resources" first to find litigation information is an important data point.

I like your compromise of asking folks where they would go. If it were me talking, I would add another note, something like "Don't click on anything, but tell me where you would go..." just to make sure we don't end up going down a rabbit hole. But I defer to you on that kind of thing, as this is your area of expertise and I'm not good at getting people back on track when they go off on tangents.



Since the press office is going to be sitting in on this session, I'd tweak the second scenario a little bit. They get really nervous about making sure we always say "alleged" violations, and I wouldn't want the question phrasing to be distracting. Maybe it could be:

>  In order to educate yourself, you have come to the FEC website to learn more about how the FEC reacts to possible violations of the law.

**Comment by nickykrause** [comment]
@emileighoutlaw Thanks for your input! I really appreciate the idea of saying "don't click on anything" - I will think on that a bit. It does have the benefit of avoiding going down the rabbit hole in a section that is of less interest for this test (e.g., Legal Resources).

As for the other tweak about the wording: I am happy to change it! I certainly don't want any triggers in the script. I am wondering, though, if there is any way to avoid saying "possible violations of the law," since that is exactly the wording that already appears in the section they would eventually access. I didn't want to lead them by using the same words, so I was trying to find another way to say that (thus, "legal transgressions"). Could I say "alleged legal transgressions"? I still don't love it, but avoiding "possible violations" as a phrase would be ideal.

**Comment by noahmanger** [comment]
That all makes sense about the navigation. I think what I'm trying to say is that I want to be sure we're asking the question in a way that will spur them to take the steps that they would naturally take. I think sometimes  in usability testing we see users trying to pretend their someone other than they are in order to give us a more generic user perspective. We want these participants to go through this _as themselves, as journalists_, not just as a generic user. Does that make sense? If so, maybe this can be addressed just in the introductory prompt.

**Comment by emileighoutlaw** [comment]
How about  "potentially illegal actions"

**Comment by nickykrause** [comment]
@noahmanger: I agree with you on this point, for sure:

>I think sometimes in usability testing we see users trying to pretend their someone other than they are in order to give us a more generic user perspective.

So, per your suggestion, I have updated the background questions to clearly state that we have specifically recruited journalists. I also added a note prior to the start of the first scenario to remind the user that we are interested in their perspective as a journalist. Finally, I followed @emileighoutlaw's suggestion to ask where they would go from the homepage, _without having them click anything._ This should give us at least some insight as to where they think the content might live, without having them dive into Legal Resources (or elsewhere) and spend valuable time clicking through sections that we aren't very interested in. 

(Oh, and as a side note: We are making it pretty clear during recruitment that we are recruiting these people _because they are journalists_, but it can't hurt to reinforce it in the script!)

Also, @emileighoutlaw: I changed the wording to "potentially illegal actions."

Repeating the script link: https://github.com/18F/FEC/blob/master/test_scripts/2016-10-06.md

**Comment by nickykrause** [comment]
Another update: @ethanheppner is working to recruit journalists for next week Friday. 

And, per the session with the FEC today, we are still waiting to hear about Judy / Christian's availability to participate as observers. Hopefully they will have some availability on Friday to be involved.

**Comment by nickykrause** [comment]
One last thought: @noahmanger: Whenever we feel like the script is in a good place, are we still planning to send it out for review by the FEC partners? I know you mentioned that you were thinking of doing that, but I wasn't sure if that was still the plan. Just curious.

**Comment by noahmanger** [comment]
Nice! This looks great. And yeah, I'd like to send it over. Any objection to me sending it over now?

**Comment by nickykrause** [comment]
@noahmanger No objection!
