### ISSUE TITLE
Make better name for buckets for static resources

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#567]
So that we have pretty URLs to PDFs, create better names for our AWS buckets.
- [ ] Create pretty URLS
- [ ] Update links

**Comment by ccostino** [comment]
@noahmanger:  This work got partially rolled into #601, but during our standup yesterday it was noted that perhaps this work wasn't worth moving forward on due to the proxy app going away with the migration to GovCloud.

However, when is that migration effort going to take place?  If it's going to be a while yet before we get to that, we may still want to give this a shot.  I was thinking some more on the approach I came up with and if it works, we'd be all set for the time being.  To recap:

1. Bind the S3 service(s) to the proxy app itself, which would allow the app to read the environment variables associated with each S3 bucket for access
1. Create another environment variable in the manifest files that maps routes to S3 service names in Cloud Foundry
1. For each route found in that mapping, grab the corresponding S3 bucket info and create a `location` directive in the `nginx.conf` built with it to provide the proxy redirects.

We'd do this for both the content that should live at `/resources` as well as attempting to create a `/downloads` path too.  @LindsayYoung, does this seem sensible to you as well?

That said, given the amount of time spent on this and uncertainty involved, should we stick with our decision yesterday and just put a pin in this piece until we're in GovCloud?  If so, then we just need to make the items slated for `/resources` tagged or organized properly within the bucket.

**Comment by ccostino** [comment]
Scratch all of the above - we need to move to the GovCloud environment in order for the assets to even be available publicly, at which point we should also have some other controls available to us to adjust the paths.

**Comment by ccostino** [comment]
The move to the GovCloud environment is done per https://github.com/18F/openFEC/issues/2031, so we can move forward on this.

**Comment by noahmanger** [comment]
I believe we did this, right @patphongs ?

**Comment by ccostino** [comment]
We may have done a part of it, I remember there being other issues around it (and the one linked above in particular: https://github.com/18F/openFEC/issues/2031).  Is anything remaining from that previous work?

**Comment by patphongs** [comment]
hmm...yes we did and it was working at one point: https://github.com/18F/fec-cms/pull/1143

I saw the environmental variable `CMS_AWS_CUSTOM_DOMAIN` is still set in web prod too.
