### ISSUE TITLE
Design flow and landing page for "About the FEC" section

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#626]
So that users can learn things about the FEC as an agency, design the flow of the "About the FEC" section.

---

We know what will be in this section (from [this issue](https://github.com/18F/fec-style/issues/540)):
- Department and office pages _(~30 HTML pages)_
- Legislative recommendations, history, and reports _(~50 mix of PDF/HTML pages)_
- Strategic plans _(~8 mix of PDF/HTML pages)_
- Budget plans and reports _(~100 mix of PDF/HTML pages)_
- FEC policies and directives _(~50 mix of PDF/HTML pages)_
- Annual reports; anniversary reports _(~35 PDF pages)_
- Procurement reports _(~10 PDF pages)_
- IG reports _(~150 mix of PDF/HTML pages)_
- Commissioner pages _(~690 mix of PDF/HTML pages)_
- FOIA  _(~30 mix of PDF/XML pages)_

The purpose of this task is to essentially answer two questions: how are all of these pages organized and which templates do they use? 

To do this, I don't think we need to outline each specific page, but we do need to outline the structure for each type of page. e.g. How are the different commissioner statement documents nested? 

The goal is to have this fleshed out in enough detail that we can pick up development in the next sprint.

**Completion criteria:**
- [ ] Abstract outline of all the pages
- [ ] Identify the templates for each type of page

**Comment by jenniferthibault** [comment]
This comment is to preview a conversation that @emileighoutlaw and I will have first thing tomorrow morning when she's back. It's totally welcome for @nickykrause / @noahmanger to offer first impressions before that if you'd like, but know that we won't likely have time to reconcile anything you specifically mention before meeting. I welcome you inserting thoughts/questions that you'd like us to for discuss during that meeting, if you'd like, or joining (sorry Noah, timezones & deadlines) but also fine if not. I didn't leave much time, I know.

Here's a first outline of how we could organize this section. Grey boxes are items that link to their own page (they may sometimes be a full section on their parent page, or sometimes just a link to their own full page. TBD) Things in pink are areas I have questions.

![screen shot 2016-12-12 at 6 56 11 pm](https://cloud.githubusercontent.com/assets/11636908/21121861/c61ab448-c09c-11e6-9b6f-020b4dddaebe.png)
![screen shot 2016-12-12 at 6 56 25 pm](https://cloud.githubusercontent.com/assets/11636908/21121860/c6158414-c09c-11e6-9a0c-4beff2854644.png)






_______________
One more: When I think about organizing information, it helps me to see the first bit of the templates that are possible, but that doesn't mean we're locked in to this format. Here's how I've visualizing the sections within the about page, and what I mean when I say pages would/would not link to deeper sections:

![about-landing_v1](https://cloud.githubusercontent.com/assets/11636908/21121793/7af4e66e-c09c-11e6-9d12-a46ecbc87aa5.png)

**Comment by nickykrause** [comment]
@jenniferthibault Thank you! If it's okay to crash your meeting, then I will, and I will look at this as much as possible beforehand.

**Comment by jenniferthibault** [comment]
Hey @emileighoutlaw & @nickykrause , I did a little simplifying to the outline to really hone in on the flow we need to settle on in order to move forward.

![about-flow-simplified](https://cloud.githubusercontent.com/assets/11636908/21157444/4f50246e-c147-11e6-88cd-882c16a188a8.png)

Then I made the outline into a clickable(ish) prototype(ish) in InVision to start visualizing the page templates each section could use.

[About the FEC outline on InVision](https://gsa.invisionapp.com/share/NW9Q0LD9E#/211084793_About-Flow-Simplified)

I did go as far as mocking up a quick template for:
- Commissioner pages
- Office pages
- Department pages

but to be honest, I'd prefer to leave those alone until we get into the specific designs & stylings of each section. Now, they're more to show what could be its own page vs what lives together on one page.

I think to move forward, we'd want to find agreement on whether the content buckets on the About landing page feels right, or needs adjustment:
- [About the FEC landing page sections](https://gsa.invisionapp.com/d/main/#/console/9879326/211084829/preview)

Then, we could go one at a time through making sure the content buckets are right within the sub-sections, and work toward content/design/implementation one at a time. Is that right? Or did I just agilefall? (Doublecheck cc @noahmanger )
- [Mission and history page](https://gsa.invisionapp.com/d/main/#/console/9879326/211084895/preview)
- [Organization page](https://gsa.invisionapp.com/d/main/#/console/9879326/211084980/preview)
- [Careers page](https://gsa.invisionapp.com/d/main/#/console/9879326/211085106/preview)
- [Organizational reports page](https://gsa.invisionapp.com/d/main/#/console/9879326/211085232/preview)

**Comment by jenniferthibault** [comment]
👋 @AmyKort Here is the issue we were talking about this morning with all the resources for viewing the outline so that you can read over it without us hovering :) 

From our walkthrough:
- The main big content buckets on the landing page seem ok to start with (with some title finessing needed, but the gist is in the right direction). If you have other thoughts after looking again, please let us know.

Which sections to start sussing out first:
- The "Mission and history" section is fairly small, well delineated, and the content exists, just needs to be pulled together in one place
-The "Organization" section would make use of the Commissioner page content that Pat has ported over, would migrate content to beta that's linked to from the home page, and would let us dig into the "Agency structure" section, which will involve dedicated content strategy & info architecture thinking to better understand if part of this should be on the website, and part might be better served in other internal tools or in other ways

Let us know if anything's changed after you take another look.

**Comment by emileighoutlaw** [comment]
@AmyKort— The things that aren't included in this mockup (that are in the [content inventory](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit?pli=1#gid=1353903152) :lock:) are copied below. 

I included a couple notes/questions, which we don't need to answer here (but are good for rumination):

- Lines 68-74
    - A publication on voter registration; does this fit into one of the proposed "Organizational reports" buckets?
- Lines 85-86
    - What's new: A possible candidate for retirement?
- Lines 88-99
    - EEO information: Needs more exploration— is it possible this fits into either 1) "Commission directives and policy" section, 2) a department page, or 3) in one of the proposed "Organizational reports" buckets?
- Lines 101-104
    - The "Activities performed by FEC (FAIR Act)" publication: Does this fit into one of the proposed "Organizational reports" buckets?

**Comment by AmyKort** [comment]
Thanks @emileighoutlaw ! A couple of thoughts about reports in the organizational reports section (unhelpfully, not in any order).

I agree we can retire What's New.

Publication on voter registration: I don't know. I was imagining this section would be for regularly filed reports, rather than one-time publications. I'd be interested to hear your thoughts.

EEO: all good questions!! :)

I don't think legislative recommendations fit here--they aren't reports about agency operations. Maybe they would make more sense as a legal resource? I'm interested to hear your thoughts.

I do think we should look at ways to keep our budget reports together. As explained on our current website: "The FEC is a concurrent submission agency and submits all budget and related documents to the President (Office of Management and Budget or OMB) and Congress simultaneously, pursuant to a provision in the Federal Election Campaign Act (FECA.)

"The original Budget submission consists of the main Justification for the budget request, the FEC Strategic Plan, the annual Performance Plan for the fiscal year of the budget request, and the Commission’s IT (Information Technology or computerization) Strategic and Performance Plan."

So basically, at the beginning of a new presidential term, federal agencies publish a strategic plan that covers that four year term and identifies overarching strategic objectives, activities and high-level measures. Then, as part of an agency's annual budget request/justification, agencies must include their annual performance plan for the year that explains how the agency plans to meet (or begin to meet) the overarching objectives of their strategic plan over the course of the year. Many agencies combine the plan with the request, to tie the requested funding to planned activities and performance at a more granular level. OMB recommends, but does not require, that agencies also include their annual performance report for the just-completed fiscal year in the budget justification/request, to give a full picture of performance all in one place. Alternatively, agencies can choose to include their performance report in a Performance and Accountability Report (PAR), which is published in November along with the agency's financial statement audit and other financial information. The FEC published a PAR up until a couple of years ago when the agency began submitting and combined Annual Performance Report/Annual Performance Plan with it's budget submission. 

I think breaking these reports apart could be confusing to users and would elide the relationship between performance and budget. In addition, because the requirements have changed over time, you will find, for example, that our 2004 strategic plan is reported within our budget request, as is our IT strategic plan. Likewise, our past PARs are our past-year performance reports. The Agency Financial Report, which replaced our PAR, similarly contains as section on performance. And I don't see where we would put our Summary of Performance and Financial Information if we treat these all as separate documents on separate pages.

In our call earlier, I couldn't remember exactly what the small agency requirements were for publishing performance information. The requirement from OMB circular A-11 (part 6, 210.8) is: Small agencies should produce their Strategic Plans, Annual Performance Plans, and Annual Performance Reports in PDF format using their existing processes and publication procedures. These agencies will include a link to the agency’s plans and reports on Performance.gov by e-mailing PREPSupport@gsa.gov or performance@omb.eop.gov.

I've also been relying on OMB guidance (https://www.whitehouse.gov/sites/default/files/omb/memoranda/2017/m-17-06.pdf) to better understand the requirements for what information must appear on the website and how.

I am also wondering whether some/most/all of what's listed below would belong in the organizational reports section (see http://www.fec.gov/open/index.shtml to get the links and some context. Some of this may be new to the website since we performed the inventory):

**Administrative Functions**
EPS Dismissals by Fiscal Year and Current Quarter 
Number of Cases Opened and Closed by Fiscal Year and Current Quarter, including average days to close a matter and total civil penalties assessed 
Case Closing Processing Statistics 
Monthly Reports from the Dept. of Treasury of balance available for Presidential Campaign Fund [PDF] 
Public Procurement Reports 
FAIR Act Inventory Reports 
Annual reports of receipts and disposition of gifts and decorations tendered by foreign governments to federal employees, spouses, and dependents submitted by the Commission to the State Department pursuant to Public Law 95-105 [PDF] 

**Agency Operations**
Agency Operations in Absence of Fiscal Year Appropriation Document 
We'd like you to help us to continue to move ahead by offering your own suggestions about additional material you'd like to see and telling us what works and what doesn't as you find information here.

**Plain Language** 
As required by the Plain Writing Act of 2010, we offer a Plain Language Web Page that highlights the FEC's long-standing commitment to clear communications. The page also lists staff you may contact with questions or concerns about our use of plain language.

And this is all leaving me wondering whether having a separate section for each type of report is going to lead to a long list of report types and a short list of reports. The Summary of Performance and Financial Information, for example, is something that we publish annually, but have only been publishing for three years. In ten years, we'll still only have 13 of these. The same is true for our AFRs, our Strategic Plans, our Plain Language Report (just the current one http://www.fec.gov/info/plainwritingreport.shtml). Or is this not a concern from a usability standpoint?

cc @amypike

**Comment by noahmanger** [comment]
So, I'd like to break out the content and design issues from this, but I'm having trouble parsing what needs further work. @emileighoutlaw and @jenniferthibault can you suggest some issues? (I can write them).

**Comment by emileighoutlaw** [comment]
All of these are great thoughts. And although I'm super glad this is out on paper for us to remember, I think we'll start untangling this when we're actually building the reports page itself. 

My really zoomed out thoughts on this:
- You've completely convinced me that we should keep budget and strategy documents together, and I have a couple ideas that we can explore once we dig in
- The Administrative Functions page is very interesting! 
    - The things on that page that I don't think are covered in other sections of the website (and also make sense to include here) are the gift reports and possibly the treasury reports.
    - The FAIR Act and procurement reports will be in our procurement and contracting card
    - The enforcement and case closing statistics should find a home in our enforcement section
- I'm increasingly feeling like Plain Language, the Privacy Act Notices, and the FOIA information should be special snowflakes that exist in the footer (and are thus accessible from every page) but don't live elsewhere in the site structure). 


Let's talk more about all this 💟

**Comment by AmyKort** [comment]
Thanks @emileighoutlaw You always look at my half-baked (leaning toward raw) thoughts and come out with a thoughtful plan. I feel really lucky to get to work with you.

**Comment by jenniferthibault** [comment]
I've split these into new issues:

Mission & history: #673 (tentatively marked for Sprint 3)
Leadership & structure: #675 (tentatively marked for Sprint 3)
Reports about the FEC: #677 
Careers: #678 

Closing this in favor of using those issues for topic-specific discussion
