### ISSUE TITLE
Implement home page version of header and hero

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#634]
Implement the new design for the hero area and header for the home page: 

![image](https://cloud.githubusercontent.com/assets/1696495/20908148/7f04ea3c-bb07-11e6-9b8d-62e0f527077a.png)

This is one step in the implementation of the new home page designs. The idea is that there's a new header that includes the full FEC seal which is only shown on the home page. Each of the three sections that are featured will link to their underlying section in the title, and the "Get started below" will scroll the page down to that section.

**Criteria for completion:**
- [x] New header with full FEC seal is visible on home page (and only home page)
- [x] The hero area is implemented as in the design
- [x] Each section title links to its respective page
- [x] Clicking "Get started below" takes the user down the page to the appropriate section

**Comment by jenniferthibault** [comment]
Design tasks to prepare for implementation:

- [ ] Export hero image
- [ ] Export card images

@xtine do you have any specific file type preference?

**Comment by xtine** [comment]
@jenniferthibault: png

**Comment by jenniferthibault** [comment]
@xtine sorry the content, links, and design are a bit scattered, but since we are splitting the page into sections to implementation, it's easier to keep the content in a separate doc.

[Google document](https://docs.google.com/a/gsa.gov/document/d/1bdbScZfwVtlauZRLtXh_-16h1BUUR26hPHC9pCLc-Os/edit?usp=sharing) with all the up-to date content so that it can be more easily copy & pasted 🔒 

[InVision](https://gsa.invisionapp.com/share/TD95OJRX3#/209035572_Home-V1_Copy_5) with final design and link paths

For layout (not content) here's how I was thinking it could stack:

![screen shot 2016-12-07 at 3 01 42 pm](https://cloud.githubusercontent.com/assets/11636908/20984427/30a397ca-bc8e-11e6-896b-d068f4cb7d04.png)

After I do a round of issue updates, I'll be exporting images for you :)

**Comment by noahmanger** [comment]
Resolved in https://github.com/18F/fec-cms/pull/659
