### ISSUE TITLE
Implement "Campaign finance data" portion of home page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#637]
In order for users to be able to find their way to the campaign finance data portion of the site, implement a section on the home page that introduces the data.

---

[Full home page design](https://cloud.githubusercontent.com/assets/1696495/20908227/2e474eea-bb08-11e6-9b55-e552a3b5c1cb.png) | This is the section for this issue:

![image](https://cloud.githubusercontent.com/assets/1696495/20908480/0558a342-bb0a-11e6-87b8-9a4ae0babb7a.png)

Eventually this section will also include small charts, but the idea is that we will start with the basics first and then add more. As such, this issue is for implementing the search box and a few links to different sections. 

**Criteria for completion:**
- [x] The search box includes options for candidates and committees
- [x] The search box implements the typeahead
- [x] The "Look up independent expenditures" link goes to https://beta.fec.gov/data/independent-expenditures
- [x] The "Look up recent filings" link goes to https://beta.fec.gov/data/filings
- [x] The "Look up an individual contributor" link goes to https://beta.fec.gov/data/receipts/individual-contributions

**Comment by jenniferthibault** [comment]
Here is a [Google document](https://docs.google.com/a/gsa.gov/document/d/1c8dxY7sGUY9Q8Qn3iAfyAyJI148HzozoQbtz5tzwo4g/edit?usp=sharing) with all the up-to date content so that it can be more easily copy & pasted 🔒 

And the [InVision](https://gsa.invisionapp.com/share/TD95OJRX3#/209035572_Home-V1_Copy_5) with final design and link paths

Here's how I was thinking the layout could stack on mobile:

![screen shot 2016-12-07 at 3 32 20 pm](https://cloud.githubusercontent.com/assets/11636908/20985411/62e215aa-bc92-11e6-99fe-93f89dbb0c15.png)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/657 . Nice work @patphongs !
