### ISSUE TITLE
Implement "Legal resources" section on home page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#638]
So that users can find their way to legal resources, create a section on the home page to showcase the various elements.

---

[Full home page design](https://cloud.githubusercontent.com/assets/1696495/20908227/2e474eea-bb08-11e6-9b55-e552a3b5c1cb.png) | This is the section for this issue:

![image](https://cloud.githubusercontent.com/assets/1696495/20908681/4b95c76c-bb0b-11e6-9bb3-f15b742da7f0.png)

(Ignore the purple stars. Relic of annotations).

**Completion criteria:**
- [ ] The first card links go to https://beta.fec.gov/data/legal/statutes/ and https://beta.fec.gov/data/legal/statutes/ and https://beta.fec.gov/regulations
- [ ] The second card links to the AO pages https://beta.fec.gov/data/legal/advisory-opinions/
- [ ] The third card goes to http://www.fec.gov/law/litigation.shtml
- [ ] The fourth card links to the enforcement actions and file a complaint pages goes to: https://fec-stage-proxy.18f.gov/data/legal/enforcement/ and http://www.fec.gov/pages/brochures/complain.shtml#search=complaint

**Comment by jenniferthibault** [comment]
Design tasks to prepare for implementation:

- [ ] Finalize & export card icons

**Comment by jenniferthibault** [comment]
Here are the updated designs for the first implementation:
![screen shot 2016-12-07 at 3 39 11 pm](https://cloud.githubusercontent.com/assets/11636908/20985655/5e844856-bc93-11e6-84c8-aba642237ae9.png)

Here is a [Google document](https://docs.google.com/a/gsa.gov/document/d/1c8dxY7sGUY9Q8Qn3iAfyAyJI148HzozoQbtz5tzwo4g/edit?usp=sharing) with all the up-to date content so that it can be more easily copy & pasted 🔒 

And the [InVision](https://gsa.invisionapp.com/share/TD95OJRX3#/209035572_Home-V1_Copy_5) with final design and link paths

For mobile, I was thinking we could drop the icons in these instances to save space in an already tight layout:
![screen shot 2016-12-07 at 4 01 11 pm](https://cloud.githubusercontent.com/assets/11636908/20986374/6978c7ac-bc96-11e6-89d7-f756ac7064fa.png)


I know I still need to export icons, but was hoping this would be enough to unblock any work from starting

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/681
