### ISSUE TITLE
Implement Complaints page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#651]
So that users can learn about the process for submitting a complaint, implement the designs for the "Complaint process" page. 

---

[Designs](https://cloud.githubusercontent.com/assets/1696495/20907733/d962729a-bb04-11e6-85e6-e8df9079da04.png) | [Content](https://docs.google.com/document/d/1XctsE8Lh5A2NCePAAhisyPVi-y4Az9CtIyNh8mtF7Zs/edit)

All of the links for the design are in the content doc. 

This page will be nested under _Enforcement matters_. 

We're going to need to either make a new template or modify the existing `CollectionPage` model to support these fields. There's a lot of similarities with the [new AO process page](https://cloud.githubusercontent.com/assets/11636908/20839417/81d8c812-b87a-11e6-8663-a6853050e033.png) so those could probably be designed as the same thing.

**Dependency:** This should use the generic template implemented in https://github.com/18F/fec-cms/issues/668

**Completion criteria:**
- [x] The page is fully implemented as designed

**Comment by noahmanger** [comment]
So, in order to get to this page, we need to update the blurb on the [Enforcement page](https://beta.fec.gov/data/legal/enforcement/).

This is an issue I'll need @emileighoutlaw help on (with @AmyKort 's review when you're back).

**Comment by emileighoutlaw** [comment]
Our strategy has pivoted since the enforcement page was first written: From a content perspective, I don't think it makes sense anymore to have two complaints links on this page.

The two things we surfaced (how to file a complaint and the guidebook for responding) are now integrated into one, combined page. So here are two options for how this content could read:

<img width="865" alt="screen shot 2017-01-03 at 4 07 34 pm" src="https://cloud.githubusercontent.com/assets/10552702/21625011/3cf178d4-d1cf-11e6-88b1-7b3d56185600.png">
^^This one is more succinct and easier to scan, but it's passive. It says what folks can find on the page but doesn't say at all why they might use it.

***

<img width="919" alt="screen shot 2017-01-03 at 4 10 01 pm" src="https://cloud.githubusercontent.com/assets/10552702/21625022/4850ee94-d1cf-11e6-9fdb-eb645a36b733.png">
^^ This is more active, it's more clear what the user might actually do with the information. But it's also more verbose.

Thoughts on this @AmyKort ?

**Comment by AmyKort** [comment]
Both look good to me. Pick the one that you think is better 😀

**Comment by emileighoutlaw** [comment]
Woo! In this case I think the first, version is better, because it's faster and easier to scan.

> **Complaints**
> Learn how complaints are filed, processed and made public


@noahmanger, can we move to implementation? I should be able to make the PR

**Comment by noahmanger** [comment]
That's good. I can do it. Which part of that links to the page?

**Comment by noahmanger** [comment]
This is all done and shipped.
