### ISSUE TITLE
Design content for ADR and AF processes

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#660]
This is a content design issue for compiling and lightly editing the content for the ADR and Administrative Fine process pages. 

Part of this includes also figuring out how the [administrative fine calculator](http://www.fec.gov/af/af_calc.shtml) figures into these pages. 

**Completion criteria:**
- [ ] Document of content approved by whoever needs to approve it

**Comment by emileighoutlaw** [comment]
Hi @AmyKort: Administrative Fine content is ready for you to look at. [Google doc](https://docs.google.com/document/d/1LAmDyKSb-KCW_QRFISwV6Q11auPzfeeaPEEtrdARiU8/edit#) :lock:

The admin fine content is two pages:
1. The administrative fine process
2. Calculating administrative fines (this page links to the current calculators, since we won't be building them for the first iteration)

Let me know what you think! Much of this is close to what exists already (on the beta site and FEC.gov), but I suspect we'll need OGC to give this a thumbs up, too.

**Comment by emileighoutlaw** [comment]
Quick question for @AmyKort about the ADR content. Is this: http://www.fec.gov/em/adr.shtml a brochure? (i.e., something we can't edit). If so, I think I want to adjust my approach for content for the ADR page. 

Thanks!

**Comment by AmyKort** [comment]
Yes, that's a brochure. I think we could make minor edits (like we made with the press office FAQs), but nothing substantial.

**Comment by emileighoutlaw** [comment]
Good to know! I'm going to adjust my approach to be more like what we have for our [complaints landing page](https://beta.fec.gov/legal-resources/enforcement/complaints-process/)

**Comment by emileighoutlaw** [comment]
Okay — I've adjusted course to make the ADR page more like our [complaints page](https://beta.fec.gov/legal-resources/enforcement/complaints-process/), because that format seems better suited to this information (and our goal of avoiding content duplication when we can). The draft [Google doc](https://docs.google.com/document/d/14S-SYvUm1LvBWfvMKJO95DwOZaueYddsTHgwFMvthJY/edit?pli=1#) 🔒 is ready for you to take a gander at, @AmyKort

**Comment by AmyKort** [comment]
I like it. I made the tiniest edit. Is this ready to share with ADR?

**Comment by emileighoutlaw** [comment]
This is done and ready for implementation
