### ISSUE TITLE
Update content strategy and design of "Candidate and Committee services" section on the homepage to reflect new content available

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#684]
When we moved from [Prepare first draft wireframes for homepage #518 ](https://github.com/18F/fec-cms/issues/518) to [Designing visual styles for home page wireframes #554](https://github.com/18F/fec-style/issues/554) we pivoted strategies for [Implementing "Registration and reporting" section of the home page #644](https://github.com/18F/fec-cms/issues/644) to only reflect existing Registration and reporting content, and not the future combination of that section with the compliance content.

This was not meant to be a permanent solution, but an agile interstitial solution.

When the content is migrated & implemented to a point we're comfortable will, we should return to the homepage section design to most accurately help users navigate to what they can find inside it.

Here's where out content strategy left off, and could pick up from:

<img width="854" alt="screen shot 2016-12-21 at 10 51 22 am" src="https://cloud.githubusercontent.com/assets/11636908/21395770/ca835172-c76b-11e6-80ea-bcca7b341f9a.png">
<img width="855" alt="screen shot 2016-12-21 at 10 52 18 am" src="https://cloud.githubusercontent.com/assets/11636908/21395769/ca811a92-c76b-11e6-9d45-3c2479483247.png">

**Comment by emileighoutlaw** [comment]
This has only changed a little bit since we've last spoken:


[Content doc](https://docs.google.com/document/d/1Hz12HWNSxWGrA-5N0u2FVCZtaumLoXDysdGURQbdE-Q/edit#) 🔒 

Notes
- We have seven, second-level buckets of information (_Taking in receipts_, _Making disbursements_, etc.). For clarity, I think it's important that if we show some of them, we show them all. But if we have seven links, I don't think we should have an additional 1-2 for _Timely information_ (feels like too many options for users). 
- For groups that don't have an upcoming training, I chose to highlight an e-learning video.
- We're not prepared to launch 1-2 sentence explanations of each group yet, but we can for a couple. I added those in, even though that makes a slightly inconsistent content experience; I think it's better to have some than none, especially for corporations and labor organizations (which operate as an SSF, not as corporations). 

Let me know how/when you'd like to discuss, @jenniferthibault !

**Comment by emileighoutlaw** [comment]
Additionally pinging @AmyKort to look over this initial homepage content

Our visual design (from previous discussions):
<img width="855" alt="screen shot 2016-12-21 at 10 52 18 am" src="https://cloud.githubusercontent.com/assets/11636908/21395769/ca811a92-c76b-11e6-9d45-3c2479483247.png">

And our updated content proposal (in this handy dandy [Google doc](https://docs.google.com/document/d/1Hz12HWNSxWGrA-5N0u2FVCZtaumLoXDysdGURQbdE-Q/edit#) 🔒)

**Comment by jenniferthibault** [comment]
Here's how this could work in context of an updated design—we're making use of our new nav pattern ([seen on candidate & committee profiles](https://github.com/18F/openFEC-web-app/issues/1786#issuecomment-276091863) that swaps sections of the page instead of jumping you down it 🎉 

I would have liked to keep the dark red background for this panel, but it was very busy, and too much small white text was feeling illegible even though it meets color contrast ratio requirements. Noped for now.

![screen shot 2017-01-30 at 9 06 19 pm](https://cloud.githubusercontent.com/assets/11636908/22449795/4da530c8-e730-11e6-9353-e21ae1a1bb71.png)

**Comment by emileighoutlaw** [comment]
Pinging @AmyKort — Would love to know what you think of:

- Jen's design above^^. 
- Updated content [Google doc](https://docs.google.com/document/d/1Hz12HWNSxWGrA-5N0u2FVCZtaumLoXDysdGURQbdE-Q/edit#) 🔒. 

If this looks good to you, we can close this issue and we'll move forward with implementation when we are ready to launch content.

**Comment by jenniferthibault** [comment]
Small nudge on this, 〰️  @AmyKort @emileighoutlaw

**Comment by AmyKort** [comment]
Design looks good. I think some of the content is still outstanding, like the name of the section, etc.

**Comment by jenniferthibault** [comment]
That makes sense! 🏁 @noahmanger for implementation issues, and copy edits for section names and content can happen there.
