### ISSUE TITLE
Images in Wagtail pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#760]
When uploading images to Wagtail pages, they keep breaking:

**Wagtail view**
![screen shot 2017-01-25 at 11 53 08 am](https://cloud.githubusercontent.com/assets/10552702/22302574/f70fa3cc-e2f4-11e6-8cce-cc86dc8b705f.png)

**Preview**
![screen shot 2017-01-25 at 11 54 55 am](https://cloud.githubusercontent.com/assets/10552702/22302619/20bb884e-e2f5-11e6-9862-125df711aef2.png)

Maybe I'm just doing it wrong? Has anyone successfully uploaded an image to the website using Wagtail yet?

**Comment by patphongs** [comment]
@emileighoutlaw I believe Wagtail is still trying to upload images locally and it can't do that. So @noahmanger wanted to direct all asset uploads (images, docs, etc) to our s3 bucket instead. So I made this PR https://github.com/18F/fec-cms/pull/747 but it has yet to be worked in because of fixes in the proxy which were just implemented by @ccostino today. I'm going to test my PR again and see if I need to make any changes to it given this proxy change.

**Comment by noahmanger** [comment]
Closing this as it should be resolved with #747
