### ISSUE TITLE
Test new candidate content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#766]
For usability testing this week, we have lots of new content for candidate and committee services. 

We haven't made any plain language improvements to it yet, but I'd like to test our structure decisions with real users to see how the new IA is working. 

The FEC has also responded that they feel strongly **Candidate and committee _services_** isn't the right name for this section. If possible, I'd like to somehow test out a portion of these possible alternatives:
- Candidate and committee support
- Candidate and committee resources
- Information for candidates and committees
- Help for candidates and committees

cc @nickykrause

**Comment by AmyKort** [comment]
Could we add one more:

Help for Candidates, PACs and Parties”  (or something like it)

**Comment by emileighoutlaw** [comment]
Yep!

**Comment by nickykrause** [comment]
I was working with Pat this morning to get the FEC's Ethnio account set up, and it seems like the screener will go live today. However, it might take a bit of time for responses to flow in, and they might not be exactly our target users for this content. Still, we can hope!

All of that said, I am wondering what other recruiting methods we might have at our disposal. Do we have any other ideas for reaching out to these users? Are there mailing lists or anything that the right folks might be signed up for?

Ideas are welcome!

**Comment by nickykrause** [comment]
Update: We have 5 users scheduled for Friday. Meeting with Lauren L today to brainstorm appropriate tasks for users to attempt to complete.

**Comment by nickykrause** [comment]
cc @emileighoutlaw

3 of the 5 users showed up for testing last week. We were hoping to do additional testing this week, to gather some more data, but the sessions fell through due to scheduling conflicts and then a few no-show users.

The synthesized observations from last week's testing are summarized here:

---

[Test script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-2-3-17.md)

Users' backgrounds (self-reported): 
- Deputy general counsel for human rights campaign. Nation's largest non profit working on LGBTQ. Handles political compliance or any type of political law. Practiced campaign finance law for a few years at another firm too.
- Consultant. Helps do compliance for clients. Has 8-10 clients of their own and subcontracts for another company and had a few clients there. Mostly corporate PACs and one association, and a union.
- Campaign finance compliance manager. 

---

**Task 1: Finding loans & debts section**
Users found the loans and debts section fairly easily. Really liked citations on the side. Although one user noted that the information was very basic but the key info was there.
**Takeaway**: :tada:

---

**Task 2: Finding what to do when embezzlement is suspected**
Users had mixed responses to this task, and all of them seemed to struggle with it in their own way. Some users suggested that a section labeled "troubleshooting" or "wrongdoing" should appear at the top level, rather than putting the troubleshooting information within the Keeping Records section itself. Another user noted that she would probably go to "Registration and Reporting" or even "Legal Resources" before she would think to look in a section called `Keeping Records.` Finally, one user pointed out that she expected that the page to tell her how to identify embezzlement, not just what to do about it.
**Takeaway**: We didn't test with very many people, so the signal is still muddy here. We can watch the structural issue here and try to collect more data about how users expect to address troubleshooting situations. There seems to be some disconnect between what we are offering on the page and what users expect, in terms of the completeness of the information.

I've logged an issue in the testing repo to keep an eye on this: https://github.com/18F/fec-testing/issues/31

---

**Task 3: Finding what to do with leftover computers when campaign ends**
All users were able to navigate to this information quickly and without taking wrong paths, but their response to the content on the page varied. One felt the legal citations were vey helpful. Another pointed out that the answer to the question "in limited circumstances" (without explaining what those circumstances were) wasn't ultimately very useful. 
**Takeaway:** 
Overall, people found the right answer very quickly, but there was some concern that the information felt incomplete. As with the previous task, there is some seems to be some disconnect between what we are offering on the page and what users expect, in terms of the completeness of the information. I haven't logged an issue specifically for this, because it is a very broad theme, but we should keep this in mind as we do more testing.

---

***General feedback about the compliance content**
- One user felt that the content was too high level and needed more specifics. (This is too broad of a comment for an issue)
- Multiple users praised the legal citations on the third tier of pages. 
- One user said that the campaign finance guides were the best publications anywhere. 
- One user noted that the candidate/committee search in this section seemed out of place. (I have logged an issue to watch this: https://github.com/18F/fec-testing/issues/32)

---

**Titling exercise**
We showed the users an outline of the candidate compliance content and asked what they would call the section. Users suggested:
- Campaign finance compliance
- Campaign finance entitites
- How to guide
- Committee type overview

We then showed the users a list of possible titles and asked if there were any in the list that seemed most useful. Here is a summary of what they said:

- There was some concern among two of the users that the label options did not cover corporations and labor orgs (one user brought this up organically, but the other had to be asked).
- There wasn't a clear trend as to which of the title options made the most sense, although two users **expressed that the word "support" would not work (either because it connotes financial support or because it sounds like an IT helpdesk).** 
- One user felt that "information" was too broad a term to be helpful, but another user liked "information" 
- One user felt that "resources" sounded too much like a list of links. 
- There were similarly split views of the word "help," with one user appreciating how straightforward it was (you can find help there), while another said it was too vague and was "useless."

Since we didn't test with very many people, it is hard to get a clear signal about which label would work best. However, one signal that is clear is that titles with the word "Support" probably aren't the best choice, given the other connotations with the word (money, helpdesk).

---

Next steps:

- We can celebrate that users were very successful with 2/3 of the tasks! :tada:
- We'll watch the two issues I logged in the testing repo about how to handle troubleshooting content and the need (or not) for the search bar in this section.
    - Hopefully these things will become clearer in future rounds of testing. Until then, there are no recommended changes.
- We can collect more data about possible titles, if we'd like ( @emileighoutlaw ?)

---

@emileighoutlaw is there anyone else you want to tag in on this summary?

**Comment by noahmanger** [comment]
@nickykrause anything more here or can we close?

**Comment by nickykrause** [comment]
@noahmanger I'm cool with closing it. I wasn't sure if there was anything @emileighoutlaw wanted to share out to the content team, but she can do that even if it's closed.
