### ISSUE TITLE
Visual review and refinement of Tips for Treasurers

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#773]
Before we release the Tips for Treasurers, 18F and FEC need to review and address any refinement issues. 

To view them on staging, [go here](https://fec-stage-proxy.18f.gov/updates/?update_type=tips-for-treasurers).

Tasks:
- [x] @jenniferthibault review
- [x] Fix credit to come from Information Division
- [x] Assign to someone at FEC to review

**Comment by dorothyyeager** [comment]
Hi just was looking at Tips for Treasurers on the beta site. I noticed an issue so I hope this is the right thread for it. It's being credited to the Press Office but it's actually Information Division (Greg and me) that puts it out, so that should be changed. Any questions FEC-wise about the tips, am happy to answer, just let me know. Thanks!

**Comment by noahmanger** [comment]
Thanks @dorothyyeager ! Adding it to the list.

**Comment by jenniferthibault** [comment]
A couple quick additional things that look like they can be solved programmatically:

- [ ] Add paragraph styling to main body content so that the content is scraped into a `<p>` tag. This will fix:
- the font size in the page template, which is currently too small
- the excerpt in the feed layout, which is currently escaping the container it's meant to live in
![screen shot 2017-02-07 at 2 29 55 pm](https://cloud.githubusercontent.com/assets/11636908/22707791/ef6021e0-ed41-11e6-9293-7caf506e57dc.png)

- [ ] To be consistent with other sections, the Read next field should say "**More** Tips for Treasurers"
<img width="1261" alt="screen shot 2017-02-07 at 2 30 49 pm" src="https://cloud.githubusercontent.com/assets/11636908/22707837/1990636c-ed42-11e6-85a8-d6117fbddc8f.png">


For next steps, @noahmanger should we fix these before assigning an FEC team member to take a final review? Or assign someone with these caveats listed? They aren't too hard to look beyond, but they do add interference for now that might make smaller details easier to overlook.

**Comment by noahmanger** [comment]
Awesome. Let's ask them to review now, since we won't be able to fix those until there's new code in production.

**Comment by jenniferthibault** [comment]
👋 @dorothyyeager would you like to take another review of the Tips for Treasurers pages with the changes above in mind?

You can see them on staging here: https://fec-stage-proxy.18f.gov/updates/?update_type=tips-for-treasurers

**Comment by dorothyyeager** [comment]
thanks @jenniferthibault @noahmanger will take a look through it!

**Comment by dorothyyeager** [comment]
Hi - have some comments I'll forward to you via email but overall looks good - just needs some tweaking here and there. Thanks!

**Comment by AmyKort** [comment]
Thank you, Dorothy! It's such a pleasure to work with you!!

**Comment by jenniferthibault** [comment]
Bringing in the complete list of fix criteria here:

- [ ] `From:` field should list `Information Division` instead of `Press Office`
- [ ] Remove periods from article titles
- [ ] Add paragraph styling to main body content so that the content is scraped into a <p> tag. [From above](https://github.com/18F/fec-cms/issues/773#issuecomment-278114781)
- [ ] On article page, document tag should say `Tips for treasurers` instead of `Weekly digest`
- [ ] Read next: first item should list another Tip document (maybe the most recent one published before this)
- [ ] The Read next field should say "**More** Tips for Treasurers" in the link to the full list [From above](https://github.com/18F/fec-cms/issues/773#issuecomment-278114781)

@noahmanger this gives a complete list to work off of for https://github.com/18F/fec-cms/pull/803

**Comment by noahmanger** [comment]
Ok! Made all those changes. 

![image](https://cloud.githubusercontent.com/assets/1696495/22757689/bc3fd192-ee00-11e6-98c9-0d049c170f2c.png)

![image](https://cloud.githubusercontent.com/assets/1696495/22757697/c3b239c4-ee00-11e6-8eb5-1735d117d975.png)

**Comment by dorothyyeager** [comment]
Thanks! Looks good!

**Comment by dorothyyeager** [comment]
Follow-up question - should I go ahead and start entering future tips now (like I'm doing with Record articles)?

**Comment by noahmanger** [comment]
@dorothyyeager we're going to need to run the scraper again for the new changes to take affect, so no need to add future ones just yet, as they'll get imported. Once we run that for the last time, then you can start adding new ones.

**Comment by noahmanger** [comment]
Resolved by #803 . Now we just need to re-import the tips on production and enable them via the feature flag and they'll be good to go.
