### ISSUE TITLE
Polish RAD form 

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#780]
After getting a basic [proof-of-concept](https://github.com/18F/fec-cms/issues/612) going, we should refine this form with @jenniferthibault and Lauren. 

**Completion criteria:**
- [x] Figure out what URL the from lives at 
- [x] Add links to the form 
- [x] Do any visual and content cleanup

**Comment by jenniferthibault** [comment]
### What's the URL?

My proposal is based on the fact that there will be other future divisions who also have these forms, that it would make sense to have it specific to the division. `question` seems generic enough to be safe, but I'm not attached to it if there's better alternatives. I think we should avoid `contact` because it conflicts with informational contact pages, not contact submissions. 

Current: `/registration-and-reporting/question-RAD`
Future:  `/candidate-and-committee-support/question-RAD`

### How do people get to the form?

I think the "Need help?" footer that's already established across the site is a great first step. This would require a card format, and would be easy to use, re-use, and add to existing pages without disrupting the content flow.

![screen shot 2017-02-02 at 10 01 09 pm](https://cloud.githubusercontent.com/assets/11636908/22578170/b73f334c-e994-11e6-9d91-044d33273869.png)

### Visual and content cleanup

Spoiler alert: this also treaded into UX design.

➕ **Recommended additions**
- Added link to privacy policy for how FEC protects the information provided
- It would be good practice to provide the user with an email confirmation of form submission. This creates a paper trail and record for the user. 
  - @patphongs do you know if this is possible from Service Now?
- Giving users an opportunity to cancel and clear the form instead of submitting it at the end creates peace of mind. Even though you could also exit out of the tab or navigate elsewhere, this creates more certainty
  - @noahmanger / @xtine is this feasible, or does it add significant new functionality?

🔺 **Recommended changes**
- The functionality notes indicate that the confirmation before submitting the form should be in pop-up, or some high-attention seeking mechanism. I've used font styles to emphasize the agreement statement a bit more, but otherwise I think we should start without any additional interactions, and see if the volume of submissions is too high, or if the submissions are proportionally irrelevant before making more drastic design changes. 

❓ **Questions/Remaining information needed** 
- We still need to provide users with an expectation of what will happen after they submit their question. I'm going to check in on the following with Lauren Lien:
  - How does RAD decide who to respond to first? First come, first served? Or do some types of     committees get preference?
  - What method should I watch for a response from RAD? Email? 
  - What kind of response should I expect? An answer to the question I submitted? An appointment time for further discussion? Something else?   
  - What timeframe should I expect a  response within? (When do I  start worrying that I won’t get a    response?)
- I'd like to understand a little bit more about how the custom Subject field is used
- Later: Will the ability to attach supporting documents ever be needed?

**Remaining**
The body content still needs to be reviewed, and @emileighoutlaw is expecting this to come her way.

**Comment by jenniferthibault** [comment]
Annnd the mockups, which I forgot to add before submitting 😹 

## Full form
![pressrelease-statistical](https://cloud.githubusercontent.com/assets/11636908/22578798/63e8e4f4-e999-11e6-9ce7-3fa00bdb798c.png)

## Custom subject
![pressrelease-statistical copy 3](https://cloud.githubusercontent.com/assets/11636908/22578801/6e535686-e999-11e6-83dc-4ce29df39ed9.png)

## Confirmation state
![pressrelease-statistical copy 2](https://cloud.githubusercontent.com/assets/11636908/22578811/78b160fa-e999-11e6-8b76-d6803bf182ce.png)

**Comment by emileighoutlaw** [comment]
From a content perspective, I love this design, and I agree about avoiding the word "Contact." I think "Submit a question..." is spot on.

Seeing these cards also made me think that we should add a verb to the "Reporting deadlines" card for consistency and to tell users why they might use it. How about something like:

"Look up reporting deadlines" ?

**Comment by patphongs** [comment]
@jenniferthibault I would imagine they should have email built in their workflow. So I think it would be something where use fills out form --> submits to ServiceNow --> ServiceNow builds a ticket and kicks off a workflow that includes sending a confirmation email to the user. I'll email our contact to ask them.

**Comment by jenniferthibault** [comment]
Thanks Pat that would be great to find out!

**Comment by llienfec** [comment]
Verbiage to be provided by RAD
- Subject
- Body
- From address: no-reply@fec.gov
- No-Reply

Subject:  Your Inquiry to the FEC

Dear [insert name provided by the committee/filer submitting the question]:

Thank you for contacting the Reports Analysis Division of the Federal Election Commission.  We have received your inquiry and will provide a response as soon as possible.  We make every effort to respond to questions within two business days; however, some inquiries requiring research may take additional time to resolve.  

In the meantime, you may find helpful information about filing, reporting, and other campaign finance-related topics on the Reports Analysis Division's Frequently Asked Questions web page, http://www.fec.gov/rad/index.shtml.  

Sincerely,

Reports Analysis Division
(800) 424-9530 (press 5 at the prompt)


Please do not reply to this automated email.

**Comment by llienfec** [comment]
^current RAD "we received your email" language.

**Comment by jenniferthibault** [comment]
Thank you very much Lauren for all the help & quick chats!

Here are my notes from the latest, which I think will put @emileighoutlaw in a good position to start thinking about the structure and content that surrounds the form:

### Position or title examples
Likely roles to choose from:
- treasurer, assistant treasurer, candidate, consultant, committee representative, attorney/lawyer, bookkeeper (or any of those with "compliance" in front of them)
- Examples of folks who RAD won't be able to serve through this form include journalists, press, and members of the public

### Custom subject field
Helps RAD keep track of increased communications of new themes that they may need to develop standard responses for. Over time, this can inform the items that are in the default dropdown.

### Expectations to set pre- and post-submission
**How does RAD decide who to respond to first?**
- There is a prioritizing system based on subject, but it's probably being revised at the moment. Not in a good place to communicate about it with confidence, so instead we should communicate standard timelines.
______

**What timeframe should I expect a  response within?**
- RAD responds to questions during standard business hours, except on filing deadlines, when they are available until 8pm ET
- It usually takes 2-3 business days, but longer if research is needed on the question
______

**What kind of response should I expect?**
- Users will receive email confirmation that their form was submitted (text of this current email is in [Lauren's response above](https://github.com/18F/fec-cms/issues/780#issuecomment-277356906))
- RAD will respond by email with a best attempt to answer. The goal is "one contact then close the issue." If additional info is needed, RAD would email and ask for a phone discussion, but this is not the goal.
______

At this point I feel like until the content is workshopped & structured a bit, most of the visual/UX design work is wrapped. @emileighoutlaw can I assign you in to this issue?

**Comment by emileighoutlaw** [comment]
Yes please! Thanks for changing the assignee to me, Jen. :)

**Comment by emileighoutlaw** [comment]
Lauren and I worked through the content today, and @llienfec was _fantastic_, as always! 💟 

Here's an updated [Google Doc](https://docs.google.com/document/d/19qbgkNct-HOoeS8yXjaD34hLRxbWKUwiO1qqToouWrc/edit#) :lock: of content. Lauren, can you take a look and let me know if you have more thoughts/edits/etc.? 

Once things are looking good, we can move to implementation!

**Comment by llienfec** [comment]
@emileighoutlaw My last edit is maybe change "filing questions" to "reporting questions" at the top. I'll pass this around the project team tomorrow for any last edits. Thanks!

**Comment by jenniferthibault** [comment]
Nice work @emileighoutlaw & @llienfec !
Here are updated mockups to accompany the new content:

### Full form

![rad-contact-form](https://cloud.githubusercontent.com/assets/11636908/22715445/fb5bcb8a-ed5e-11e6-9e09-ceee10a02894.png)

### Custom subject field

![rad-contact-other](https://cloud.githubusercontent.com/assets/11636908/22715412/c016b15c-ed5e-11e6-9f57-1f544929e5ae.png)

### Success state

![rad-contact-success](https://cloud.githubusercontent.com/assets/11636908/22715410/c015f5aa-ed5e-11e6-902e-414cb96369ff.png)

**Comment by noahmanger** [comment]
Screenshots with the edits: https://github.com/18F/fec-cms/pull/755#issuecomment-278198318
