### ISSUE TITLE
Commissioner serve dates are confusing

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#816]
Recapping conversation that happened in FEC's Slack:

The "serve" dates in our Commissioner page Wagtail templates don't work for messy dates. This is how we've created the template:

![screen shot 2017-02-13 at 2 19 33 pm](https://cloud.githubusercontent.com/assets/10552702/22901489/899d2f1e-f1f7-11e6-805c-2e1634b14429.png)

But in reality there are a few exceptions to that template: 

- Gaps in service without a reappointment
- Recess appointments (which lead to things like multiple swearing in dates)
- Commissioners serving on an expired term

Messy dates impact both current and former Commissioners, and we need to sort this out before those pages can go live. 

@AmyKort and @PaulClark2 brought up that they'd support an approach with as little information in the first iteration as possible, since it might be difficult to shoehorn this into template.

cc @jenniferthibault @noahmanger

**Comment by jenniferthibault** [comment]
I'm having a hard time knowing what the need is behind this, especially when looking at what happens on the current FEC site.

On the current FEC site, for current commissioners, I see this handled through description in the written text of the commissioner's bios:
> Steven T. Walther was first sworn in as an FEC Commissioner on January 10, 2006, as a recess appointee. Although his name was placed before the Senate for confirmation in June, 2007, his recess term expired on December 31, 2007, before the Senate acted. On June 24, 2008, he was confirmed unanimously by the Senate and sworn in by Supreme Court Justice Ruth Bader Ginsburg on June 27, to resume the balance of his statutory term. Mr. Walther served as Vice Chairman of the FEC for the balance of 2008 and served as the Commission’s Chairman in 2009.

<img width="243" alt="screen shot 2017-02-13 at 4 39 26 pm" src="https://cloud.githubusercontent.com/assets/11636908/22904601/054c085c-f20b-11e6-8cc8-17105ab36b83.png">

For former commissioners, I see a lightweight intro to this on the index page, but a more detailed description also in the written text of the commissioner's bios:
<img width="483" alt="screen shot 2017-02-13 at 4 40 48 pm" src="https://cloud.githubusercontent.com/assets/11636908/22904671/406132dc-f20b-11e6-9bc9-e563ff84ed9b.png">


Given the complexity around reappointments & expired / still serving terms, I'm not sure there is an elegant design solution without the benefit of the plain language write-up in each commissioner's bio. 

With this, I'm leaning that we don't make more custom fields that could generate confusing date ranges, since there is almost always an exception to the rule. Instead, we could have a generic field that accepts plain text entry, where we could essentially match what's on the current FEC site.
> (Reappointed in July 1987, July 1994 and July 2000)

What's your take, @emileighoutlaw ?

**Comment by jenniferthibault** [comment]
Actually! The more simple solution for now might be to just type the word "Reappointed" in the field itself, and enter only the year someone was reappointed, not the full DD/MM/YYYY. That would allow us to keep the fields as they are, but customize language around anything tricky (which I admit I don't fully understand, except reappointments)


Using @patphongs' examples from Slack, that would give us:
<img width="1090" alt="screen shot 2017-02-13 at 4 55 52 pm" src="https://cloud.githubusercontent.com/assets/11636908/22905227/8fd83ad4-f20d-11e6-8d41-6b6bffb9a000.png">
![screen shot 2017-02-13 at 4 57 24 pm](https://cloud.githubusercontent.com/assets/11636908/22905228/8fdc86fc-f20d-11e6-88bb-535b7e3d798a.png)


But it's possible I've oversimplified, so this idea would greatly benefit from someone who understands the term messiness better than I do

**Comment by noahmanger** [comment]
With only a partial understanding of all the intricacies, @jenniferthibault 's solution seems like a good one. It's valuable to store the start and end dates as actual `date` values in the database, because when displaying a list of past commissioners, they're ordered by expiration date. 

My vote would be to keep the start and end date fields and add a simple plain text field for additional details.

**Comment by emileighoutlaw** [comment]
I also feel like I don't fully understand the intricacies of this— I'm wondering what @PaulClark2, @AmyKort and @patphongs think of Jen's solution.

**Comment by PaulClark2** [comment]
I think Jen's solution works.

**Comment by noahmanger** [comment]
Sounds like we have agreement here. I added "Reappointed" to the existing pages with reappointment dates, so closing. But just pinging @patphongs and @johnnyporkchops that for future pages you need to add "Reappointed" in this field:
![image](https://cloud.githubusercontent.com/assets/1696495/23311087/ce92986e-fa82-11e6-884f-f3c133cfe0a2.png)
