### ISSUE TITLE
Apply nav menu to other content sections, consider updates

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-cms#827]
In applying the navigation menu to the legal resources and candidate and committee services sections, we wanted to take this as an opportunity to revisit the megamenu as designed (based on [#20](https://github.com/18F/fec-testing/issues/20) ). 

Note: the site should be navigable with or without the fly-out menu, and placement of remaining links from the [IA/sitemap issue](https://github.com/18F/fec-cms/issues/740) are in progress, see: 
- [candidate and committee services](https://github.com/18F/fec-cms/issues/783) - adding Deadlines, Forms, RAD Contact, Learning
- [data landing](https://github.com/18F/fec-cms/issues/833) - adding [API](https://github.com/18F/fec-cms/issues/729), Additional data, About the data _**link added**_
- [legal resources](https://github.com/18F/fec-cms/issues/824) - adding court cases, legislation, policy

So the good news is that I think for the Legal resources and Candidate and Committee services nav menu sections, we can use a pattern where we use the menu to introduce and provide quick access to the main subsections of those sections, and let the breadcrumbs, layouts, cards, buttons and page links provide deeper way-finding.

For Candidate and committee services, the main subsections appear (to me) to be the committee types; with the filing deadlines and forms index being good quick reference links that draw a considerable amount of traffic. I've also added a link to the home, as if I recall correctly from testing way-back-when, people looked for the section home link. 
![desktop - nav intermediate simpler copy 2](https://cloud.githubusercontent.com/assets/474916/23087507/d1745256-f542-11e6-93ec-9b2c5d46bfd4.png)  This pattern is pretty much the same for Legal resources, with the main sub-sections being Statutes, Regs, AOs, Enforcement, Court cases, Legislation, and Policy (tbd). Here, like on the data landing page, exposing the legal resources search felt natural. 
![desktop - nav intermediate simpler copy 4](https://cloud.githubusercontent.com/assets/474916/23087509/d51aafea-f542-11e6-8abd-ead1a3143e9c.png)  

Based on this pattern, we might consider a somewhat slimmed down menu for data landing that guides people to the advanced data landing page. Here are two looks at that.  
![desktop - nav intermediate simpler copy 3](https://cloud.githubusercontent.com/assets/474916/23087535/06b68ed4-f543-11e6-9493-32a7a83cba08.png)
![desktop - nav intermediate simpler](https://cloud.githubusercontent.com/assets/474916/23087537/0c7084e2-f543-11e6-99d8-b5bb76d2e551.png)

Apologies for the weird amounts of white space around the images in this. As always, happy to talk about this in person!

**Comment by onezerojeremy** [comment]
After a great conversation/advising session with @jenniferthibault made some updates : 
![desktop - nav intermediate simpler2](https://cloud.githubusercontent.com/assets/474916/23265834/f6831d50-f9b3-11e6-8efe-95b9fdc58e48.png)

The basic pattern here is to simultaneously illustrate what major sections lie within each, provide links to those for expert users, and at the same time to drive traffic to the landing pages, which help ground new users in what these sections encompass (in a way that a nav menu could not).

Obviously still imperfect, but hopefully good fodder for discussion.

**Comment by jenniferthibault** [comment]
A couple of evolutions to Jeremy's awesome work above - see them in action in this 🖌 [InVision](https://gsa.invisionapp.com/share/HQAOQLDF9#/221540402_Mega-Menu_Live_Hover)

### Summary of changes
**Campaign finance data tab**
- The lines under "Advanced data" now take you to those category sections on the advanced data page instead of directly to the data tables. This allows users to see the bredth of the category before choosing the data set they're looking for, _and_ allows us to [provide context to what is included in the data tables](https://github.com/18F/openFEC-web-app/issues/1322) ala this GitHub issue from research & user feedback about a year ago. In this way, the advanced data page begins to act more like an entry point for advanced users
- Added a link to the API in the navigation to surface it more prominently. This helps the API feel more like a part of the FEC's data product offerings, instead of a separate tool. (Discuss!)

**Candidate and committee services tab**
- Whatever the name of this section turns out to be, it would be ideal to have a shortened version to label the first category with (I've used "Services home" here)
- "Information for" links take you to the relevant section on the services landing page, where users could then select one of the 7 sub-categories

**Legal resources tab**
- Removed the embedded search in favor of near-term universal search, and keeping that functionality on the landing page
- Each link takes you to that section's landing page directly

![mega-menu_live data](https://cloud.githubusercontent.com/assets/11636908/23510931/71d78d40-ff29-11e6-976f-c0e98e5eda64.png)
![mega-menu_live reg](https://cloud.githubusercontent.com/assets/11636908/23510935/7511c318-ff29-11e6-9ad2-a1803525f01d.png)
![mega-menu_live legal](https://cloud.githubusercontent.com/assets/11636908/23510938/76dd903c-ff29-11e6-91a5-79ab5a3b6b5a.png)


Thoughts welcome!

**Comment by jenniferthibault** [comment]
@nickykrause & @emileighoutlaw : not sure if you're aware of this issue, so tagging just in case!

**Comment by jenniferthibault** [comment]
Updated 🖌 [InVision](https://gsa.invisionapp.com/share/HQAOQLDF9#/221540402_Mega-Menu_Live_Hover) with some changes:

- The operating principle should be that if it lives in the menu, it should link to a part of the modern site experience (and URL). For this reason, we:
  - Removed the API from the data menu so as not to confuse people about what is part of the site & what will take them away. 
  - Removed "policy directives" from the legal menu

These items will still be available from the landing pages themselves, but it would be confusing to link away from the site from the main menu. As the site transition continues, when policy directives are migrated, we'd likely expect that link to return to the menu.

- Re-ordered the Legal & Advanced Data nav items to reflect the new order of their pages' sections. Both are now ordered by most frequently accessed information.

![screen shot 2017-03-06 at 1 43 38 pm](https://cloud.githubusercontent.com/assets/11636908/23624437/acf4442a-0273-11e7-9176-87360bc6d33d.png)
![screen shot 2017-03-06 at 1 43 46 pm](https://cloud.githubusercontent.com/assets/11636908/23624436/acf1d528-0273-11e7-81f4-1cc507a33c71.png)
![screen shot 2017-03-06 at 1 44 34 pm](https://cloud.githubusercontent.com/assets/11636908/23624438/acf47b52-0273-11e7-99c9-a0bfe6d4fae7.png)




**Next steps**
- @emileighoutlaw we need to run the Candidate & committee services section by the content manager group, what's the best way to do that?

**Comment by jenniferthibault** [comment]
@nickykrause / @onezerojeremy this should be in good shape for testing this week as well!

**Comment by noahmanger** [comment]
I think I should be able to get a version of this working in actual code by the time we do testing, too.

**Comment by emileighoutlaw** [comment]
I think all this content looks really great. 

**Copyedit suggestion** for the `Candidate and committee services` menu:
- We'll want it to say _Information about_ rather than _Information for_.
- I'd also suggest omitting the colon. I understand why it's there (and it's technically correct), but the fact that it's the only across the menus feels a little jarring. I don't believe omitting it will be a barrier to understanding and would make for a more consistent experience. 

**Question time**
I have a slightly larger strategy question, which is maybe one that is better answered through testing.

The legal menu has the white line below "Home" that stretches across the whole menu:
![screen shot 2017-03-06 at 1 44 34 pm](https://cloud.githubusercontent.com/assets/11636908/23624438/acf47b52-0273-11e7-99c9-a0bfe6d4fae7.png)



Seeing that made me wonder about the column split in `Candidate and committee services`'s menu:
![screen shot 2017-03-06 at 1 43 46 pm](https://cloud.githubusercontent.com/assets/11636908/23624436/acf1d528-0273-11e7-81f4-1cc507a33c71.png)



The links underneath _Information about_ are children of the _Services home_ section, in the same way that "advisory opinions" are children of the _Legal home_. So that feels like an odd moment of inconsistency to me. Does that make sense?

**Comment by jenniferthibault** [comment]
On your second point—It makes sense, but right now it's this way because these two landing pages are structured differently.

Candidate and committee services has the four children categories (the "Information about" at the moment) But they don't have their own landing pages. We chose instead to building the seven sub-categories to the CC services landing pages themselves, so unless we want to rethink that architecture.....

On legal resources, that landing page & it's content is the least mature at this point. Data & CC Services have been architected & re-architected, but legal's day is still on the horizon. When that happens, I expect the nav to reflect that.

All this to say, it's reflecting the state of the site as we have it now, but will keep changing to grow!

**Comment by emileighoutlaw** [comment]
I still have some questions about this, but I think it'd be easier to talk about in person? Anyway, no reason to hold this issue up on my account. Maybe @jenniferthibault and I could sync on Thursday or Friday for a quick 10-20 minutes?

**Comment by noahmanger** [comment]
New issue for finalizing this work. https://github.com/18F/fec-style/issues/655
