### ISSUE TITLE
Design way-finding and navigation between old and new experiences

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#835]
The purpose of this task is to answer a series of questions around how we manage the experience for users as they traverse between the old and new site experiences. At the heart of things is this question: When users navigate to the old experience, is it (A) a subset of pages from the current fec.gov that have been changed in some way, or is it (B) to a static snapshot archive of fec.gov as it its today?

Our working assumption is that the approach we're taking is (A). We should use this issue to nail down that that is the correct approach. And if so, these are further questions to address:

**Additional questions:**
- [ ] When users go from new site to old, what UI elements are in place to keep them oriented and help them get back? 
- [ ] To what extent are we redesigning the IA and navigation on the old experience?
- [ ] How do we style and present links from the new to the old experience? 
- [ ] How does the 404 page on the new site change?
- [ ] How does the 404 page on the old site change? 

At the end of this issue, we should have a series of screens that illustrate the changes that will be made to the new and old sites and/or issues for further design and implementation work.

**Comment by patphongs** [comment]
Notes from our discussions today:

- What's possible on the old site?
- Linking Legal documents
- Redirects
- Banner
- Navigation to remove from old site
- 404 pages design on new and old site
- Have pattern so it doesn't break on each individual piece.
- Running a parallel Dev environment in AWS

**Comment by nickykrause** [comment]
@onezerojeremy - Some notes from our chat earlier:

---

**Classes of content:**
- Liminal types:
    - **To-be-reborn**
        - Once reborn, the old pages are ashes? Or zombies?
    - **To-be-retired**
        - Once retired, the old pages are archival?

- Established type:
    - Stable pages on the new site - living and happy and :tada:

---

**Questions:** 

UX questions:
- Where do things live, in terms of the experience, and how do we indicate where they live?
    - When you are somewhere, how do you know where you are? 
    - How do you know what kind of page you’re on?
- What do we do with the ashes of content that have been moved? 
    - Do we just redirect to the new site, so no one can accidentally access it? 
    - Or does it live on, like a zombie page that shouldn’t be a alive but is still there?
        - If it lives on, what does it look like, and what does it say?
- What is the experience of navigating between experiences?
    - ...from a stable page on the new site to a to-be-reincarnated page on the old site?
    - ...from a to-be-reincarnated page on the old site, to a stable page on the new site?
- What is the experience of getting a search result for a to-be-reincarnated page on the old site, and how does it compare to finding a stable page on the new site?
    - What is this experience like via Google? 
    - What is this experience like via search on the new site?
    - Will there still be a search on the old site? Is that an experience we need to consider? 
- What is the relationship between the new site navigation and the old site navigation?
    - Will the old site still have navigation needs? (e.g., if there is a whole section of content still sitting on the old site, will users need to be able to navigate inside that content? How would that navigation experience compete with the navigation to the new site, for the content outside that section?

- Procedural questions:
    - At what point does content retirement happen and how is it managed?
    - At what point does content reincarnation happen and how is it managed?

----

**Thoughts on what we need to produce**

- Wireframes/some visual representation of how the experiences will look/work
    - User flows
- Process flows for some of the procedural/content governance flows
- Part of this task is **making a presentation to the FEC** about what these classes of content are and how we’re suggesting that they relate to each other. What is the case we’re going to make?

**Comment by patphongs** [comment]
Just tacking onto this ticket because I feel like this is an important piece of the two site puzzle cc @nickykrause @onezerojeremy 

What domain will the legacy site have? Since this site will be running in parallel, we want to give this some thought because we don't want users thinking the legacy site is old. 

Suggestion from @noahmanger `classic.fec.gov`. Has a nice ring to it!

**Comment by nickykrause** [comment]
After much conversation last week, we produced two possible approaches to the two-site strategy:

- **Liger**. For content that we know needs to be migrated but has not yet been redesigned, create "transitional" pages on the new site (fec.gov), where the body of the page contains legacy content and the "frame" of the page contains the new navigation. Also create an "archive" version of the legacy site, which will be a snapshot of the site in its full form, but which will not continue to be updated (it is for reference only).

- **Mirror**. The new site (fec.gov) and the old site (transition.fec.gov) are available in parallel, with banners existing on both sites to help users move between them. The new site will have "alerts" directing users to the transition site for content sections/elements that are not yet fully-formed, and we will provide special link styles alerting users that they are moving from the new site to the old site. Furthermore, the transition site will offer "gentle redirects" for content that has already been fully moved to the new site (e.g., the press section, data section), so as to keep users informed and in control of what is happening. The "gentle redirects" essentially allow the user to access a page that is overtaken by some kind of alert that the content has been moved elsewhere.

After much discussion, most of which is [available in this Google doc](https://docs.google.com/document/d/1BMUv-hHQAQKOtwwNZESoM121NE37Uj8nD1sqpIbGKDg/edit#heading=h.sl051ddj08wk) :lock: , we decided that the Liger solution offers the most "pros," but there are still quite a few unknowns about its technical feasibility, as well as the possibility that the "transition" pages will feel incomplete or be potentially problematic for internal users. We don't want to disrupt people's ability to do their jobs.

That said, **we have opted to set aside a few days for @patphongs to attempt a Liger prototype.** If we are able to make sufficient progress on a Liger prototype without encountering significant blockers, then we will proceed to test Liger with both internal and external users. If Liger does not fare well for any reason, we can switch to the mirror approach.

---

These are the tasks we have upcoming in the next sprint (likely need to make issues for these):

**Prototype**
- Build a Liger prototype in the first few days of Sprint 2.2

**Visual design and microcopy**
- Visual design of banners, alerts, 404/500 pages (404s and 500s for new site pages, transitional pages, and archive site?)
- Content/microcopy design of banners, alerts, 404/500 pages

**Content**
- Content mapping for links/redirects
- Sitemap buildout
    - Build out green dotted line pages in wagtail 
- Figure out which Liger pages might need supplemental "navigation" in order to offer a whole story (e.g., in the demo we added links at the top of the "Help with Reporting and Compliance" page for Quick Answers, Library)  

**Testing**
- Test the Liger prototype with internal users
- Test the Liger prototype with external users

I'm taking suggestions for things to add to that list (or things that might need to be altered. Does this look right to you, @onezerojeremy and @patphongs?

Once we have a good list, we can break this out into other GitHub issues leading into sprint planning.

**Comment by noahmanger** [comment]
This looks like a solid list to me. Let's wait to build out additional issues until we've validated the concept with https://github.com/18F/openFEC-web-app/issues/1887

**Comment by noahmanger** [comment]
This work has all been continuing through other issues, so I'm closing this one.
