### ISSUE TITLE
Design experience for linking to legacy legal resource tools

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#840]
At the time of the site flip, we will need to continue to provide links to EQS and the AO search, alongside our own searches for those items. So that legal researchers always know where they can get what information, we need to design the experience around how those two things co-exist. 

---

Basically we need to address why one would use the new tools vs. the old tools, and provide links back to the old tools. We'll need to talk with @AmyKort more about how to message this in the interface. 

cc @nickykrause @onezerojeremy @jenniferthibault

**Comment by jenniferthibault** [comment]
For the following tools, I know we have begun implementation on the beta site, but each is in varying stages of completeness for functionality or data quality:

- [SERS](http://sers.fec.gov/fosers/) (regulations search)
- [SAOS](http://saos.fec.gov/saos/searchao) (AO search)
- [EQS](http://eqs.fec.gov/eqs/searcheqs) (MUR, ADR, Admin fine search)

I would need our legal devs and subject matter experts to help point out the specific ways that the tools on the beta site differ, or have incomplete data, but I think we have enough to start crafting an approach and basic messaging.


## Placement of notice: guiding principle
**Place the notice where it impacts the results you expect to see** (or as close as we can get to that spot with the current site map)
- For the features we have preliminary search results pages for (AOs, Regs, MURs), this means we can put the notice at the top of the search results list ([as we currently do](https://beta.fec.gov/data/legal/search/enforcement/?search=filing&search_type=murs) to alert people Archived MURs aren't available) or in the filter panel.
We have precedent for each, but the search results area seems a better use of space.

## Content of notice: guiding principles

These definitely benefit from content review, but I started with the template @emileighoutlaw set in https://github.com/18F/fec-cms/issues/836#issuecomment-284900830 for safe starting territory. 

**Set expectations for work in progress or not**
- when we're actively developing something, say so. When we aren't planning to make improvements soon, acknowledge that too in order to set expectations for timely improvements (AOs) or somewhat of a wait (regulations improvements)

**Help users know what's different between the two experiences**
- Mention specific differences in data availability or completeness

**Direct users to where the data is complete**
- the transition site's URL


## Drafts
![new - near before - legal](https://cloud.githubusercontent.com/assets/11636908/23885209/12645906-0848-11e7-93cc-2cd79c429936.png)

## Timeline for notifications
- These could be placed as early as they can be implemented (no need to wait until site flip, as they are accurate now), and should remain through the site transition until each feature reaches parity with its predecessor. 

Thoughts on any of the above?

**Comment by jenniferthibault** [comment]
Also — did I miss any other legal apps?

**Comment by patphongs** [comment]
@jenniferthibault Thanks for making this ticket! I was talking to @AmyKort and @amypike yesterday and there's a few missing from your list. Here's the full list, I also put in links to the new landing pages on the new site for these items. I hope this helps!

- AO Search
        - http://saos.fec.gov/saos/searchao
        - New site - https://beta.fec.gov/data/legal/advisory-opinions/
- Rulemakings
        - http://sers.fec.gov/fosers/
        - New site - To be built
- MUR Archive (1975 - 1998)
        - http://www.fec.gov/MUR/
        - New site - https://beta.fec.gov/legal-resources/enforcement/
- Current MUR search (1999 - Present)
        - http://eqs.fec.gov/eqs/searcheqs
        - New site - https://beta.fec.gov/legal-resources/enforcement/
- Administrative Fine Program
        - http://eqs.fec.gov/eqs/searcheqs
        - New site - https://beta.fec.gov/legal-resources/enforcement/administrative-fines/
- Administrative Fine Calculator
        - http://fec.gov/af/
        - New site - 
- Alternative Dispute Resolution
        - http://eqs.fec.gov/eqs/searcheqs
        - New site - https://beta.fec.gov/legal-resources/enforcement/alternative-dispute-resolution/
- Audit Report Search
        - http://fec.gov/auditsearch/auditsearch.do
        - New site - https://beta.fec.gov/legal-resources/enforcement/audit-reports/

**Comment by jenniferthibault** [comment]
This is great Pat, thank you! I'll adjust a few things and will update this issue again with a new iteration

**Comment by noahmanger** [comment]
A few thoughts (and maybe better to discuss in design pairing, but logging here before I forget):

1. For AOs and MURs, I like the "info message" style. This feels like the right component and placement. But for language what about also adding something to more clearly differentiate the two tools, which would also include why you'd want to use the new one over the old. 

2. For both of those messages in the search results, they feel perhaps a little _too_ prominent. Should they be minimizable?

3. For ADRs and Admin Fines, what about taking the approach you suggested with rulemakings and just including regular links? Because there's not already some equivalent form of the tool on the new site, I think it's less important to call attention to their absence.

**Comment by jenniferthibault** [comment]
1. Language on all of these needs @emileighoutlaw , but I agree with your observation! On principle we should tell folks if there's more data/functionality on one or the other. 
2. Love the idea of minimizing them on the data tables, I'll have that mocked up in a jiff!

3. The only reason I did plain-text links on rulemakings is because the text is written in paragraph style about the SERS tool. I'd prefer to use the alert style there too if we can.
I think folks will be looking for these tools, so calling the users attention isn't about pointing out the absence, it's about helping them find there it lives.

**Comment by jenniferthibault** [comment]
Here's how the minimizing could work:
- alert would start open by default

![screen shot 2017-03-20 at 3 45 55 pm](https://cloud.githubusercontent.com/assets/11636908/24118496/6aeec778-0d84-11e7-8bf9-28bfad018399.png)

Toggle closed:

![screen shot 2017-03-20 at 3 46 03 pm](https://cloud.githubusercontent.com/assets/11636908/24118497/6af01286-0d84-11e7-803f-2af6a559b3f8.png)

**Comment by jenniferthibault** [comment]
Sorry, I hit enter before finishing!

@emileighoutlaw are you ready to take this issue assignment over for content?

**Comment by noahmanger** [comment]
Just chatted with Jen about a few things and here's a couple take-aways:

### SERS
For the link to SERS, we want to stick with the current implementation, which uses a button:

![image](https://cloud.githubusercontent.com/assets/1696495/24119568/f34594f0-0d6e-11e7-8367-26453e8f5429.png)

But instead of the heading and content here being about SERS, we think it makes the most sense for it to be about the actual _substance_ of SERS (Rule making documents?). It can reference SERS, but should be oriented around what you'll actually find, no?

### ADR and AO
In the spirit of framing in terms of _what you'll find_ rather than _the system you're using_, we think that instead of an alert style link to EQS from the ADR and AF pages, we could use the existing pattern of a block of copy + a button, like:

![screen shot 2017-03-20 at 1 37 14 pm](https://cloud.githubusercontent.com/assets/1696495/24121166/81a24586-0d74-11e7-9fe0-74c25f292a0a.png)

What do you think @emileighoutlaw ?

**Comment by jenniferthibault** [comment]
@emileighoutlaw below is a collected summary of the alert text needed. When possible, it would be good to communicate:
- Clear differentiations between the two tools, which would also include why you'd want to use the new one over the old.
- Expectations around if the tool is a work in progress

### AOs
Displayed on:
- AO landing page
- AO search table
- Legal search results list

<img width="730" alt="screen shot 2017-03-23 at 11 24 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/24279390/fd2a36b6-101f-11e7-9eb6-3654ed41fbe4.png">


### MURs
Displayed on:
- Enforcement landing page
- MUR search table
- Legal search results list

<img width="707" alt="screen shot 2017-03-23 at 11 29 31 pm" src="https://cloud.githubusercontent.com/assets/11636908/24279513/9ce26106-1020-11e7-9a12-ef3bfca00400.png">

### ADR case search, Admin Fines case search, Admin fine calculator, Rulemaking document search
Displayed:
- As sections of the landing page for each type
[See Noah's comment above for the best explanation of this thinking](https://github.com/18F/fec-cms/issues/840#issuecomment-287894272)

Transferring over to you, Emileigh! Let us know if you want to pair up or have any questions on this

**Comment by emileighoutlaw** [comment]
After waiting patiently for two weeks, I finally have a [draft of some words](https://docs.google.com/document/d/1_c-zQyPUdNJ5LROl3BxpD71c5RKhLA5jvlb_oGh_6P8/edit#) 🔒 that we can look at for all of these things. 

👀  @AmyKort definitely needs to review these blurbs.

💟  And as always, I love having @jenniferthibault's and @noahmanger's smart copyedit eyes whenever they have time.

**Comment by noahmanger** [comment]
This all looks great to me.

**Comment by jenniferthibault** [comment]
This works for me! I left one very small comment.

**Comment by emileighoutlaw** [comment]
This content is approved by Amy and me. 🚀  We can move to implementation

**Comment by noahmanger** [comment]
Being implemented by https://github.com/18F/openFEC-web-app/issues/1900
