### ISSUE TITLE
Create S3 environment within fec-prototyping

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#848]
The purpose of this ticket is to create an S3 environment within fec-prototyping to move current fec.gov static files to. Ideally, we would have 3 separate instances, one for dev, staging, and production, as those spaces are already there. 

This will create an environment to develop changes during planning and also an external environment in which we can begin usability testing before the site flip.

**Comment by LindsayYoung** [comment]
I know you have use the s3 services before, but for reference here are the docs so you can have them handy https://cloud.gov/docs/services/s3/

Also, to be clear, we can make archive.fec.gov live well before the site flip, and I would prefer that. 

For static files, I don't think we need 3 instances because we are not trying out code. I think the workflow for this is to create the s3 bucket once you are happy with the ugly name version, we can add the naming rules to the proxy.  Though, if you have more development tasks than I understand, don't let me dissuade you from setting up multiple environments.

**Comment by noahmanger** [comment]
@patphongs this has been completed right?

**Comment by patphongs** [comment]
That's correct, it's all done and documented too. You can close, thanks!
