### ISSUE TITLE
Organizing documents and images in wagtail

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#851]
We need to create a way for users to be able to upload and organize images and documents in Wagtail. A solution that I have talked about with @noahmanger and @emileighoutlaw is to use Wagtail's collections feature. Which will allow users to easily upload a particular asset into a particular collection. For example, record images can go into a record collection.

![screen shot 2017-03-01 at 10 18 01 pm](https://cloud.githubusercontent.com/assets/12799132/23491555/f8b94554-fecc-11e6-8506-7767b78ea53a.png)

## Implementation criteria:
- [x] Taxonomy for collection naming
- [ ] Add documentation to the content guide for using collections
- [ ] Train users on how to use collections

**Comment by dorothyyeager** [comment]
This is a great idea and I meant to ask about it the other day. I know for us, we have three basic categories of images we use in Info, but some might be useful for others. (Categories are staff/Commissioners, state pics and seals for reporting articles, and pictures for conference/webinar promotion.) I don't know if you are thinking of organizing collections by office or topic, but hopefully that feedback is helpful.

**Comment by emileighoutlaw** [comment]
That's super helpful, @dorothyyeager! I'll definitely want to talk more when we dive into this next sprint 🐬

**Comment by emileighoutlaw** [comment]
I've been poking around taxonomy research and thinking about our specific challenges and needs for this  image organization, and I have some thoughts and tentative ideas:

**Goals** 
- Create image categories ("collections") that help content managers find images in Wagtail. 
- Create categories that don't overlap (i.e., when users upload new images, it's clear where the image fits in)

**Challenge**
Collections can only go one layer deep, so we can't have a collection within a collection. This is tricky, because it means our organization needs to be flat (not hierarchical). At the same time, we don't want to give people too many collection options to choose from (which we know can be overwhelming). 

**Approach**
I think it makes the most sense to organize images by the content of the image itself and not where in the site hierarchy the image is placed. 

_That means that when choosing a collection for Commissioner pictures, we'd prefer something called `Headshots` to something called `Leadership and structure`._

The reasoning here is that shared content could be useful in several sections of the website. 

_For example, a "reporting example" could be used in `Help for candidates and committees` as well as an `FEC Record` article. A commissioner photo might be needed for a press release. A thumbnail of a brochure cover could be used on several pages across several sections._ 

People do a good job of remembering lists of about [7 (plus or minus 2) things at a time](https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two), so shooting for a list of about 7 collections felt good to me. Here's what I landed on: 

<img width="1023" alt="screen shot 2017-03-27 at 3 50 39 pm" src="https://cloud.githubusercontent.com/assets/10552702/24377436/08a03544-1305-11e7-82f0-af0d49d7947f.png">

I would really really welcome any thoughts or feedback about this.

**Comment by noahmanger** [comment]
That makes a ton of sense to me! I'd also add that Wagtail has the ability to tag images with keywords, so there might be a way to make use of that as well.

**Comment by dorothyyeager** [comment]
That makes sense to me too. We have been using tags for Record article images and it's helped with finding them already. I'll put some thought into the ones we've used and see if I can make them consistent and useful. For the category state seals - maybe relabel "state and district images" - we primarily use them for special election Record articles but in case there are other uses for them, plus sometimes we use a map of a congressional district instead of a state seal.

**Comment by emileighoutlaw** [comment]
Adding @patphongs' notes that we need to account for documents, too:

Audits (Different types of audit documents)
Litigation (Court case documents)
Outreach (Webinar agendas and course docs)
Commission Meeting Documents (meeting documents, audio, transcripts)
Commissioner Statements(Both joint and individual statements from commissioners)

**Comment by emileighoutlaw** [comment]
So how about this for a revised list:


- Conference and training promotions (images)
- Headshots (images)
- Reporting examples (images) 
- Maps (images)
- Publication thumbnails (images)
- State and district seals (images)
- Statistics and charts (images)

.

- Audits (documents)
- Litigation (documents)
- Conferences and trainings (documents)
- Commissioner meetings (documents)
- Commissioner statements (documents)

**Comment by emileighoutlaw** [comment]
Quick ping for @patphongs' busy brain. Does that list (above) look helpful/complete to you?

**Comment by patphongs** [comment]
Sorry for the delay! Yes this looks good, if more categories come up, it's easy enough to add it too. We should ask the Content owners who own these docs if these collections will be enough for them.

**Comment by emileighoutlaw** [comment]
Great! I'll share with content managers on our Monday meeting, and add these categories to our collections
