### ISSUE TITLE
Figure out replacement for RAD lookup tool

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#870]
So that committees can directly contact their RAD analyst, implement a way for them to look up their analyst's name and contact information.

---

The current [RAD page](http://www.fec.gov/rad/) has this tool:
![image](https://cloud.githubusercontent.com/assets/1696495/23876320/235013a2-07fa-11e7-8f6e-1c00ee285d5b.png)

We were just discussing on Slack if this can be replaced with the new contact form or if it needs to be reimplemented. If it needs to be re-implemented, it can use the [existing API endpoint](https://api.open.fec.gov/developers/#!/filer_resources/get_rad_analyst).

**Tasks:**
- [ ] Figure out where it lives within the C&C Services experience

**Comment by AmyKort** [comment]
@llienfec

**Comment by nickykrause** [comment]
I missed the Slack conversation on this, but I am just catching up on it. I'm pulling some of it in here for reference.

> Pat: The contact form may be able to replace it if it can somehow returns the analyst for a particular committee? But that would have to be worked into the design.
> Noah: My question is around what RAD’s desired business process is. Do they want all requests to go through the form now? Or do they want to also allow direct contact?
> My understanding is that they'd like folks to be able to separately look up their analyst. But, llien and rhough are the experts. I don't think the form sufficiently serves both purposes.

^ So, although we have a contact form that allows users to submit questions to RAD, we're looking for a feature that allows users to look up their analyst. 

Some notes on the functionality of the current tool:
- It allows lookup by committee name and/or committee ID
- It does not offer a typeahead
- The results display the first and last name of the analyst, plus two phone numbers:
<img width="738" alt="screen shot 2017-03-15 at 8 59 22 am" src="https://cloud.githubusercontent.com/assets/1450173/23951925/becacd22-095d-11e7-87d0-0fd3f21510e6.png">
- The entire feature can be hidden

@noahmanger - Question. Is there any reason we couldn't offer a typeahead in our version of this search, as we do with other committee lookup fields on beta?

**Comment by noahmanger** [comment]
Yep, I was imagining a typeahead implementation so that you don't need separate fields for committee ID and name.

**Comment by nickykrause** [comment]
Okay! I worked on this some more and chatted with folks about it today during the design pairing. Thanks, all, for your thoughts.


## what we said earlier about the interactions
For documentation, I'd like to note that [this artboard labeled "Draft 1"](https://gsa.invisionapp.com/share/JTAWWYTDX#/224263288_Draft1) is what I shared today in the pairing meeting. We discussed the possibility of applying the filter patterns to do an on-page "search," and we realized a few things:
- We don't need to offer the ability to search for more than one committee (i.e., there probably isn't a user need for that)
- It would be a simpler implementation to offer just one result and the ability for users to "reset" the search if they wish to search a second time.


## what I changed about the interactions
In light of that, I have tweaked the designs to [Draft 2](https://gsa.invisionapp.com/share/JTAWWYTDX#/224263287_Draft2). 

Note a couple of things: 
- This is also now showing what might happen when there are no results found.
- The copy is of course still TBD

**Questions:** (cc @jenniferthibault in particular)
1.  Does this seem to violate any existing design patterns or stretch our existing patterns too far? 
2. Does it seem useful to offer the green/red "validation messages" that we offer for filters? (see image below). I left them out because it seems like a different context to me and that the interface is not complex enough for users to need the "assist" in understanding what is happening.
<img width="131" alt="screen shot 2017-03-17 at 3 39 04 pm" src="https://cloud.githubusercontent.com/assets/1450173/24062042/e36cff08-0b27-11e7-99ef-14b02d3726c9.png">
3. Any concerns or user needs I'm not thinking of? (maybe @llienfec will have thoughts?)


## And now...where do we put it?

Outside these interaction questions, we need to sort out where to put it. In the design pairing today, we talked briefly about [adding it as a "contact" section on C&C services](https://gsa.invisionapp.com/share/JTAWWYTDX#/224263286_Placement1), but...
- This didn't feel quite right because we've been trying to minimize showing special "contact" pages outside of the designated `contact` page, if possible.
- This perhaps raises the lookup tool to higher prominence than it needs (i.e., putting it in the side nav on C&C services is giving it a lot of weight).

We were running out of time in the meeting, but we asked if maybe this tool is sufficiently related to the `Submit a question to RAD` form to warrant living alongside it. I have mocked up [what it might look like to have the RAD form and lookup tool next to each other](https://gsa.invisionapp.com/share/JTAWWYTDX#/224263285_Placement2), but...
- It is not clear to me what this page would be titled, that could make the two pieces feel like they are "tied together"
- It is not clear which content element should be listed first

(cc @emileighoutlaw in particular, for these placement questions)

There may be other solutions as well, but I will leave this here for people to weigh in on these changes before exploring too far. 

cc @noahmanger @onezerojeremy, too, in case you want to chime in

**Comment by noahmanger** [comment]
👍 to the general interaction design. That looks good to me.

I think I like the placement on the contact form page. There might be a more general title for this page ("Additional support"? "Contact Reports Analysis Division"?).

The only other thing I could think would be making it a modal or something that could be triggered on any compliance page.

**Comment by noahmanger** [comment]
In the interest of moving this ball forward, does anyone object to starting with this on the contact form page as Nicky mocked up? That way we can make it and if it turns out people need it in more places, we can revisit?

**Comment by jenniferthibault** [comment]
No objections, it makes sense to group them together to me. I can see how some authorized representatives would prefer to contact their analyst directly by phone, and so would use that first and vice versa for email.

Here's a small tweak I might make to the selected committee & how to clear the form, which ties it more closely to checkbox entries and how users clear unchecked boxes in the data filters:

![screen shot 2017-03-21 at 11 13 51 pm](https://cloud.githubusercontent.com/assets/11636908/24180858/bc764134-0e8d-11e7-9447-ba89c294f231.png)


______________

There's something I haven't quite solved for yet, but there's a slight redundancy to me for authorized representatives here, who could either call their analyst, or be allowed to submit the form. But if you know your analyst, why might you submit a general contact and not go straight to them? I was trying to hash that out, and I think it's worth showing the early sketch, even though I was hitting a wall with what to do with the "All others" info then. Maybe it will spark ideas for other folks! 

![screen shot 2017-03-21 at 11 32 24 pm](https://cloud.githubusercontent.com/assets/11636908/24181004/ada82036-0e8e-11e7-9cc9-66c42f974d08.png)

**Comment by llienfec** [comment]
Looks amazing, all!  

@jenniferthibault   Your comments on redundancy brought out an interesting point - RAD hasn't done a great job of letting people know that when you submit a question through the RAD Form, your question goes to your assigned analyst (unless they are out of the office).

One request: in some of the designs above, the phone hours are listed under the analyst's name.  Those are the RAD open phone line hours, but not necessarily the hours that the analyst works.  We have the analysts put their hours on their voicemail to help set a committee's call-back expectation.  Can we use the design where the hours are under the Reports Analysis Division header instead?

**Comment by jenniferthibault** [comment]
@llienfec that is so helpful! Knowing that the form goes the that committee's RAD analyst anyways helps clear up what could happen. (And yes, can definitely position the contact hours with the Division instead of the individual, if the mock up below doesn't accomplishes what you meant, let me know!)

**How I understood the purpose of this page before**
A way to submit a question to RAD in general by form submission.

**How I understand the purpose of the page now**
A way to find and get in touch with your analyst, either by phone or form submission.

Based on this, I replaced the `Search for committee by name or ID` field with the `Committee name or ID` field from the form below. This way, we only ask users to complete that field once, and it acts almost as a Recipient field. Users who want to use the form continue filling it out and submit. Users who want to call can end their search right there.

I also tried my hand at editing the copy at the top to make this more clear, though I assume that will need review and tweaking!

> **Authorized representatives**
> If you represent a committee or another entity registered with the FEC, RAD staff can help answer your reporting questions. 

> Submit the form below and your committee’s RAD analyst will email you, usually within 3 business days. Or, for immediate assistance, use their provided contact information to call them by phone during business hours.

![screen shot 2017-03-22 at 10 02 22 am](https://cloud.githubusercontent.com/assets/11636908/24201546/bd24fbb2-0ee6-11e7-8d39-dbb4ae50226e.png)

How do you feel about this type of change @llienfec ?

**Comment by llienfec** [comment]
This is an interesting change @jenniferthibault   I like that it's basically saying that these two tools can be used to accomplish the same thing.  Since it's a change from what we showed today, I'd need to pass it around for a little buy in if you think this is the direction we should head in.  Easy to do.

If we do go this way, can you help us think of ways to make what the contact form is at the point where the contact form starts?  Would people be likely to stop at getting an analyst's phone number?  (I didn't word this section very well, let me know if it's confusing.)

**Comment by noahmanger** [comment]
I like including it on this page, but having both visible like this feels a little confusing. It makes me think it's all part of a single interaction, rather than alternative interactions. 

What if we only showed one at a time, either with accordions or the side tabs like on candidate pages?

**Comment by llienfec** [comment]
I like that idea a lot.

**Comment by jenniferthibault** [comment]
I was exactly proposing to make it feel like one interaction! That's a better way to say what I was trying to explain :)

- If people are only looking for immediate assistance and want their analysts phone number, they can stop at the first step because their need is met. 

- If people don't need immediate assistance, aren't in a good location to call, or otherwise would prefer email, they are going to need to provide their committee name anyways in the form. By using that as a first step, we can help people understand that their form is being sent to and reviewed by their analyst. (A piece that's missing otherwise)

If we have time and if this is of sufficient priority in the overall theme of how folks contact the FEC, I'd favor the following approach:

- Test it this way first is that it feels like "adding more" to compartmentalize the two. Start with the functionality feeling like one interaction, then see if it needs to be split into two after some quick usability tests. 
  - Task: They have a question about if a certain transaction qualifies as something to report, and the deadline is in 48 hours. 
  - Success = looking up their analyst to find the phone number and stopping their use of the feature. 
  - Failure = looking up their analyst and trying to continue to use the form below.

If we don't have the time to go that route, or if that's not the priority right now I think my preference is to try accordions first: 
- Place "Find your analyst" first, but keep the accordion panel closed. 
- Then the "Submit a question" panel second, and open. 
- Given what we know of accordions from previous tests though, I'm slightly concerned the "find your analyst" feature will be often overlooked.

Using tabs as the approach would hide the second option too much, and there's not enough content for "Find your analyst" to have its own page. DQ'd!

**Comment by noahmanger** [comment]
@llienfec given the option, would you prefer people call or email? If email, I like Jen's suggestion for the accordions, with the lookup featured first but closed. I'm worried we don't have the time to test and re-design, so I think picking something we feel good enough about to implement now would be good.

**Comment by llienfec** [comment]
@noahmanger Let's do accordions, closed call on top, open form below.  We just want it to be clear that if you need immediate help, use the phone.  If you don't, then use the form.  I like the language we already have written for those, so as long as the time expectations are clear, I think this is great to start with (and hopefully end with).

**Comment by noahmanger** [comment]
Great. Thanks @llienfec . I made a fresh issue for hammering out the remaining interaction details in https://github.com/18F/fec-cms/issues/934
