### ISSUE TITLE
Determine domains and paths for legacy pages

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#871]
This is a small task to finalize a decision for what the domain will be for the snapshot archive site and what the path will be for the legacy pages that will continue to live at fec.gov.

**Completion criteria:**
- [x] Decide on archive subdomain: transition.fec.gov
- [x] Decide on path for legacy static pages

**Comment by noahmanger** [comment]
After banging my head against a thesaurus, here's a strawman proposal:

- **transition.fec.gov:** The subdomain for hosting hybrid (i.e. liger) pages. I really can't think of a better term to capture the "transitional" nature of these pages. 
- **classic.fec.gov**: The subdomain for hosting the complete old fec.gov experience. Unlike "archive", "classic" doesn't carry strong connotations about being maintained or not, which makes it useful given the fact that some content won't be actively maintained, but the data will be up-to-date. We were originally saying "transition.fec.gov" for this, but I think that actually fits better for the first type.

Thoughts? cc @emileighoutlaw

**Comment by emileighoutlaw** [comment]
Helloooooo!

- I'm major thumbs up to `transition.fec.gov` for the hybrid (liger) pages.
- I'm still waffling on the new name for the old fec.gov pages

After some discussion, our content team decided `legacy.fec.gov` might possibly come off as derogatory (depending on context). They loved `classic.fec.gov`, but I totally hear @amykort's reticence about that one. 

Amy, I know you threw out a few suggestions in the meeting, but I can't remember them. 

It's really really tough to get at something being and old version without implying it's outdated. Any of these excite or spark ideas?

`throwback.fec.gov`? `traditional.fec.gov`? `vintage.fec.gov`? `heritage.fec.gov`?

**Comment by johnnyporkchops** [comment]
How about sunset.fec.gov

**Comment by AmyKort** [comment]
I think all of my suggestions were bad, which is why I said them so quickly.

After beating my head against a thesaurus, I am thinking things along the lines of former.fec.gov or previous.fec.gov. 

traditional.fec.gov would work.

I like John's idea for sunset.fec.gov. 

We can still go with classic.fec.gov, if we don't come up with something better. 

aughts.fec.gov or earlytwentyfirstcenturyversionof.fec.gov (kidding on both)

I was looking into something that said "prior version" but was also one word.

This is hard.

**Comment by emileighoutlaw** [comment]
`sunset` has a really specific meaning for content projects, but since it means phasing something out or terminating it over time, it might actually work for this? We _are_ planning to sunset these pages in time. 

What do you think @noahmanger ?

**Comment by noahmanger** [comment]
It wouldn't be my first choice, but at the end of the day I don't care that much, so whatever works best for the most people.

**Comment by emileighoutlaw** [comment]
I'm also starting to feel fatigued thinking about this. What's your first choice, Noah? classic.fec.gov? And are we willing to just go with sunset.fec.gov, if Amy and John think that's a better option?

**Comment by amypike** [comment]
If you are looking for another opinion, I like what @emileighoutlaw said about @johnnyporkchops suggestion of "sunset," because of the specific meaning for content projects.  I think that makes the name accurate (we are planning to sunset these pages), a little aspirational (no really, eventually, they WILL go away, we promise) and funny (ha, ha, what is funnier than a good sunseting regulations joke?).    @AmyKort

**Comment by amypike** [comment]
Answer: A FOOTNOTE joke. @AmyKort

**Comment by noahmanger** [comment]
You know, the more I think about it, the more I think sunset works well. So I'm game!

**Comment by emileighoutlaw** [comment]
Just as a content update: FEC is game to try `classic.fec.gov` for the legacy URL if that's the direction our team wants to take. I know Pat is also working on a couple possible options.

**Comment by AmyKort** [comment]
We've come around to preferring classic to sunset, if those are the two options in front of us.

Also, this is really hard! Let's make this the last thing we ever try to name.
