### ISSUE TITLE
Design placement of committee guides on C&C Services landing

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#874]
So that users can easily find the committee guides relevant to the committee types that we don't have content for yet, design a place to highlight them on the C&C Services landing page.

--

**Completion criteria:**
- [x] Designs ready for implementation
- [x] Update https://github.com/18F/fec-cms/issues/873 with the new designs

**Comment by jenniferthibault** [comment]
I took an educated guess at what guides we needed to show (assuming it's the same as what's live on Registration and Reporting now) and saved the changes as a draft in Wagtail.

@emileighoutlaw please take a look! The surrounding copy or title structure may need some tweaking.

![screen shot 2017-03-22 at 11 00 18 am](https://cloud.githubusercontent.com/assets/11636908/24204449/f76e5126-0eee-11e7-8641-502ddda627c2.png)
![screen shot 2017-03-22 at 11 00 35 am](https://cloud.githubusercontent.com/assets/11636908/24204450/f771c234-0eee-11e7-8152-5979e93bc6bf.png)


@noahmanger seeing the linked PRs out from #873 , I'm a little confused. Is this being implemented in HTML or Wagtail?

**Comment by noahmanger** [comment]
Awesome. This is actually already fully implemented in Wagtail, so we can just make the change there.

@emileighoutlaw given the conversation we just had, should we also include the candidate guide as well?

**Comment by AmyKort** [comment]
Yes, please include the Candidate Guide as well. Thanks!

**Comment by jenniferthibault** [comment]
@noahmanger can you share some of the thoughts from the convo on why it's needed? It will impact the overall design if the guides are meant to be permanent features that need to live with the bulleted list at all points, or if they are temporary, and will be replaced by the bulleted section content as it's available.

**Comment by emileighoutlaw** [comment]
I can share thoughts — there's a whole world of content about the act of filling out FEC forms that's in the candidate guide that we're just now digging into. 

Since that "filling out forms" content is turning into another really substantial chunk of content (that we haven't built or thought about yet) I didn't want it to be a hold-up for publishing this section. But if it isn't included in our first release, we still need the candidate guide to fill in the gaps.

**Comment by noahmanger** [comment]
If we're using the existing Wagtail components that we've used for sidebar thumbnails, here's how it looks:

![image](https://cloud.githubusercontent.com/assets/1696495/24213928/4547f0f8-0ef1-11e7-8b28-c30ac2d129f8.png)

**Comment by jenniferthibault** [comment]
Ha, I just went into Wagtail and did the same thing. 

In that case @emileighoutlaw does it make more sense to embed the guide on the "Filing reports" page? Or wherever is relevant to the missing info instead of right up front as an enticing click target?

My concern is that the guide is a very alluring thing to click on here. Pictures! So it could be a misleading route to take folks on first if most of the info is available to them in an easier format through the sub-pages.

**Comment by noahmanger** [comment]
I hear that. But on the other hand, we know that the guides are incredibly valuable for folks, and I worry that if we present the other guides up front but _not_ the candidate guide, it will be confusing. I suppose it's ultimately a matter of content strategy: do we _not_ want people using the guides if there's other info? Or do we want people to get the info via whichever method is most comfortable?

**Comment by AmyKort** [comment]
I think we weren't meaning to signal to folks that we were retiring the campaign guides in favor of the sub pages. I'd prefer to have all the guides on the landing page. I think we were hoping to let people choose to access the information by whatever method was most comfortable for them. For me, a 198 page pdf file is not choice number 1 (control F is my best friend!), but I worry that if we take down parallel access to the campaign guides on this page, we might be signaling something we don't intend.

tagging @amypike

**Comment by amypike** [comment]
Yes, that makes a lot of sense, @AmyKort .  There just isn't enough content "meat" on the bones of these pages, yet, and the "meat" is found only in the Guide.  I would hate for users to be unable to find the answers to their questions.   I remain confident @jenniferthibault that eventually, most of the info available will be available to users in an easier format through the sub-pages and we won't be so Guide-dependent.

**Comment by emileighoutlaw** [comment]
From a content strategy perspective, I think this is a 6 of one half a dozen of another situation.

On the one hand, Jen is right that having the picture PDF will inevitably be appealing to some users (which won't be to their benefit, since newbie won't know it's 200 pages just from looking at the link)
On the other hand, Noah is also right that embedding the guide in a different place could be confusing because it's inconsistent

So I think Amy and Amy tip the scales toward having it on the landing pages for now.

**Comment by jenniferthibault** [comment]
👍 makes sense. Sorry for possibly roping in so many people, just wanted to make sure it was in the right spot for now!

**Comment by noahmanger** [comment]
Awesome. And I see someone already implemented, so going to go ahead and close.
