### ISSUE TITLE
Visual design of two-site experience components

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#878]
So that users can always stay oriented as they traverse the new and old experiences after the flip, polish the design of components like banners and links. 

---

These are the components I believe we need to account for (cc @jenniferthibault ):
- [x] Banner on new site (expanded and collapsed state)
- [x] Banner on "liger" pages
- [x] Banner on archive site
- [x] Any components we want to use _before_ the flip
- [x] Links? (I can't remember if we decided we were styling these separately)
- [x] Finish copy

**Comment by jenniferthibault** [comment]
**Additional components post & during flip already designed:**

- Legal alerts in https://github.com/18F/fec-cms/issues/840
- Candidate and committee services alerts in https://github.com/18F/fec-cms/issues/836

On @patphongs 's guidance, it seems that placing elements below the old FEC nav is much easier, which is a constraint I've designed around in the following mockup.

## Components for pre-flip
- Banners that emphasize the timeline for flip, opportunities to try beta, ask questions, and give feedback from both sites. 
- Menus that start expanded, then collapse. Users would receive a cookie if they've already visited and minimized the alert so that next time they load the page it defaults to minimized


![screen shot 2017-03-23 at 5 02 42 pm](https://cloud.githubusercontent.com/assets/11636908/24270359/34e938de-0feb-11e7-8691-d90b4641a1a6.png)

## Components for flip & post-flip
- Banners that emphasize the change has already taken place, there's an opportunity to access the previous site experience, and that some content is no longer maintained.

![screen shot 2017-03-23 at 5 03 07 pm](https://cloud.githubusercontent.com/assets/11636908/24270437/8a55dc78-0feb-11e7-9e92-e87d9fe433c3.png)


### Hybrid pages
- Display new FEC.gov flip banner, "breadcrumb-like" trail to the page they just visited from, faux sub-nav to other hybrid sections, and up-to-date information

![screen shot 2017-03-23 at 5 03 17 pm](https://cloud.githubusercontent.com/assets/11636908/24270513/d547b706-0feb-11e7-80ac-1845b09c6ca8.png)

## Next steps
- Did I miss any states that need visualizing?
- Is everything I've proposed feasible given our timeline & capacity?
- Language will need to be reviewed for all of these, but I took a first stab at what we _might_ do. I think @emileighoutlaw will want to choreograph her own editing process for this language, so it's most useful to have feedback on the visuals and interactions for now. 
- Note: In places where the mockups here differ from the prototype in https://github.com/18F/fec-cms/issues/877, consider this issue the most up to date thinking. (i'll try to keep the prototype updated!)

**Comment by noahmanger** [comment]
Small language thought: instead of "betaFEC is now fec.gov" what about just "Welcome to the new fec.gov". That way we're not banking on people understanding what betaFEC was? 

The "Back to previous page" might be a little tricky, both technically and UX-wise. For instance, when you've clicked through a few levels, does it always take it back to the last new page you were on? If so, maybe it should say the name of the original page? 

Technically, I think we could make it work by passing URL parameters in links to hybrid pages. Just a matter of time.

Otherwise, looks good!

**Comment by jenniferthibault** [comment]
I'll leave the language thoughts for Emileigh to pick up at the right point in time.

On "Back to previous"—that's something I took directly from @nickykrause & @onezerojeremy 's [mockups in InVision](https://gsa.invisionapp.com/share/KMAR2WZSF#/screens/222549089) so I assumed it had been sussed out already 🤔 What say you, Jeremy & Nicky?

<img width="701" alt="screen shot 2017-03-24 at 11 45 19 am" src="https://cloud.githubusercontent.com/assets/11636908/24301986/6d2fe002-1087-11e7-8a18-0b5e37c682c3.png">

**Comment by patphongs** [comment]
@jenniferthibault These are looking great! Thanks for sharing. Just wanted to loop in folks who were not at our design meeting today that the "< Back to previous page" button works exactly like your browser back button. Sounds like everyone liked the redundancy of the feature? We can always take it out later if needed.

**Comment by patphongs** [comment]
@jenniferthibault In the implementation of the "Show more" and "Show less" buttons on the banner, do you intend it to always be open by default when you come to the page. Or if you've collapsed it once, to remember it being collapsed and to always have it minimized unless it was explicitly maximized again? I believe in the invision mock ups from @nickykrause there were buttons to "minimize this message" and "minimize this and don't show me again". 

I think on first launch, it's nice to advertise the start the tour option, but I'm not sure how persistent that message should be?

**Comment by jenniferthibault** [comment]
Good clarification—Since Nicky's out one more day, I can give my best guess. 

I think the banner should display open on first visit. When someone minimizes it, the site should remember that (through cookies?) until the next phase (flip) so that on their next visit the banner is still minimized.

Whenever the content of the banner is updated and new, the cookies should be reset and the banner should present open on page load again. That way, new messaging will be signaled by the banner appearing again.

Given timelines, I don't think the "don't show me this again" is something we want to pursue, since otherwise there'd be no way for the user to later decide they *do* want to start the tour and get back to it. That would have been good if we were implementing this a little further in advance.

**Comment by noahmanger** [comment]
Remaining tasks here:
- [ ] Finish copy
- [ ] Determine if we want to do anything about link styles

**Comment by jenniferthibault** [comment]
Quick synced with Nicky and Jeremy, and since we're pursuing the hybrid approach, we don't need unique link styling—that was only for the mirrored approach. No more visual/UX needed!

**Comment by emileighoutlaw** [comment]
Getting in some content thoughts about the pre-flip components now. I'll add notes on the post-flip components early next week. 

❔ Can we be upfront about what the archive site URL will be? I've added it below, because I think it's kindest to tell people where they'll be able to find the archive design rather than asking them to trust us that it will exist but not yet giving them the pathway. Although y'all can tell me that we can't do that, too.

:pen: The hardest thing about this content is the "this site" "that site" pronoun ambiguity and shifting "FEC.gov" meaning. So that's what I'm really trying my hardest to make clear, and if it isn't clear, we should keep workshopping.


## Components for pre-flip

### beta.fec.gov
<img width="862" alt="screen shot 2017-03-31 at 4 31 32 pm" src="https://cloud.githubusercontent.com/assets/10552702/24570132/86ea29dc-162f-11e7-9e12-d31e2a27a80b.png">

> **30 days** until this site becomes the new FEC.gov.

> On May 1, 2017, the [current FEC.gov](url) will be archived and made available at classic.fec.gov. Our team _won't_ be updating or adding new content to the archive site.

> Questions or comments? Please let us know— send a note using our [anonymous feedback tool]() or by emailing [betafeedback@fec.gov](url).


### FEC.gov
<img width="853" alt="screen shot 2017-03-31 at 4 31 37 pm" src="https://cloud.githubusercontent.com/assets/10552702/24570134/881d7a5c-162f-11e7-8b1a-10d2da2b1152.png">

> On May 1, 2017, [betaFEC](url) will become the new FEC.gov.

> After that day, an archive copy of this website will be available at classic.fec.gov. Our team _won't_ be updating or adding new content to the archive site.

> Questions or comments? Please let us know— send a note using our anonymous feedback tool or by emailing betafeedback@fec.gov.

**Comment by jenniferthibault** [comment]
- I think we can be upfront about the URL now that we know it! Love that directness.

One small bit that's not quite accurate about the descriptions above is this part:
> Our team _won't_ be updating or adding new content to the archive site.

Some parts of the site (like most of the legal apps and the data apps, possibly select content pages, but I'm not 100% sure) will continue to be updated, but some won't, which is why these banners will appear on classic.fec pages:

![screen shot 2017-03-31 at 6 38 44 pm](https://cloud.githubusercontent.com/assets/11636908/24571758/59da8b50-1641-11e7-9af3-c73a4f68efad.png)

**Comment by emileighoutlaw** [comment]
Arg! So complicated! 

The hope of that sentence was to clarify a bit more about _why_ this switch is important, but I don't think it's as valuable if we have to either be short and vague (_some sections are no longer being maintained_)  or take up a lot of space explaining exactly what's happening (_X, Y and Z things are being updated but other sections of the website are not_). 

Excluding this detail would leave us with something like:

### beta.fec.gov
> **30 days** until this site becomes the new FEC.gov.

> On May 1, 2017, the [current FEC.gov](url) will be archived and made available at classic.fec.gov. 

> Questions or comments? Please let us know— send a note using our [anonymous feedback tool]() or by emailing [betafeedback@fec.gov](url).


### FEC.gov
> On May 1, 2017, [betaFEC](url) will become the new FEC.gov.

> After that day, an archive copy of this website will be available at classic.fec.gov.

> Questions or comments? Please let us know— send a note using our anonymous feedback tool or by emailing betafeedback@fec.gov.

**Comment by jenniferthibault** [comment]
Thanks for moving to the google doc—I dropped in some questions, but I think we're really close!

**Comment by patphongs** [comment]
@jenniferthibault I've completed the styling for both desktop and mobile for the transition pages. It's ready for your review (see screenshot below). You can also access a live version here (https://fec-dev-transition.app.cloud.gov/), although it doesn't have all the content yet as it was just for dev purposes. 

Please ignore the banner as @xtine is working on the new banner and I will replace it with her version.

<img width="1436" alt="screen shot 2017-04-05 at 11 48 37 am" src="https://cloud.githubusercontent.com/assets/12799132/24714266/032dd8ee-19f6-11e7-806d-3a86e8ef3a92.png">

<img width="404" alt="screen shot 2017-04-05 at 11 49 28 am" src="https://cloud.githubusercontent.com/assets/12799132/24714265/03291e94-19f6-11e7-8ab3-11cfe7f67a0f.png">
