### ISSUE TITLE
Design and microcopy of error pages for two-site experience

### ISSUE THREAD

**Issue by nickykrause** [18F/fec-cms#881]
This issue stems from the original two-site experience issue (https://github.com/18F/fec-cms/issues/835). 

We are still in the process of deciding which two-site strategy we will pursue (Liger or Mirror), and Pat is currently working on the Liger prototype to help us make this decision (see https://github.com/18F/fec-cms/issues/878).

Regardless of which strategy we pursue, we will need to think through the design and microcopy for error pages (e.g., 404 and 500 pages), including whether or not there will be adjustments needed to the error pages on the legacy site. 

Completion criteria:
- [x] An understanding of the error pages that need design and microcopy (e.g., new site 404, new site 500, old site 404, etc.)
- [x] Designs for each page
- [x] Microcopy for each page

**Comment by emileighoutlaw** [comment]
Swooping in with content thoughts!

# 404
<img width="652" alt="screen shot 2017-03-16 at 11 59 19 am" src="https://cloud.githubusercontent.com/assets/10552702/24009508/38679832-0a43-11e7-9428-e9a34a6c95ba.png">

^^ is our current 404 message. I’m recommending a few small changes in our approach. 

Previously, we had the very friendly “Oops,” leading us off. But that feels tonally off from where the rest of our site content landed. Additionally, when we take into account how people will be feeling after a site switch, something straightforward feels most empathetic.

I am hopeful that a single 404 might message could work for the both the new and old site, but I’m curious to hear more about why we might want different messages (I fear that different messages could add to the already confusing, two-site experience).

Proposed new 404:

> ## Page not found
> So sorry, but we couldn’t find what you’re looking for. Please double-check the URL and try again. 
> ——— 
> Still not working? FEC.gov is in the middle of a redesign. We've worked hard to keep all our URLs up to date, but please contact our team if you think something is broken or missing.

> [Return home] [Email our team] [File a GitHub issue]

I struggled here to think of a clear way to explain why a page might have gone wonky in our migration. So I'm open to critique about that part especially. 

Little notes on the contact buttons: I put email before GitHub, because I think that will be useful for more folks. I also added “GitHub” to the button copy, because I have a hunch that `[File an issue]` won’t be easy for non-technical folks to differentiate from `[Email our team]`.


# 500 
h/t @ccostino, for talking me through 500 errors at the end of his busy day. I'm playing around with some new ideas here, but I thought it would be nice to try an approach that clearly states:
1. This sucks
2. This is our issue, not the user's
3. Our tech team is usually notified about these kinds of errors automatically 
4. Users can still reach out to us, if they want

> ## Server error
> So sorry, but this page failed to load. This happened because of an internal error, and our web team has been notified. Please try again, and thanks for your patience. 

> [Return home] [Email our team] [File a GitHub issue]

**Comment by noahmanger** [comment]
Agree with everything @emileighoutlaw said about tone and content above. What about also including a link to the archive site?

**Comment by emileighoutlaw** [comment]
I'm neutral about the archive site, only because:
- It adds an extra option folks have to choose from 
- We know it's hard to explain the difference between the new home and old home, and it seems likely that we'd have to add a sentence or two explaining which is which on the error message, which makes for more user time reading and processing info
- We are providing a clear pathway to the old experience from the new home, if folks want it

But I could also be convinced this is important to the user experience, if other folks think so?

**Comment by noahmanger** [comment]
Those are all good points. The only reason I'd still argue for it is that I think there's benefit in providing as many alternate "escape routes" out of an error page, but wanna hear what others think.

**Comment by emileighoutlaw** [comment]
Sure thing. I do think having four button options is probably too many, and the text is starting to feel pretty long, so here's a tweak with the contact info pulled into the paragraph text and just two options for visiting the homepage or the archived site. 

_Note: Explaining the archive site felt too long to put on a single button, which is why you see it as both a button and a line of text with a hyperlink. Otherwise the button options would have been: 
`[Return home]` `[Try searching an archive of the previous fec.gov design]`_

# 404
> ## Page not found
> Sorry, we couldn’t find the page you’re looking for. 

> fec.gov is in the middle of a redesign. We've worked hard to keep our URLs up to date, but please let us know if you think something is missing or broken. We're available by [email](url) or [GitHub](url). 

 > [Return home] or try searching an archive of the [previous fec.gov design](url).



# 500 

> ## Server error
> Sorry, this page failed to load. This happened because of an internal error, and our web team has been notified. Please try again, and thanks for your patience. 

> If you'd like to contact our team, we're available by [email](url) or [GitHub](url). 

 > [Return home] or try searching an archive of the [previous fec.gov design](url).

**Comment by noahmanger** [comment]
Love it.

**Comment by emileighoutlaw** [comment]
I think we're ready for design, then, although since we already have designs for these pages, I'm not sure how much needs to be updated.

**Comment by noahmanger** [comment]
@jenniferthibault do you want to take a pass?

**Comment by jenniferthibault** [comment]
Sure! Nice copy work, I think the final version is an improvement over all those buttons.

One content observation—FEC.gov is always capitalized, from what I remember of things, so I added that.

![screen shot 2017-04-04 at 6 50 37 pm](https://cloud.githubusercontent.com/assets/11636908/24682441/c4f0172e-1967-11e7-8619-8ba7cf1976e6.png)

On the classic.FEC.gov side, I agree that we can use the same messaging, but keep their format with one tweak to existing: I think we should ask them to stop the auto-redirect from the 404 pages that brings you back to the home page after a few seconds. That way users have enough time to read and determine their own navigation path. Thoughts?

<img width="1264" alt="screen shot 2017-04-04 at 6 52 43 pm" src="https://cloud.githubusercontent.com/assets/11636908/24682518/270f9cae-1968-11e7-81ac-a211519d6331.png">

**Comment by noahmanger** [comment]
These look great. I vote we move to implementation.

**Comment by noahmanger** [comment]
Implementation issue here https://github.com/18F/fec-cms/issues/966
