### ISSUE TITLE
Update fec.gov links to transition.fec.gov links

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#927]
One the transition hybrid pages are up at transition.fec.gov we need to replace all links that currently go to the old site (fec.gov) to go to the transition pages. 

For link re-writing, there's three use-cases we need to account for:

1. Links that currently link to something on fec.gov (an AO, a Record article) that has a replacement on the new site. These should be re-written to link to the new instance instead.
2. Links that currently link to something on fec.gov that will need to link to transition.fec.gov
3. Links that currently link to something on fec.gov that will need to link to classic.fec.gov 

I'll leave it to @patphongs and/or @LindsayYoung to weigh in on the best method to do this, considering different options available like 301 redirects or changing the hard-coded values. 

Whatever we do we need to account for:
- Hard-coded link values in any template (including potentially JS) files
- Links in CMS database content

**Completion criteria:**
- [ ] Update all links to their correct values

**Comment by LindsayYoung** [comment]
To clarify, redirects are a different task, that should be completed first and that gives us time for this task because if we don't find all the links right away, it will still be ok because they will redirect to the right place under our general rules. Though this task should still be done to keep the html clean.

#cms data content
We will want to make the rewrite rules and then loop through the text data in the CMS finding and replacing those links with the correct, relative link.

We started on a function here:
https://github.com/18F/fec-cms/blob/develop/fec/home/utils/link_reroute.py

We started making a task to loop through the models and apply the funcion (This has some sqlite specific stuff in it so this might be less important) - https://github.com/18F/fec-cms/blob/develop/fec/data_loader/management/commands/remake_links.py

# Links in the code
We will want to look for those manually in all the repos

**Comment by noahmanger** [comment]
Task for now: Update www.fec.gov links set in CMS pages to transition.fec.gov .

**Comment by AmyKort** [comment]
@llienfec for transparency

**Comment by llienfec** [comment]
Thanks.  Meeting with @patphongs tomorrow AM to talk about where we're at.  Then will keep going w/ making changes as needed.

**Comment by AmyKort** [comment]
Awesome! Let me know when/how you want more folks helping out with this!

**Comment by llienfec** [comment]
Legal resources is done for the most part.  I have a couple of questions outstanding that I'll see if @emileighoutlaw is available to pair on.  Will let @AmyKort know when it's ready to review.  Dorothy is making good headway on the Record and press releases.  Help for Candidates and Committees will be done soon.
