### ISSUE TITLE
Design meeting agenda view for latest updates feed

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#932]
This issue is to design how meeting agendas should show up in the latest updates feed. Agendas pose a few constraints but also some opportunities:

Here's [an example](http://www.fec.gov/agenda/2016/agenda20161208.shtml) from the current site
- I don't think it makes sense to pull in any body text as a snippet
- I do think it could be helpful to include links to things like:
  - Video
  - Audio
  - Captions
  - Sunshine notice
  - Draft Minutes
  - Approved minutes

An idea:
![image](https://cloud.githubusercontent.com/assets/1696495/24382544/cf023c40-130b-11e7-9ff3-e018899d823f.png)

Determine:
- [x] Title ("Open meeting agenda"?)
- [x] What to include in the body
- [x] "From: ..." - should it be Info Div?

**Comment by jenniferthibault** [comment]
## Categories & tags
I first started looking at how many different types of things are in this category, and it looks like there are three, based on what we set up in the [calendar](https://beta.fec.gov/calendar/):

<img width="299" alt="screen shot 2017-04-06 at 5 27 26 pm" src="https://cloud.githubusercontent.com/assets/11636908/24776380/7873f126-1aee-11e7-8227-8115ef600450.png">

But looking at an an existing page for a public hearing shows that public hearings seems to be a sub-type of an open meeting: http://www.fec.gov/agenda/2016/agendaaudithearing20161206.shtml

To be consistent with the model we set up in the calendar, I think the parent category should be `Commission meetings`. This is also already in the template, woo! The sub-categories would be `Open meetings` and `Executive sessions` Each has a slightly different intro blurb that would need to be added to the page template (manually, or templatized, idk?)

This also means we need sub-section drop down changes to the feed filters.

## Page titles
Since the model is now that the page is about the meeting event & all it's associated documents, we should drop "Agenda" from the page titles, and use only the type of session it is. This keeps things more broad:

![screen shot 2017-04-06 at 5 26 58 pm](https://cloud.githubusercontent.com/assets/11636908/24776427/c5435f28-1aee-11e7-94fc-b9ccbd420a68.png)

## Body 
I was first thinking that we could keep the preview items simple, as shown above to mimic the Weekly Digest items, but I could see value in @noahmanger 's suggestion above to bring in documents or transcript options as they are made available. Let's do that, but put two spaces on either side of the pipe character for cleaner separation `x  |  y  |  z`

If we had everything, that would look like this:
![screen shot 2017-04-06 at 5 44 37 pm](https://cloud.githubusercontent.com/assets/11636908/24776873/c7f4ef78-1af0-11e7-9126-0ca5a3d1d97d.png)

## From office
One field I think we should exclude here is the "From: Office" field—these aren't published by a specific office like other departmental publications, but are published by the Secretary and Clerk of the Commission. I'm not certain that this adds value to know.

Thoughts?

**Comment by johnnyporkchops** [comment]
I like this design and agree with the  suggested links to include

**Comment by noahmanger** [comment]
Sounds like we have a design! Closing.
