### ISSUE TITLE
Design RAD lookup tool interaction

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#934]
So that users know the best way to get in touch with their RAD analyst, complete the interaction design for the RAD lookup tool.

---

In https://github.com/18F/fec-cms/issues/870 we decided that the RAD analyst lookup tool would be in an accordion above the RAD contact form. Rather than jump to implementation though, I think it would be helpful to do one final pass at design to make the implementation easier. 

**Completion criteria:**
- [x] Design accordion interaction
- [x] Show empty (starting) state of tool
- [x] Show success state of tool
- [ ] ~Show error state~ don't need error state since it will only work with a valid committee selection

cc @jenniferthibault @nickykrause

**Comment by nickykrause** [comment]
Okay, I _think_ I translated the other issue thread properly. Thank you all so much for evolving this while I was out! I think we went a good direction.

Rather than pasting them all here, I put the screens [into an InVision](https://gsa.invisionapp.com/share/JTAWWYTDX#/226750744_RAD-Tool-1). 🎨  It doesn't exactly mimic the interaction, but I think it conveys the idea.

Some notes/question about the interaction:
- Does this seem to reflect where we landed in #870? Or am I missing something you all discussed?
- @jenniferthibault - Instead of labeling the sidebar info `ALL OTHERS`, I just labeled it `GENERAL INFORMATION`. I hope this still gets at what I think you were saying? I interpreted the layout to mean that the body content is relevant to `Authorized representatives`, while the sidebar info is for "anyone at all" (rather than everyone _else_, or "all others").
- I am assuming that the accordion would work the same way that our filter panel accordions work, where opening one would not automatically close the others. (So, they need to be open/closed manually.)
- @jenniferthibault - I like the adjustment that you made to the method for clearing the form, in the sense that it functions more like the filters we have now, with the "X" to clear:

![image](https://cloud.githubusercontent.com/assets/1450173/24555166/c4f398a6-15f5-11e7-975c-6ad6eda63359.png)

The only thing I'm not sure about is if this suggests clearly enough that only one committee can be added. It's so close to the filter behavior that we have elsewhere, which _does_ allow multiple filters to be added, that I wonder if it will seem like adding multiple is possible. With the previous iteration, I was trying to assert that there is one committee that can be `selected` at a time: 
![image](https://cloud.githubusercontent.com/assets/1450173/24555275/14cf7aa2-15f6-11e7-91b0-aedf5941cfa7.png)

All that said, I do like the consistency of the filter pattern, and I don't really know if users would ever really try to enter more than one committee. Still, if it's not going possible for them to do that, then it seems like it should be clear. 

We could...
1. Visibly disable the search box after a committee is selected, so they know to clear the first filter to activate it again
2. If they enter another committee, automatically remove the first one and replace it with the new one
3. Present some kind of error if they try to enter another committee
4. Let them enter more than one committee and adjust the results display so they know which analyst aligns with which committee
5. Leave it as-is and test it

I would vote for 1, 2, or 5, but I am curious what others think.

**Comment by nickykrause** [comment]
Okay! Chatted about this today in the design pairing. 

Latest design: [InVision](https://gsa.invisionapp.com/share/JTAWWYTDX#/226750744_RAD-Tool-1) :art:

Some notes:
- The `submit a question` accordion is open by default
- All of the `submit a question` fields look and behave the way they do now
- When the user switches between accordions, the old accordion section should close when the new accordion section opens. So, there is only one accordion open at a time. 
- When a user searches for a committee, a typeahead appears to help with selection
- When the user selects a committee, the campaign finance analyst information populates in the space below. 
- The selected committee stays in the search field unless the user clears it
- Users can search for only one committee at a time

A few screenshots, if you prefer not to open the InVision:
---

<img width="532" alt="screen shot 2017-03-31 at 1 21 30 pm" src="https://cloud.githubusercontent.com/assets/1450173/24563719/0c9c09b2-1615-11e7-8e4a-26a3955a5bca.png">

---

<img width="371" alt="screen shot 2017-03-31 at 1 21 46 pm" src="https://cloud.githubusercontent.com/assets/1450173/24563723/10b1f868-1615-11e7-963a-40adc5a7d31d.png">

---

<img width="371" alt="screen shot 2017-03-31 at 1 21 50 pm" src="https://cloud.githubusercontent.com/assets/1450173/24563729/145e2f0e-1615-11e7-9fec-59ef14b91b6b.png">

---

<img width="372" alt="screen shot 2017-03-31 at 1 21 55 pm" src="https://cloud.githubusercontent.com/assets/1450173/24563732/17b2c912-1615-11e7-80d9-156ebc0f9836.png">

**Comment by noahmanger** [comment]
This looks great. Moving to implementation https://github.com/18F/fec-cms/issues/961

**Comment by jenniferthibault** [comment]
+ 👍
