### ISSUE TITLE
Design site search in header

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#935]
Since it appears that we'll be able to make DigitalGov search work for our needs, in part by enhancing it with our candidate and committee typeahead results, we should design how this will actually look and work. 

It's easy to make both candidate and committee results show up as suggestions, and could be possible to have a third category that triggers a search of itemized receipts for the search term, like:

![r](https://cloud.githubusercontent.com/assets/1696495/24383973/65acf58c-1315-11e7-87ad-9be60d64f687.png)

Pieces to consider in the design:
- [x] Where does it live?
- [x] Does it collapse/expand?
- [x] How does it work on mobile?
- [x] How is it labeled?
- [x] Should we remove the search bars in the breadcrumb bars in the /data section?

**Comment by onezerojeremy** [comment]
From an IXD perspective, it might also need a "search _compliance content_" or "search everything" 

* - compliance content is the kind of stuff, not necessarily the microcopy

**Comment by jenniferthibault** [comment]
The first questions I've been asking of myself is how the search is presented at first glance & how it works at first interaction.

**Is it always exposed?**
- Hypothetical pro: Single click between spotting it and starting to type
- Hypothetical con: Maybe a bit too prominent and enticing as an alternative to using the navigation
![screen shot 2017-04-11 at 4 35 46 pm](https://cloud.githubusercontent.com/assets/11636908/24929778/27db878e-1ed5-11e7-9d5a-bec28b7b8b93.png)


**Does it reveal progressively on click?**
- Hypothetical pro: Keeps the layout cleaner, is prominent when you look for it, but not overly alluring
- Hypothetical con: two clicks to start using it is more than one click
![screen shot 2017-04-11 at 4 35 56 pm](https://cloud.githubusercontent.com/assets/11636908/24929980/dfcab2f2-1ed5-11e7-8387-7997c3111145.png)
![tlnrg](https://cloud.githubusercontent.com/assets/11636908/24929992/e9816228-1ed5-11e7-9423-95cf40c07b5f.png)

**Is it actually a button that opens a panel?**
- Hypothetical pro: Keeps the layout cleaner, allows more space for text entry
- Hypothetical con: Two clicks is more than one click—requires more screen shifting on mobile
Like these two combined (the second is a very old mockup, sorry)
![screen shot 2017-04-11 at 4 35 56 pm](https://cloud.githubusercontent.com/assets/11636908/24930041/23eee57a-1ed6-11e7-97dd-11d152ce4ef0.png)
<img width="767" alt="screen shot 2017-04-11 at 4 43 53 pm" src="https://cloud.githubusercontent.com/assets/11636908/24930043/23f2fc32-1ed6-11e7-92fb-8731087cc06a.png">

Any best leads here @noahmanger / @nickykrause / @onezerojeremy ?

**Comment by nickykrause** [comment]
Thanks for the summary @jenniferthibault! 

My gut reaction was: If we can keep the search bar visible, we should, because it makes sense to avoid adding time/cognitive load to the interaction whenever possible. That initial reaction is tempered by the idea that having things "too cluttered" might also add to the load, but, the area in which we are placing the search does not seem at all cluttered to me, which feels like an argument for leaving the bar accessible.

Then my next thought was about "noticeability" - the search bar with an exposed box is more noticeable, but, as you alluded to, do we want it to be "alluring"? Will users be compelled to go straight to search, if the box is exposed, rather than at least trying the nav? 
- Response to this: Do we care if users go straight to search? Should we try to influence their behavior to avoid using the search, if possible? I can't think of a good reason that we should try to influence their behavior unless we believe strongly that the search experience will be inferior to the nav experience (or even the navigate-via-homepage-content-links experience)

All of that aside, I did a little checking on research that might exist (admittedly _very_ little) and came up with [this from NN group (2014)](https://www.nngroup.com/articles/magnifying-glass-icon/). The conclusions there are:
- The word "search" is not needed; users have reached a point where they recognize the symbol alone
- **Icon-only designs make search harder to find:**
>Above all, retain an open text-entry field next to the icon in the desktop version of a website. It’s also best to retain the text field on tablets. When a site is viewed on small screens (such as those of smartphones and smartwatches), the text box can be hidden until the user touches the magnifying-glass icon. And in each of these cases, there is no need to include a label within the search box.
- Search should be placed in the upper-right of the screen
- Users should be able to initiate search by hitting `enter` AND hitting the icon (people still do both)

So, maybe we try exposed search box first and then test? If we're having a lot of user frustration with the search results, then we minimize its visual prominence by going icon-only?

**Comment by noahmanger** [comment]
That all makes sense to me! Let's go with it expanded for now.

**Comment by jenniferthibault** [comment]
That makes sense to me. If we followed our established pattern on mobile/tablet, it would integrate into the menu like this:

![screen shot 2017-04-12 at 8 57 00 am](https://cloud.githubusercontent.com/assets/11636908/24958670/1b37626c-1f5e-11e7-9dd8-62bef531ae29.png)

Addressing an additional completion criteria: `Should we remove the search bars in the breadcrumb bars in the /data section?`
I think yes, we should remove the search bars from the breadcrumb areas on the data side, since this search functionality will be right above it and equal (better, even since it searches both candidates and committees at the same time!)
@noahmanger can we make the search bar on the data landing page search both candidates and committees yet? It will seem odd to have search bars that seemingly do the same thing, but don't.

**Comment by noahmanger** [comment]
That all looks good. And yes, we can unify. It's not technically hard, but there's then the need to design the results. If we can use the same pattern that we use for the general search results, then that could be not much extra work.
