### ISSUE TITLE
Publication date for FEC Record Articles?

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#973]
@amypike commented on [Mon Apr 10 2017](https://github.com/18F/FEC/issues/3952)

Hi there!  This page shows the date "September 27, 2012" on the top right-hand corner of the page.  It may not be clear to users that this is the date the article was published in the FEC Record and it does not mean that this information was last updated September 27, 2012.   

https://beta.fec.gov/updates/voter-registration-activity-and-gotv/

Thanks!

**Comment by emileighoutlaw** [comment]
More context: 

> My concern is that a date is listed in the top right-hand corner of RECORD articles, but it isn't clear that it is a "publication date," which might lead a user to wonder if the information on that page is no longer accurate/up to date.  The other pages do not have a date listed, for example.   One possible solution is to remove the publication date entirely.  I will be curious what usability testing reveals.


And calling in @dorothyyeager, @gsmaragdis, and @amypike to continue discussion!

**Comment by gsmaragdis** [comment]
I am fine with putting in Publication Date

**Comment by amypike** [comment]
How do y'all feel about "original publication date?"  To me, that telegraphs that this is material that was published someplace else, at some point in the recent past, but is still reliable information.  @emileighoutlaw @gsmaragdis @dorothyyeager

**Comment by emileighoutlaw** [comment]
Hi! Before we jump to solutions, I was hoping we could chat a little more about what we think the challenge is. I have a couple of questions, specifically—  I have a couple questions about this! 😄 

First, are we talking about the date that appears in the feed or the article page, or both?
_Feed_
![screen shot 2017-04-10 at 12 45 31 pm](https://cloud.githubusercontent.com/assets/10552702/24874772/748ada66-1deb-11e7-9b08-44399fe0b281.png)

_Article page_
![screen shot 2017-04-10 at 12 45 46 pm](https://cloud.githubusercontent.com/assets/10552702/24874792/7ed4635c-1deb-11e7-8bec-c76497a9d7be.png)

Press releases also have a publication date. Does this issue apply to those pages, too?
_Press release date_
![screen shot 2017-04-10 at 12 46 59 pm](https://cloud.githubusercontent.com/assets/10552702/24874865/af5847aa-1deb-11e7-8abe-6be8e870e452.png)

Then digging into the concerns here — is our primary concern that users may misinterpret what the date means? And can we talk a little more about what they might misunderstand that date to mean? And what are the risks if they do misunderstand?

I know that's a ton of questions! Thanks for thinking them through with me!!

**Comment by amypike** [comment]
@emileighoutlaw In answer to your first question, I think it's both - the date that appears in the feed and in the article.  None of our other content in the candidate and committee pages has a date attached to it. so the date stands out from the rest of the content.   And my concern is because there is a date attached to this content, it makes the content seem less reliable because the publication date is sometimes many years ago.   Technically, there is a date that is attached to all of our content because the content is ripped out of a campaign guide, which has a publication date.  However, the publication date is not listed for those sections of content but it is listed for RECORD articles.  A user might see a Record article that was posted in 2013 - and look at other candidate committee pages that have no content - and assume that that RECORD article is out-of-date.  This would be a problem for a number of reasons, most important is that Record articles are often the most-up-to-date information available.  It would be a shame if listing a date made users believe the exact opposite.    On our current website, it is very clear when a user is looking at a page that is a Record article but on the beta, it is easy to miss the heading "Outreach: the Record."  Also, on the current website, there's an explanation that the RECORD is an FEC publication, formerly a hard copy monthly publication.  It also distinguishes between the Record as a Commission publication and other official Commission documents, like Federal Register notices, AOs, etc.  

 Also, I just realized that by capitalizing The Record in these posts, it may look like I am shouting. I'm not, just not used to working without italics.  I'm sorry!  @gsmaragdis @dorothyyeager @AmyKort

**Comment by dorothyyeager** [comment]
I've always loved that the RECORD shouts :')

Article date would be my suggestion for the Record articles. 

For the other pages, I've seen other federal gov't websites that will have a "date last reviewed"

Example taken from IRS's political organizations page:
_Page Last Reviewed or Updated: 02-Nov-2012_

I know in Wagtail we've got dates on the help for committees pages; I think it's just they aren't visible? Maybe it's worth considering if they should be?

**Comment by gsmaragdis** [comment]
I am not certain if we want to go down the date last reviewed path.

**Comment by amypike** [comment]
@gsmaragdis Yeah, think OGC might have an issue with "date last reviewed."
